### ISSUE TITLE
[Bug]: Not launching right after fresh installation

### ISSUE THREAD

**Issue by popsoda27** [lshqqytiger/stable-diffusion-webui-directml#107]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Not launching right after fresh installation. Console tells me I need to manually upgrade pip.
Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check.

### Steps to reproduce the problem

As per installation guide on main page: Installed exact version Python 3.10.6, installed Git, downloaded the repo, ran the webui-user.bat

### What should have happened?

WebUI to launch successfully on localhost.

### Commit where the problem happens

5ab7f213bec2f816f9c5644becb32eb72c8ffb89

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of extensions

No

### Console logs

```Shell
Creating venv in directory E:\Downloads\stable-diffusion-webui\venv using python "C:\Users\popso\AppData\Local\Programs\Python\Python310\python.exe"
venv "E:\Downloads\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 5ab7f213bec2f816f9c5644becb32eb72c8ffb89
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Collecting torch==2.0.0
  Using cached https://download.pytorch.org/whl/cu118/torch-2.0.0%2Bcu118-cp310-cp310-win_amd64.whl (2611.3 MB)
Collecting torchvision==0.15.1
  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.15.1%2Bcu118-cp310-cp310-win_amd64.whl (4.9 MB)
Collecting jinja2
  Using cached https://download.pytorch.org/whl/Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting networkx
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting filelock
  Using cached filelock-3.12.0-py3-none-any.whl (10 kB)
Collecting sympy
  Using cached https://download.pytorch.org/whl/sympy-1.11.1-py3-none-any.whl (6.5 MB)
Collecting requests
  Using cached requests-2.29.0-py3-none-any.whl (62 kB)
Collecting pillow!=8.3.*,>=5.3.0
  Using cached Pillow-9.5.0-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting numpy
  Using cached numpy-1.24.3-cp310-cp310-win_amd64.whl (14.8 MB)
Collecting MarkupSafe>=2.0
  Using cached https://download.pytorch.org/whl/MarkupSafe-2.1.2-cp310-cp310-win_amd64.whl (16 kB)
Collecting certifi>=2017.4.17
  Using cached https://download.pytorch.org/whl/certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting idna<4,>=2.5
  Using cached https://download.pytorch.org/whl/idna-3.4-py3-none-any.whl (61 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.1.0-cp310-cp310-win_amd64.whl (97 kB)
Collecting mpmath>=0.19
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, numpy, networkx, MarkupSafe, idna, filelock, charset-normalizer, certifi, requests, jinja2, torch, torchvision
Successfully installed MarkupSafe-2.1.2 certifi-2022.12.7 charset-normalizer-3.1.0 filelock-3.12.0 idna-3.4 jinja2-3.1.2 mpmath-1.3.0 networkx-3.1 numpy-1.24.3 pillow-9.5.0 requests-2.29.0 sympy-1.11.1 torch-2.0.0+cu118 torchvision-0.15.1+cu118 typing-extensions-4.5.0 urllib3-1.26.15

[notice] A new release of pip available: 22.2.1 -> 23.1.2
[notice] To update, run: E:\Downloads\stable-diffusion-webui\venv\Scripts\python.exe -m pip install --upgrade pip
Traceback (most recent call last):
  File "E:\Downloads\stable-diffusion-webui\launch.py", line 352, in <module>
    prepare_environment()
  File "E:\Downloads\stable-diffusion-webui\launch.py", line 257, in prepare_environment
    run_python("import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'")
  File "E:\Downloads\stable-diffusion-webui\launch.py", line 120, in run_python
    return run(f'"{python}" -c "{code}"', desc, errdesc)
  File "E:\Downloads\stable-diffusion-webui\launch.py", line 96, in run
    raise RuntimeError(message)
RuntimeError: Error running command.
Command: "E:\Downloads\stable-diffusion-webui\venv\Scripts\python.exe" -c "import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check


Press any key to continue . . .
```

### Additional information

AMD 6700XT
Win 11 Pro

**Comment by lshqqytiger** [comment]
It seems that you cloned upstream repository.
Clone `https://github.com/lshqqytiger/stable-diffusion-webui-directml` and try again with it.

**Comment by popsoda27** [comment]
Thank you for your reply @lshqqytiger.

I tried your suggested repo. Upon webui-user.bat, everything installs fine automatically and it finally launches.
However at the bottom I noticed this:
python: 3.10.6  •  torch: 2.0.0+cpu  •  xformers: N/A  •  gradio: 3.28.1  •  commit: [3284ccc0]

It's on torch 2 and cpu only? I thought this could run on AMD GPUs.

**Comment by popsoda27** [comment]
> Thank you for your reply @lshqqytiger.
> 
> I tried your suggested repo. Upon webui-user.bat, everything installs fine automatically and it finally launches. However at the bottom I noticed this: python: 3.10.6  •  torch: 2.0.0+cpu  •  xformers: N/A  •  gradio: 3.28.1  •  commit: [[3284ccc](https://github.com/lshqqytiger/stable-diffusion-webui-directml/commit/3284ccc091f09146997fd93bb88a2ecd27ab3a1b)]
> 
> It's on torch 2 and cpu only? I thought this could run on AMD GPUs.

Sorry I stand corrected. I tried generating and indeed is using GPU. Thank you again @lshqqytiger
