### ISSUE TITLE
[Bug]: on fresh install: "ModuleNotFoundError: No module named 'basicsr.version'"

### ISSUE THREAD

**Issue by p4rsl3y** [lshqqytiger/stable-diffusion-webui-directml#114]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When running 'webui-user.bat' following the instructions on the install page, after the installation of the requirements and launching 'web UI with arguments:' a 'modulenotfounderror' occurred.

I am trying to install the program on a pc running windows10 pro
- running an AMD 6950xt GPU with the latest drivers installed
- intel CPU

### Steps to reproduce the problem

1. make a new installation of github.com/lshqqytiger/stable-diffusion-webui-directml
2. launch webui-user.bat

### What should have happened?

the webui should have launched without any errors

### Commit where the problem happens

 36db52a

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
No
```

### List of extensions

No

### Console logs

```Shell
Creating venv in directory F:\stable-diffusion-webui-directml\venv using python "C:\Users\Parsley\AppData\Local\Programs\Python\Python310\python.exe"
venv "F:\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 36db52a5d22e3a89af9dddae765aaa7f068494bd
Installing torch and torchvision
Collecting torch==2.0.0
  Using cached torch-2.0.0-cp310-cp310-win_amd64.whl (172.3 MB)
Collecting torchvision==0.15.1
  Using cached torchvision-0.15.1-cp310-cp310-win_amd64.whl (1.2 MB)
Collecting torch-directml
  Using cached torch_directml-0.2.0.dev230426-cp310-cp310-win_amd64.whl (8.2 MB)
Collecting sympy
  Using cached sympy-1.11.1-py3-none-any.whl (6.5 MB)
Collecting filelock
  Using cached filelock-3.12.0-py3-none-any.whl (10 kB)
Collecting networkx
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting typing-extensions
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting jinja2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting requests
  Using cached requests-2.30.0-py3-none-any.whl (62 kB)
Collecting numpy
  Using cached numpy-1.24.3-cp310-cp310-win_amd64.whl (14.8 MB)
Collecting pillow!=8.3.*,>=5.3.0
  Using cached Pillow-9.5.0-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.2-cp310-cp310-win_amd64.whl (16 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.1.0-cp310-cp310-win_amd64.whl (97 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.0.2-py3-none-any.whl (123 kB)
Collecting mpmath>=0.19
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, numpy, networkx, MarkupSafe, idna, filelock, charset-normalizer, certifi, requests, jinja2, torch, torchvision, torch-directml
Successfully installed MarkupSafe-2.1.2 certifi-2023.5.7 charset-normalizer-3.1.0 filelock-3.12.0 idna-3.4 jinja2-3.1.2 mpmath-1.3.0 networkx-3.1 numpy-1.24.3 pillow-9.5.0 requests-2.30.0 sympy-1.11.1 torch-2.0.0 torch-directml-0.2.0.dev230426 torchvision-0.15.1 typing-extensions-4.5.0 urllib3-2.0.2

[notice] A new release of pip available: 22.2.1 -> 23.1.2
[notice] To update, run: F:\stable-diffusion-webui-directml\venv\Scripts\python.exe -m pip install --upgrade pip
Installing gfpgan
Installing clip
Installing open_clip
Cloning Taming Transformers into F:\stable-diffusion-webui-directml\repositories\taming-transformers...
Cloning CodeFormer into F:\stable-diffusion-webui-directml\repositories\CodeFormer...
Cloning BLIP into F:\stable-diffusion-webui-directml\repositories\BLIP...
Cloning stable-diffusion-stability-ai into F:\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai...
Cloning k-diffusion into F:\stable-diffusion-webui-directml\repositories\k-diffusion...
Installing requirements for CodeFormer
Installing requirements
Launching Web UI with arguments:
Traceback (most recent call last):
  File "F:\stable-diffusion-webui-directml\launch.py", line 355, in <module>
    start()
  File "F:\stable-diffusion-webui-directml\launch.py", line 346, in start
    import webui
  File "F:\stable-diffusion-webui-directml\webui.py", line 35, in <module>
    from modules import extra_networks, ui_extra_networks_checkpoints
  File "F:\stable-diffusion-webui-directml\modules\ui_extra_networks_checkpoints.py", line 5, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "F:\stable-diffusion-webui-directml\modules\shared.py", line 94, in <module>
    import modules.dml
  File "F:\stable-diffusion-webui-directml\modules\dml\__init__.py", line 4, in <module>
    import modules.dml.hijack
  File "F:\stable-diffusion-webui-directml\modules\dml\hijack\__init__.py", line 4, in <module>
    import modules.dml.hijack.realesrgan_model
  File "F:\stable-diffusion-webui-directml\modules\dml\hijack\realesrgan_model.py", line 4, in <module>
    from realesrgan import RealESRGANer
  File "F:\stable-diffusion-webui-directml\venv\lib\site-packages\realesrgan\__init__.py", line 2, in <module>
    from .archs import *
  File "F:\stable-diffusion-webui-directml\venv\lib\site-packages\realesrgan\archs\__init__.py", line 2, in <module>
    from basicsr.utils import scandir
  File "F:\stable-diffusion-webui-directml\repositories\CodeFormer\basicsr\__init__.py", line 11, in <module>
    from .version import __gitsha__, __version__
ModuleNotFoundError: No module named 'basicsr.version'
Press any key to continue . . .
```

**Comment by p4rsl3y** [comment]
Update:

I got it working again by git cloning the basicsr source on github https://github.com/XPixelGroup/BasicSR.git
into F:\stable-diffusion-webui-directml\repositories\CodeFormer\basicsr
so now i have F:\stable-diffusion-webui-directml\repositories\CodeFormer\basicsr\BasicSR

and running "python setup.py develop"

Note: along the way i also set 'include-system-site-packages = true'
in \stable-diffusion-webui\venv\pyvenv.cfg

but i have no clue what effect this had on the end result.
