### ISSUE TITLE
[Bug]: restore faces error

### ISSUE THREAD

**Issue by AKingkai** [lshqqytiger/stable-diffusion-webui-directml#12]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Tick restore faces ,Prompt for errors in the last step.

Error completing request
TypeError: 'NoneType' object is not subscriptable

### Steps to reproduce the problem

1. Tick restore faces ,
2. prompt ' boy face '
3. generate
4.last step error

### What should have happened?

finish

### Commit where the problem happens

c8882499

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--opt-sub-quad-attention --precision full --no-half --medvram --no-half-vae --share --opt-split-attention-v1 --disable-nan-check
```

### List of extensions

LDSR | built-in |   |  
Lora | built-in |   |  
ScuNET | built-in |   |  
SwinIR | built-in |   |  
prompt-bracket-checker | built-in

### Console logs

```Shell
ebui-directml\venv\Scripts\Python.exe"
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Commit hash: c88824995d87be36a62b110dd509ff7ccb6eeaa2
Installing requirements for Web UI
Launching Web UI with arguments: --opt-sub-quad-attention --precision full --no-half --medvram --no-half-vae --share --opt-split-attention-v1 --disable-nan-check
Warning: experimental graphic memory optimization is disabled due to gpu vendor. Currently this optimization is only available for AMDGPUs.
Disabled experimental graphic memory optimizations.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
Loading weights [7234b76e42] from D:\SD\stable-diffusion-webui-directml\models\Stable-diffusion\Chilloutmix-Ni.safetensors
Creating model from config: D:\SD\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying sub-quadratic cross attention optimization.
Textual inversion embeddings loaded(1): ulzzang-6500-v1.1
Model loaded in 1.3s (create model: 0.5s, apply weights to model: 0.7s).
Running on local URL:  http://127.0.0.1:7860
Running on public URL: https://xxxxxxxxxxxxxx.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades (NEW!), check out Spaces: https://huggingface.co/spaces
100%|█████████████████████████████████████| 20/20 [00:07<00:00,  2.63it/s]
Error verifying pickled file from D:\SD\stable-diffusion-webui-directml\models\Codeformer\tmp1eiusxvd:
Traceback (most recent call last):
  File "D:\SD\stable-diffusion-webui-directml\modules\safe.py", line 81, in check_pt
    with zipfile.ZipFile(filename) as z:
  File "C:\Users\CXK\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1267, in __init__
    self._RealGetContents()
  File "C:\Users\CXK\AppData\Local\Programs\Python\Python310\lib\zipfile.py", line 1334, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\SD\stable-diffusion-webui-directml\modules\safe.py", line 135, in load_with_extra
    check_pt(filename, extra_handler)
  File "D:\SD\stable-diffusion-webui-directml\modules\safe.py", line 102, in check_pt
    unpickler.load()
_pickle.UnpicklingError: persistent IDs in protocol 0 must be ASCII strings

-----> !!!! The file is most likely corrupted !!!! <-----
You can skip this check with --disable-safe-unpickle commandline argument, but that is not going to help you.


Error completing request
Arguments: ('task(5a7r42gce19wgdb)', 'boy face', '', [], 20, 0, True, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 200, 200, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "D:\SD\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\SD\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\SD\stable-diffusion-webui-directml\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "D:\SD\stable-diffusion-webui-directml\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "D:\SD\stable-diffusion-webui-directml\modules\processing.py", line 661, in process_images_inner
    x_sample = modules.face_restoration.restore_faces(x_sample)
  File "D:\SD\stable-diffusion-webui-directml\modules\face_restoration.py", line 19, in restore_faces
    return face_restorer.restore(np_image)
  File "D:\SD\stable-diffusion-webui-directml\modules\codeformer_model.py", line 88, in restore
    self.create_models()
  File "D:\SD\stable-diffusion-webui-directml\modules\codeformer_model.py", line 65, in create_models
    checkpoint = torch.load(ckpt_path)['params_ema']
TypeError: 'NoneType' object is not subscriptable
```

### Additional information

RX590
win10
cup i5-8500

**Comment by SilverThread0814** [comment]
when i  using the restore faces every time and it's the same unusable,i am 6800XT

**Comment by SilverThread0814** [comment]
100%|█████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.09it/s]
Error completing request:07,  3.01it/s]
Arguments: ('task(ehx61v98t0h2uvw)', '1girl,', '', [], 20, 0, True, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'Refresh models', False, 'none', 'None', 1, None, False, 'Scale to Fit (Inner Fit)', False, False, 64, 64, 64, 1, 0.9, 5, '0.0001', False, 'None', '', 0.1, False, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "J:\WEBUI\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "J:\WEBUI\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "J:\WEBUI\stable-diffusion-webui-directml\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "J:\WEBUI\stable-diffusion-webui-directml\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "J:\WEBUI\stable-diffusion-webui-directml\modules\processing.py", line 661, in process_images_inner
    x_sample = modules.face_restoration.restore_faces(x_sample)
  File "J:\WEBUI\stable-diffusion-webui-directml\modules\face_restoration.py", line 19, in restore_faces
    return face_restorer.restore(np_image)
  File "J:\WEBUI\stable-diffusion-webui-directml\modules\codeformer_model.py", line 88, in restore
    self.create_models()
  File "J:\WEBUI\stable-diffusion-webui-directml\modules\codeformer_model.py", line 65, in create_models
    checkpoint = torch.load(ckpt_path)['params_ema']
  File "J:\WEBUI\stable-diffusion-webui-directml\modules\safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "J:\WEBUI\stable-diffusion-webui-directml\modules\safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "J:\WEBUI\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 777, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "J:\WEBUI\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by OldPixelReaper** [comment]
Face Restore works for me with CodeFormer, but with GFPGAN I only get colorful broken faces. 

With this installation it works:
https://github.com/TencentARC/GFPGAN

However, after about 30 minutes of use with stable-diffusion-webui-directml, my PC suddenly shuts down. My PC is in good shape, I edit videos with it, I create games with Unreal Engine, and I use https://github.com/azuritecoin/OnnxDiffusersUI for hours without problems. So it seems to be a program specific problem.

But I'm still glad that this exists, I have hope that some things will be fixed here:-)

big thx

Win11 AMD RX 5700 XT, latest drivers....

**Comment by OldPixelReaper** [comment]
I know that many have the problem of a shortage of electricity. In my case, this does not apply.

**Comment by biderpan-ai** [comment]
I have this same problem ，but i fix it，cd stable-diffusion-webui-directml\repositories\CodeFormer\weights\facelib and redownload 'parsing_parsenet.pth'and'detection_Resnet50_Final.pth' ,it can use Restore faces
