### ISSUE TITLE
[Bug]: Generation Immediately Fails with "The Parameter Is Incorrect" Error

### ISSUE THREAD

**Issue by flaccidbagel** [lshqqytiger/stable-diffusion-webui-directml#122]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Any form of generation results in an immediate error. As suggested in previous reports, I've both deleted the venv folder as well as performed complete fresh installations. I simply cannot generate anything. Using the original, non-forked version and my older Nvidia card functions.

### Steps to reproduce the problem

1. Go to UI webpage
2. Insert any words for txt2img
3. Press Generate

### What should have happened?

Some form of output.

### Commit where the problem happens

https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a20efa1f8355d967d4bd0a42238c3f6120f74cf5

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--opt-split-attention --lowvram --precision full --no-half --always-batch-cond-uncond --disable-safe-unpickle
```

### List of extensions

Lora
Lycoris
Locon

### Console logs

```Shell
0%|                                                                                           | 0/31 [00:01<?, ?it/s]
Error completing request
Arguments: ('task(x0c408oixid38tr)', '(masterpiece), best quality, natural lighting, Man in front of phone booth', '', [], 31, 0, False, False, 1, 8, 7, -1.0, -1.0, 0, 0, 0, False, 800, 600, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0) {}
Traceback (most recent call last):
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\modules\processing.py", line 515, in process_images
    res = process_images_inner(p)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\modules\processing.py", line 669, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\modules\processing.py", line 887, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 377, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 251, in launch_sampling
    return func()
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 377, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\sampling.py", line 153, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 135, in forward
    x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict([cond_in], image_cond_in))
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 797, in forward
    h = module(h, emb, context)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 334, in forward
    x = block(x, context=context[i])
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 269, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 136, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 272, in _forward
    x = self.attn1(self.norm1(x), context=context if self.disable_self_attn else None) + x
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\modules\sd_hijack_optimizations.py", line 131, in split_cross_attention_forward
    s1 = einsum('b i d, b j d -> b i j', q[:, i:end], k)
  File "S:\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\functional.py", line 378, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
RuntimeError: The parameter is incorrect.
```

### Additional information

Specs:
Processor: AMD Ryzen 5 5600X 6-Core Processor (12 CPUs), ~3.7GHz
Memory: 32768MB RAM
Available OS Memory: 32694MB RAM
Card name: AMD Radeon RX 6700 XT
Display Memory: 28590 MB
Dedicated Memory: 12243 MB
Shared Memory: 16347 MB

**Comment by JJGall** [comment]
Does 512x512 work fine? You might be trying to generate too high of a resolution.

**Comment by lshqqytiger** [comment]
Which versions of torch and torch-directml did you use?

**Comment by flaccidbagel** [comment]
I can definitely give 512x512 a go, but I wasn't aware that would be a limitation, especially as the current GPU should be a direct upgrade over the Nvidia (1070 TI). I can definitely give that a go, however if I raise the resolution too high, I do get a VRAM error instead as expected.

Regarding torch versions, I'm not certain how to confirm that. As I was going with the standard documented install method, I'm assuming it would be whichever version is currently the default. If there's a method of confirming that I'll definitely check and follow up.

**Comment by lshqqytiger** [comment]
You can get the versions of torch and torch-directml using the commands below.
```
PS > .\venv\Scripts\Activate.ps1
(venv) PS > pip show torch
(venv) PS > pip show torch-directml
```

**Comment by flaccidbagel** [comment]
Thank you. Results below:

Name: torch
Version: 2.0.0
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: s:\stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages
Requires: filelock, jinja2, networkx, sympy, typing-extensions
Required-by: accelerate, basicsr, clean-fid, clip, facexlib, gfpgan, kornia, lpips, open-clip-torch, pytorch-lightning, realesrgan, timm, torch-directml, torchdiffeq, torchmetrics, torchsde, torchvision

Name: torch-directml
Version: 0.2.0.dev230426
Summary: A DirectML backend for hardware acceleration in PyTorch.
Home-page: https://github.com/microsoft/directml
Author: Microsoft Corporation
Author-email: askdirectml@microsoft.com
License: MIT
Location: s:\stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages
Requires: torch, torchvision
Required-by:

**Comment by lshqqytiger** [comment]
`RuntimeError: The parameter is incorrect.` error occurs when the specific feature is not implemented on torch-directml yet.
But `einsum` is already implemented and I can't reproduce this issue.. very weird.

**Comment by cwb78** [comment]
I'm having the same error. I can't generate any images at any size. Brand new, fresh install. Only the base model, no extensions or extras. Same video card, AMD 6700 XT. Windows 10.

**Comment by songib** [comment]
Got the same issue the first time I click Generate, but after that, it went away the second time I try to generate. 
Maybe the extension bugs or something. but idk yet.

**Comment by Dash3210** [comment]
Hey, getting same problem Installed everything then the window opens perfectly but by entering prompt and hitting generate it gives the same error, though my computer is very old and have no ram compared to latest computers, it is a 4gb intel 5005u...yup very bad

**Comment by megazaz80** [comment]
> You can get the versions of torch and torch-directml using the commands below.
> 
> ```
> PS > .\venv\Scripts\Activate.ps1
> (venv) PS > pip show torch
> (venv) PS > pip show torch-directml
> ```

I did something really strange yesterday because my SD was broken I copy paste my older backup over the new one and then something strange happen my speeds go over the roof, before for generating 512x720 one step was over 6 secs now I getting 1.18, btw my card is rx6600xt 
![IMG_20230521_105215879_HDR~2](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/70824762/d167325f-1c25-4a31-8f71-d90f91867b92)

**Comment by lshqqytiger** [comment]
1.18s/it for RX 6600 XT is normal.
My RX 5700 XT, which has similar performance to yours, is up to 1.07it/s. (--no-half --opt-sub-quad-attention)

**Comment by NoAvailableAlias** [comment]
Also getting the same results as Kert for larger than 768 on an intel a770. In fact, tried all permutations of the Optimizations settings including cross attention and couldn't get large images to generate without a RuntimeError parameter incorrect.

Some cross attention types would fail right at the transition to hires processing and others would fail at the very end of hires.

**Comment by Wookfg** [comment]
I got this then ran the pip update and it went away
<insert path here>\stable-diffusion-webui-directml\venv\Scripts\python.exe -m pip install --upgrade pip

**Comment by MaciejGorczyca** [comment]
I was also having the error mentioned by @Kert and then I tried to run without any --opt-something arg but would run out of memory quickly. I tried running it with the args mentioned by @lshqqytiger `--no-half --opt-sub-quad-attention` and hires fix works now and I don't run out of memory for reasonable resolutions. I'm using RX 6900 XT.

**Comment by bkrew** [comment]
I noticed that the Option resize by often causes that kind of errors. it doesnt care if the outcome of the resizing is divideable by 8.

**Comment by PDCWolf** [comment]
Same problem, clean install on a 6750XT, tried --no-half --no-half-vae --always-batch-cond-uncond, also adding --precision full, and --medvram 

Torch 2.0.0, Torch-directml 0.2.0.dev230426

**Comment by PDCWolf** [comment]
Excuse my lack of etiquette, wasn't sure if I should edit to add extra info or add a new comment. the --no-half --opt-sub-quad-attention solved the issue.
