### ISSUE TITLE
[Bug]: SD has an error as soon as it finishes making a picture, please help.

### ISSUE THREAD

**Issue by Tord44** [lshqqytiger/stable-diffusion-webui-directml#125]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

So i started up SD for the first time, i try to create something and write a normal prompt and it starts creating, everything goes completely fine as usual, but once it finishes it gives me this message and the drawing gets deleted before it gets finished 
![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/44593348/c29102f3-c862-4546-85b9-77b8ae7f56f7)

### Steps to reproduce the problem

1. starting up Stable diffusion
2. writing a prompt 
3. pressing the generate button
4. waiting for it to finish
5. it finishes and i get the error message and the drawing gets deleted

### What should have happened?

it shouldve just generated the picture which i was trying to generate with simple prompts that were like 6 words long.

### Commit where the problem happens

version:  •  python: 3.10.6  •  torch: 2.0.0+cpu  •  xformers: 0.0.17  •  gradio: 3.29.0  •  checkpoint: d1c96253ed

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome, Brave

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS= --medvram --precision full --xformers --upcast-sampling are the code lines i use when i start up SD
```

### List of extensions

No

### Console logs

```Shell
D:\Stable diffusion\webui\stable-diffusion-webui-directml>git pull
Already up to date.
venv "D:\Stable diffusion\webui\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: <none>
Commit hash: 3f52b28025efbc52c2a745d34bc7ed37710c7a1c
Installing requirements
Launching Web UI with arguments: --medvram --precision full --xformers --upcast-sampling
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.0+cu118 with CUDA 1108 (you have 2.0.0+cpu)
    Python  3.10.10 (you have 3.10.6)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
Loading weights [d1c96253ed] from D:\Stable diffusion\webui\stable-diffusion-webui-directml\models\Stable-diffusion\meinaunreal_v3.safetensors
Creating model from config: D:\Stable diffusion\webui\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 8.1s (import torch: 2.2s, import gradio: 1.4s, import ldm: 0.7s, other imports: 1.0s, load scripts: 1.6s, create ui: 1.0s, gradio launch: 0.1s).
Applying cross attention optimization (InvokeAI).
Textual inversion embeddings loaded(0):
Model loaded in 4.1s (load weights from disk: 0.4s, create model: 0.9s, apply weights to model: 0.9s, apply half(): 0.7s, load VAE: 0.1s, hijack: 1.1s).
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:37<00:00,  1.86s/it]
Error completing request███████████████████████████████████████████████████████████████| 20/20 [00:33<00:00,  1.73s/it]
Arguments: ('task(i2s0znyihmjpq35)', 'clear blue skies', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0) {}
Traceback (most recent call last):
  File "D:\Stable diffusion\webui\stable-diffusion-webui-directml\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "D:\Stable diffusion\webui\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\Stable diffusion\webui\stable-diffusion-webui-directml\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "D:\Stable diffusion\webui\stable-diffusion-webui-directml\modules\processing.py", line 526, in process_images
    res = process_images_inner(p)
  File "D:\Stable diffusion\webui\stable-diffusion-webui-directml\modules\processing.py", line 682, in process_images_inner
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "D:\Stable diffusion\webui\stable-diffusion-webui-directml\modules\processing.py", line 682, in <listcomp>
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "D:\Stable diffusion\webui\stable-diffusion-webui-directml\modules\processing.py", line 444, in decode_first_stage
    x = model.decode_first_stage(x)
  File "D:\Stable diffusion\webui\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "D:\Stable diffusion\webui\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 26, in __call__
    return self.__sub_func(self.__orig_func, *args, **kwargs)
  File "D:\Stable diffusion\webui\stable-diffusion-webui-directml\modules\sd_hijack_unet.py", line 76, in <lambda>
    first_stage_sub = lambda orig_func, self, x, **kwargs: orig_func(self, x.to(devices.dtype_vae), **kwargs)
  File "D:\Stable diffusion\webui\stable-diffusion-webui-directml\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Stable diffusion\webui\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 826, in decode_first_stage
    return self.first_stage_model.decode(z)
  File "D:\Stable diffusion\webui\stable-diffusion-webui-directml\modules\lowvram.py", line 52, in first_stage_model_decode_wrap
    return first_stage_model_decode(z)
  File "D:\Stable diffusion\webui\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 90, in decode
    dec = self.decoder(z)
  File "D:\Stable diffusion\webui\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Stable diffusion\webui\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 631, in forward
    h = self.mid.attn_1(h)
  File "D:\Stable diffusion\webui\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Stable diffusion\webui\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 258, in forward
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None, op=self.attention_op)
  File "D:\Stable diffusion\webui\stable-diffusion-webui-directml\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 196, in memory_efficient_attention
    return _memory_efficient_attention(
  File "D:\Stable diffusion\webui\stable-diffusion-webui-directml\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 294, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "D:\Stable diffusion\webui\stable-diffusion-webui-directml\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 310, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp)
  File "D:\Stable diffusion\webui\stable-diffusion-webui-directml\venv\lib\site-packages\xformers\ops\fmha\dispatch.py", line 98, in _dispatch_fw
    return _run_priority_list(
  File "D:\Stable diffusion\webui\stable-diffusion-webui-directml\venv\lib\site-packages\xformers\ops\fmha\dispatch.py", line 73, in _run_priority_list
    raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 4096, 1, 512) (torch.float16)
     key         : shape=(1, 4096, 1, 512) (torch.float16)
     value       : shape=(1, 4096, 1, 512) (torch.float16)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`cutlassF` is not supported because:
    device=privateuseone (supported: {'cuda'})
`flshattF` is not supported because:
    device=privateuseone (supported: {'cuda'})
    max(query.shape[-1] != value.shape[-1]) > 128
`tritonflashattF` is not supported because:
    device=privateuseone (supported: {'cuda'})
    max(query.shape[-1] != value.shape[-1]) > 128
    triton is not available
`smallkF` is not supported because:
    device=privateuseone (supported: {'cpu', 'cuda'})
    dtype=torch.float16 (supported: {torch.float32})
    max(query.shape[-1] != value.shape[-1]) > 32
    unsupported embed per head: 512
```

**Comment by JJGall** [comment]
remove --xformers, that is only for CUDA devices, so Nvidia etc.
