### ISSUE TITLE
[Bug]: Latest commit breaks webUI

### ISSUE THREAD

**Issue by hkpD** [lshqqytiger/stable-diffusion-webui-directml#130]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits

### What happened?

The latest webUI commit does not work on my computer. All of the latest commits worked before and I accidentally put "git pull" in my webui-user.bat and now I can't access webUI. 

### Steps to reproduce the problem

Clone the latest repo and run webui-user.bat

### What should have happened?

It should have opened the webUI. 

### Commit where the problem happens

f158f1032fd2e977cc884328a942c6ea0a6a06c5

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 6000 above)

### What browsers do you use to access the UI ?

Brave

### Command Line Arguments

```Shell
--no-half-vae --autolaunch --theme dark --skip-torch-cuda-test
```

### List of extensions

No

### Console logs

```Shell
Creating venv in directory H:\StableDiffusion\stable-diffusion-webui-directml\venv using python "C:\Users\toxyg\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe"
venv "H:\StableDiffusion\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: <none>
Commit hash: f158f1032fd2e977cc884328a942c6ea0a6a06c5
Installing torch and torchvision
H:\StableDiffusion\stable-diffusion-webui-directml\venv\Scripts\python.exe: Error while finding module specification for 'torch==2.0.0' (ModuleNotFoundError: No module named 'torch==2')
Traceback (most recent call last):
  File "H:\StableDiffusion\stable-diffusion-webui-directml\launch.py", line 37, in <module>
    main()
  File "H:\StableDiffusion\stable-diffusion-webui-directml\launch.py", line 29, in main
    prepare_environment()
  File "H:\StableDiffusion\stable-diffusion-webui-directml\modules\launch_utils.py", line 257, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "H:\StableDiffusion\stable-diffusion-webui-directml\modules\launch_utils.py", line 102, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install torch.
Command: "H:\StableDiffusion\stable-diffusion-webui-directml\venv\Scripts\python.exe" -m torch==2.0.0 torchvision==0.15.1 torch-directml
Error code: 1
Press any key to continue . . .
```

**Comment by VeteranXT** [comment]
Duplicate with #128

**Comment by lshqqytiger** [comment]
I wrote an announcement #131.
I'm sorry for a late announcement.
