### ISSUE TITLE
[Bug]: Unable to get extensions Load From:

### ISSUE THREAD

**Issue by VeteranXT** [lshqqytiger/stable-diffusion-webui-directml#132]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Clicked Load from button and showed me this error 

This is default link :  https://raw.githubusercontent.com/AUTOMATIC1111/stable-diffusion-webui-extensions/master/index.json

### Steps to reproduce the problem

Click on extensions tab
Click load from : 

### What should have happened?

Loaded all extensions with a list

### Commit where the problem happens

b4f34ad

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 6000 above)

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
-skip-torch-cuda-test --medvram --precision full --no-half
```

### List of extensions

Default

### Console logs

```Shell
Arguments: ('E:\\Storage\\Apps\\AI_Geneartor\\Stable_diffusin_Directtl\\extensions.html', ['ads', 'localization', 'installed'], 0) {}
Traceback (most recent call last):
  File "E:\Storage\Apps\AI_Geneartor\Stable_diffusin_Directtl\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "E:\Storage\Apps\AI_Geneartor\Stable_diffusin_Directtl\modules\ui_extensions.py", line 389, in refresh_available_extensions
    with urllib.request.urlopen(url) as response:
  File "C:\Users\Vlada\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Vlada\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 519, in open
    response = self._open(req, data)
  File "C:\Users\Vlada\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 541, in _open
    return self._call_chain(self.handle_open, 'unknown',
  File "C:\Users\Vlada\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 496, in _call_chain
    result = func(*args)
  File "C:\Users\Vlada\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 1419, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: e>

Traceback (most recent call last):
  File "E:\Storage\Apps\AI_Geneartor\Stable_diffusin_Directtl\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Storage\Apps\AI_Geneartor\Stable_diffusin_Directtl\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "E:\Storage\Apps\AI_Geneartor\Stable_diffusin_Directtl\venv\lib\site-packages\gradio\blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "E:\Storage\Apps\AI_Geneartor\Stable_diffusin_Directtl\venv\lib\site-packages\gradio\blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 5, received: 4).
Wanted outputs:
    [textbox, html, checkboxgroup, html, textbox]
Received outputs:
    [{'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, "<div class='error'>URLError: &lt;urlopen error unknown url type: e&gt;</div>"]
```

**Comment by VeteranXT** [comment]
found fix 
Adding this in launch.py after

from modules import launch_utils

import ssl
ssl._create_default_https_context = ssl._create_unverified_context

now loads all extensions and everything. And works. Hope this gets implemented?
