### ISSUE TITLE
[Bug]: Unable to get list of available extensions

### ISSUE THREAD

**Issue by VeteranXT** [lshqqytiger/stable-diffusion-webui-directml#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Started local server and pressed Extensions tab. available then Load Form:

Url was default to :https://raw.githubusercontent.com/AUTOMATIC1111/stable-diffusion-webui-extensions/master/index.json

### Steps to reproduce the problem

Launch Local WebUI
Open Local Adress with port
Click on Extensions
Click on Availabe
Click on Load From:

### What should have happened?

Show me list of all extensions that are installed or can be updated

### Commit where the problem happens

20ae71f

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 6000 above)

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--skip-torch-cuda-test --medvram --precision full --no-half --opt-sub-quad-attention
```

### List of extensions

Defaults

### Console logs

```Shell
Traceback (most recent call last):
  File "E:\Storage\Apps\AI_Geneartor\Stable_diffusin_Directtl\venv\lib\site-packages\gradio\routes.py", line 414, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Storage\Apps\AI_Geneartor\Stable_diffusin_Directtl\venv\lib\site-packages\gradio\blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "E:\Storage\Apps\AI_Geneartor\Stable_diffusin_Directtl\venv\lib\site-packages\gradio\blocks.py", line 1229, in postprocess_data
    self.validate_outputs(fn_index, predictions)  # type: ignore
  File "E:\Storage\Apps\AI_Geneartor\Stable_diffusin_Directtl\venv\lib\site-packages\gradio\blocks.py", line 1204, in validate_outputs
    raise ValueError(
ValueError: An event handler (f) didn't receive enough output values (needed: 5, received: 4).
Wanted outputs:
    [textbox, html, checkboxgroup, html, textbox]
Received outputs:
    [{'__type__': 'generic_update'}, {'__type__': 'generic_update'}, {'__type__': 'generic_update'}, "<div class='error'>SSLError: not enough data: cadata does not contain a certificate (_ssl.c:3989)</div>"]
```

**Comment by VeteranXT** [comment]
Fix: 

to Launch.py after
from modules import launch_utils

add following

import ssl
ssl._create_default_https_context = ssl._create_unverified_context
