### ISSUE TITLE
[Bug]: Runtime error with Hires. fix

### ISSUE THREAD

**Issue by FrakerKill** [lshqqytiger/stable-diffusion-webui-directml#143]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I can't generate images with Hires. fix option after new merge

### Steps to reproduce the problem

1. Go to generate 512x512 with Hires. fix with 1,65 with a RX6600
2. Press generate
3. And runtime error

### What should have happened?

Generate an image about 1MB

### Commit where the problem happens

WEBUI

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

Other GPUs

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
set PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.6,max_split_size_mb:128
set COMMANDLINE_ARGS=--medvram --always-batch-cond-uncond --precision full --no-half --opt-split-attention --opt-sub-quad-attention --sub-quad-q-chunk-size 512 --sub-quad-kv-chunk-size 512 --sub-quad-chunk-threshold 80 --disable-nan-check --use-cpu interrogate gfpgan codeformer --upcast-sampling --api --autolaunch --listen
set SAFETENSORS_FAST_GPU=1
```

### List of extensions

Controlnet
3dopenpose
aspect ratio

### Console logs

```Shell
Applying optimization: Doggettx... done.
Weights loaded in 42.6s (calculate hash: 22.9s, load weights from disk: 0.7s, apply weights to model: 18.9s).
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:19<00:00,  1.51it/s]
Total progress: 31it [04:16,  8.26s/it]
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [00:19<00:00,  1.51it/s]
Running DDIM Sampling with 19 timesteps███████████████████████████████████████████████████                                                  | 29/50 [00:48<00:14,  1.46it/s]
Decoding image:   0%|                                                                                                                                | 0/19 [00:03<?, ?it/s]
Error completing request
Arguments: ('task(7q1bkpifub8syg9)', '(masterpiece,best quality:1.4),ultra detailed,(big eyes:1.2)\n1 girl,solo,\nblonde hair,twintail\ngyaru\n(school uniform)\n( reaching out)\nhuge breasts,cleavage\nshame,smile\nschool classroom,', '(bad-artist:1.0), (bad-artist-anime:1.0), (bad_prompt_version2:0.8), (badhandv4:1.0), (negative_hand:1.0), (worst quality:2), (low quality:2), (normal quality:2), (monochrome:1.2), (grayscale:1.2), (EasyNegative:1.0), (ng_deepnegative_v1_75t:1.0),', [], 30, 21, False, False, 1, 1, 10, 644523516.0, -1.0, 0, 0, 0, False, 512, 512, True, 0.5, 1.7, '4x-UltraSharp', 20, 0, 0, 0, '', '', [], 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0) {}
Traceback (most recent call last):
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\txt2img.py", line 57, in txt2img
    processed = processing.process_images(p)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\processing.py", line 611, in process_images
    res = process_images_inner(p)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\processing.py", line 729, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\processing.py", line 1059, in sample
    samples = self.sampler.sample_img2img(self, samples, noise, self.hr_c, self.hr_uc, steps=self.hr_second_pass_steps or self.steps, image_conditioning=image_conditioning)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\sd_samplers_compvis.py", line 199, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.sampler.decode(x1, conditioning, t_enc, unconditional_guidance_scale=p.cfg_scale, unconditional_conditioning=unconditional_conditioning))
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\sd_samplers_compvis.py", line 51, in launch_sampling
    return func()
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\sd_samplers_compvis.py", line 199, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.sampler.decode(x1, conditioning, t_enc, unconditional_guidance_scale=p.cfg_scale, unconditional_conditioning=unconditional_conditioning))
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddim.py", line 333, in decode
    x_dec, _ = self.p_sample_ddim(x_dec, cond, ts, index=index, use_original_steps=use_original_steps,
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\sd_samplers_compvis.py", line 58, in p_sample_ddim_hook
    res = self.orig_p_sample_ddim(x_dec, cond, ts, *args, unconditional_conditioning=unconditional_conditioning, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\dml\hijack\stablediffusion.py", line 37, in p_sample_ddim
    model_uncond, model_t = self.model.apply_model(x_in, t_in, c_in).chunk(2)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 797, in forward
    h = module(h, emb, context)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 334, in forward
    x = block(x, context=context[i])
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 269, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 136, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 272, in _forward
    x = self.attn1(self.norm1(x), context=context if self.disable_self_attn else None) + x
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\sd_hijack_optimizations.py", line 251, in split_cross_attention_forward
    s1 = einsum('b i d, b j d -> b i j', q[:, i:end], k)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\venv\lib\site-packages\torch\functional.py", line 378, in einsum
    return _VF.einsum(equation, operands)  # type: ignore[attr-defined]
RuntimeError
```

**Comment by FrakerKill** [comment]
Finally, this error disappears but now UniPC sampler is taken all memory and can't do 640x640 for less than 8GB VRAM

**Comment by FrakerKill** [comment]
I go into last checkpoint until merge and UniPC works fine

**Comment by FrakerKill** [comment]
Traceback (most recent call last):
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\txt2img.py", line 94, in txt2img
    processed = processing.process_images(p)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\processing.py", line 613, in process_images
    res = process_images_inner(p)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\processing.py", line 731, in process_images_inner
    samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\processing.py", line 1061, in sample
    samples = self.sampler.sample_img2img(self, samples, noise, self.hr_c, self.hr_uc, steps=self.hr_second_pass_steps or self.steps, image_conditioning=image_conditioning)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 356, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 257, in launch_sampling
    return func()
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 356, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\sampling.py", line 626, in sample_dpmpp_2m_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 156, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict(c_crossattn, image_cond_in[a:b]))
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 797, in forward
    h = module(h, emb, context)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 334, in forward
    x = block(x, context=context[i])
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 269, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 136, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\venv\lib\site-packages\tomesd\patch.py", line 54, in _forward
    x = u_a(self.attn1(m_a(self.norm1(x)), context=context if self.disable_self_attn else None)) + x
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\venv\lib\site-packages\tomesd\merge.py", line 102, in merge
    unm = gather(src, dim=-2, index=unm_idx.expand(n, t1 - r, c))
RuntimeError

**Comment by FrakerKill** [comment]
the last error

**Comment by Pinoles17** [comment]
Did you find the solution? I have the same problem using hiresFix x2 (1024x1024) and find out that "no-half" is the problem, but you can't use Inpaint without it
