### ISSUE TITLE
[Bug]: Each time i try to open SD i get this

### ISSUE THREAD

**Issue by Spas120** [lshqqytiger/stable-diffusion-webui-directml#150]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Each time i try to open SD I get this error "ModuleNotFoundError: No module named 'onnxruntime'"

### Steps to reproduce the problem

just by trying to open SD

### What should have happened?

SD opening

### Commit where the problem happens

idk

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

CPU

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--opt-sub-quad-attention --medvram --autolaunch
```

### List of extensions

Image browser

### Console logs

```Shell
Launching Web UI with arguments: --opt-sub-quad-attention --medvram --autolaunch
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
Traceback (most recent call last):
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\launch.py", line 38, in <module>
    main()
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\launch.py", line 34, in main
    start()
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\launch_utils.py", line 351, in start
    import webui
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\webui.py", line 53, in <module>
    import modules.img2img
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\img2img.py", line 12, in <module>
    from modules.ui import plaintext_to_html
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\ui.py", line 19, in <module>
    from modules.sd_olive import optimize
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\sd_olive.py", line 6, in <module>
    import onnxruntime as ort
ModuleNotFoundError: No module named 'onnxruntime'
Press any key to continue . . .
```

**Comment by Nikitaefimov** [comment]
Same

**Comment by hkpD** [comment]
I am getting the same issue.

**Comment by hkpD** [comment]
He just updated the repository with a fix, but this is what I am receiving now after his fix

```
Calculating sha256 for H:\StableDiffusion\stable-diffusion-webui-directml\models\Stable-diffusion\CounterfeitV30_v30-fp16.ckpt: Traceback (most recent call last):
  File "H:\StableDiffusion\stable-diffusion-webui-directml\launch.py", line 38, in <module>
    main()
  File "H:\StableDiffusion\stable-diffusion-webui-directml\launch.py", line 34, in main
    start()
  File "H:\StableDiffusion\stable-diffusion-webui-directml\modules\launch_utils.py", line 355, in start
    webui.webui()
  File "H:\StableDiffusion\stable-diffusion-webui-directml\webui.py", line 376, in webui
    shared.demo = modules.ui.create_ui()
  File "H:\StableDiffusion\stable-diffusion-webui-directml\modules\ui.py", line 1160, in create_ui
    wrap_gradio_gpu_call(convert_to_onnx, extra_outputs=[""]),
NameError: name 'convert_to_onnx' is not defined
62f81a5ba8128b5bd38e30256074654a43f8a62bd33a4efc005e6a4ea987183a
```

**Comment by hkpD** [comment]
> 

I can CD myself to the repository path and that's about it. Are you able to provide some commands to do those things by any chance?

**Comment by lshqqytiger** [comment]
Pull and try again. I think this issue is solved now.
