### ISSUE TITLE
[Bug]: Inpainting "Only Masked" using VRAM as if "Whole picture"?

### ISSUE THREAD

**Issue by mr-september** [lshqqytiger/stable-diffusion-webui-directml#161]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

In an older version, before the UI changed to add "resize by" and "resize to", I used to be able to mask a tiny part (maybe around 128x128) of a huge image, and if I just left the "resize by" to 512, select "Only masked" it would generate high quality, detailed inpaints without any issues.

Since some updates, this is no longer possible. Inpainting large images, even of tiny masked areas and selecting "Only masked" always throws VRAM errors. The only fix is to slide the "Resize by" down until roughly it's in the range of 512x512, and the resulting inpainted area would look very blurry. The speed has also become much slower.

### Steps to reproduce the problem

Use inpainting with any large image (>768x768 for me).

### What should have happened?

Retain old settings of leaving the masked area at 512x512, and quickly get high-detailed output.

### Commit where the problem happens

ba780a8e4fb27d1eb9595947380a63bd84fc419e

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 5000 below)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--opt-sub-quad-attention --medvram --disable-nan-check --autolaunch --api --cors-allow-origins=http://127.0.0.1:3456 --no-half
```

### List of extensions

-

### Console logs

```Shell
Traceback (most recent call last):
  File "E:\stable-diffusion-webui-directml\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "E:\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "E:\stable-diffusion-webui-directml\modules\img2img.py", line 178, in img2img
    processed = process_images(p)
  File "E:\stable-diffusion-webui-directml\modules\processing.py", line 613, in process_images
    res = process_images_inner(p)
  File "E:\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "E:\stable-diffusion-webui-directml\modules\processing.py", line 733, in process_images_inner
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "E:\stable-diffusion-webui-directml\modules\processing.py", line 733, in <listcomp>
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "E:\stable-diffusion-webui-directml\modules\processing.py", line 518, in decode_first_stage
    x = model.decode_first_stage(x)
  File "E:\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "E:\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 826, in decode_first_stage
    return self.first_stage_model.decode(z)
  File "E:\stable-diffusion-webui-directml\modules\lowvram.py", line 52, in first_stage_model_decode_wrap
    return first_stage_model_decode(z)
  File "E:\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 90, in decode
    dec = self.decoder(z)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 637, in forward
    h = self.up[i_level].block[i_block](h, temb)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 132, in forward
    h = nonlinearity(h)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\functional.py", line 2059, in silu
    return torch._C._nn.silu(input)
RuntimeError: Could not allocate tensor with 1006632960 bytes. There is not enough GPU video memory available!
```
```


### Additional information

_No response_

**Comment by mr-september** [comment]
I noticed, the preview window is cropped down to the "resize to" dimensions, same as old versions. However, when it's near completion, it will throw a VRAM error out. I think the bug may be occurring where the newly inpainted sub-image is being stitched back with the rest of the input image.

**Comment by mr-september** [comment]
This is also affecting [Ultimate Upscale](https://github.com/Coyote-A/ultimate-upscale-for-automatic1111). Identical settings/size as before, now throws VRAM errors late into the process. I suspect it may be a problem with the stitching process.
