### ISSUE TITLE
[Bug]: error keeps showing up again

### ISSUE THREAD

**Issue by Spas120** [lshqqytiger/stable-diffusion-webui-directml#162]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

the error "RuntimeError: 'devices' argument must be DML" keeps popping up

### Steps to reproduce the problem

just clicking generate

### What should have happened?

normal generation

### Commit where the problem happens

idk

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 6000 above)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--opt-sub-quad-attention --medvram --autolaunch --no-half
```

### List of extensions

image browser

### Console logs

```Shell
Error completing request
Arguments: ('task(ig4pub126k6nk3q)', 'pikachu', 'low resolution', [], 25, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 544, 544, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0) {}
Traceback (most recent call last):
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\txt2img.py", line 94, in txt2img
    processed = processing.process_images(p)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\processing.py", line 613, in process_images
    res = process_images_inner(p)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\processing.py", line 721, in process_images_inner
    p.setup_conds()
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\processing.py", line 1099, in setup_conds
    super().setup_conds()
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\processing.py", line 337, in setup_conds
    self.uc = self.get_conds_with_caching(prompt_parser.get_learned_conditioning, self.negative_prompts, self.steps * self.step_multiplier, self.cached_uc)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\processing.py", line 328, in get_conds_with_caching
    cache[1] = function(shared.sd_model, required_prompts, steps)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\prompt_parser.py", line 143, in get_learned_conditioning
    conds = model.get_learned_conditioning(texts)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 669, in get_learned_conditioning
    c = self.cond_stage_model(c)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\sd_hijack_clip.py", line 229, in forward
    z = self.process_tokens(tokens, multipliers)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\sd_hijack_clip.py", line 254, in process_tokens
    z = self.encode_with_transformers(tokens)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\sd_hijack_clip.py", line 302, in encode_with_transformers
    outputs = self.wrapped.transformer(input_ids=tokens, output_hidden_states=-opts.CLIP_stop_at_last_layers)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 811, in forward
    return self.text_model(
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 708, in forward
    hidden_states = self.embeddings(input_ids=input_ids, position_ids=position_ids)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\models\clip\modeling_clip.py", line 223, in forward
    inputs_embeds = self.token_embedding(input_ids)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\modules\sd_hijack.py", line 255, in forward
    inputs_embeds = self.wrapped(input_ids)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\sparse.py", line 162, in forward
    return F.embedding(
  File "C:\Users\user\Desktop\stable\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: 'devices' argument must be DML
```

**Comment by lshqqytiger** [comment]
I can't reproduce. It generates image without any error for me.

**Comment by Spas120** [comment]
> I can't reproduce. It generates image without any error for me.

then why does it happen for me? all i wantd to do is make it slower so i can generate bigger images without it crashing

**Comment by lshqqytiger** [comment]
I think this would be the same as `Out of memory` but I can't find another issue and it doesn't happen to me so I'm not sure.

**Comment by Spas120** [comment]
> I think this would be the same as `Out of memory` but I can't find another issue and it doesn't happen to me so I'm not sure.

is there anyway to at least slow down the generation process so it can generate bigger images

**Comment by lshqqytiger** [comment]
`--lowvram` instead of `--medvram`. It will much more harshly suppress vram usage than `--medvram`.

**Comment by Spas120** [comment]
> `--lowvram` instead of `--medvram`. It will much more harshly suppress vram usage than `--medvram`. It is not recommended if you have 8GB of vram or more.

well i tried that but it just made my screen go out and it even did that with medvram

**Comment by lshqqytiger** [comment]
Could you tell me what gpu(s) you are using?

**Comment by Spas120** [comment]
> Could you tell me what gpu(s) you are using? AMD GPUs (RX 6000 series) is less helpful and DirectML can use another gpu if you have.

Well my actual gpu is RX 580 series actually to be honest i only chose RX 6000 because i didn't see a option for my gpu

**Comment by lshqqytiger** [comment]
Did you check whether RX 580 is working properly? (vram usage & utilization in task manager)
RX 580 has 8GB of vram and it is generally thought that `--lowvram` is too much limitation for that gpu.

**Comment by Spas120** [comment]
> Did you check whether RX 580 is working properly? (vram usage & utilization in task manager) RX 580 has 8GB of vram and it is generally thought that `--lowvram` is too much limitation for that gpu.

My gpu seems to be working fine but whenever i try generating something it does take 100% of the gpu just to generate one image

**Comment by lshqqytiger** [comment]
Have you tried updating graphics driver or removing `venv`?

**Comment by Spas120** [comment]
> Have you tried updating graphics driver or removing `venv`?

i tried updating it but it just said the best driver is already installed and what's venv?

**Comment by lshqqytiger** [comment]
`stable-diffusion-webui-directml/venv` is the folder you might have. You can reset virtual environment by removing it.

**Comment by Spas120** [comment]
> `stable-diffusion-webui-directml/venv` is the folder you might have. You can reset virtual environment by removing it.

how can that fix the problem?

**Comment by lshqqytiger** [comment]
This kind of issue is very rare. The way to fix this problem is unknown. Although we can't do many things about DirectML itself, we can try basic solutions like reinstalling packages.

**Comment by Spas120** [comment]
> This kind of issue is very rare. The way to fix this problem is unknown. Although we can't do many things about DirectML itself, we can try basic solutions like reinstalling packages.

well i reinstalled stable diffusion many times before in general and it still does the problem and deleting venv didnt change anything

**Comment by lshqqytiger** [comment]
Then we have no more options left except for reinstalling gpu driver or Windows. DirectML depends on them.

**Comment by Spas120** [comment]
> Then we have no more options left except for reinstalling gpu driver or Windows. DirectML depends on them.

is directml an app or something? cause if it is then i don't have it installed

**Comment by lshqqytiger** [comment]
DirectML is a DirectX 12 library for machine learning. That means DirectML strongly depends on DirectX and Windows. DirectML (`torch-directml`) is automatically installed while the first startup of webui.

**Comment by Spas120** [comment]
> DirectML is a DirectX 12 library for machine learning. That means DirectML strongly depends on DirectX and Windows. DirectML (`torch-directml`) is automatically installed while the first startup of webui.

is directx installed during the startup or do i need to install it manually?

**Comment by lshqqytiger** [comment]
DirectX is embedded in Windows. You cannot install it manually.

**Comment by Spas120** [comment]
> DirectX is embedded in Windows. You cannot install it manua

**Comment by Spas120** [comment]
> DirectX is embedded in Windows. You cannot install it manually.

I accidently closed the issue but i still dont know how to solve the screen going out problem

**Comment by Spas120** [comment]
> DirectX is embedded in Windows. You cannot install it manually.

idk how to fix the screen going out then

**Comment by lshqqytiger** [comment]
The phenomenon that the screen goes out is mostly due to unstable power supply. Undervolt or underclock your gpu.

**Comment by Spas120** [comment]
> The phenomenon that the screen goes out is mostly due to unstable power supply. Undervolt or underclock your gpu.

well the screen goes out but everything else still plays like you can hear everything from the pc before the screen went out

**Comment by lshqqytiger** [comment]
That is a typical symptom of a graphics card power failure. For more information, you should check the system log like Windows event viewer.

**Comment by Spas120** [comment]
> That is a typical symptom of a graphics card power failure. In order to reveal actual cause, you should check the system log like Windows event viewer.

how do i get to the system logs?

**Comment by lshqqytiger** [comment]
Using `Reliability Monitor` or `Event Viewer`.

**Comment by Spas120** [comment]
> Using `Reliability Monitor` (from Microsoft Management Console) or `Event Viewer` (from Control Panel).

well i got it open but where should i look to find what i'm looking for?

**Comment by lshqqytiger** [comment]
Find `Error` and `Warning` which is seemed to be related to this issue.

**Comment by Spas120** [comment]
> Find `Error` and `Warning` which is seemed to be related to this issue.

so how can i tell which one is the screen going out problem?

**Comment by lshqqytiger** [comment]
Reproduce that problem and find the error/warning message describing about power issue right after rebooting.

**Comment by Spas120** [comment]
> Reproduce that problem and find the error/warning message describing about power issue right after rebooting.

well the problem happens randomly and do i look through the custom views folder for the errors or the windows log folder or the applications and services logs folder?

**Comment by lshqqytiger** [comment]
Every item of Reliability Monitor and Event Viewer has its message and a date when it happened. I think you can find something (describing power shortage or driver crash or another?) by them.

**Comment by Spas120** [comment]
> Every item of Reliability Monitor and Event Viewer has its message and a date when it happened. I think you can find something (describing power shortage or driver crash or another?) by them.

what would the error say?

**Comment by songib** [comment]
did you find the fix?

**Comment by Disflippant** [comment]
I was running into the error _RuntimeError: 'devices' argument must be DML_ with a RX 6600 XT . An update of my graphics driver solved it for me.
