### ISSUE TITLE
[Bug]: DML allocator out of memory!

### ISSUE THREAD

**Issue by Milor123** [lshqqytiger/stable-diffusion-webui-directml#174]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

My stable difusion suddenly stopped working

### Steps to reproduce the problem

Today i get this fail, i dont understand that happend.
Now try do a clean install doing a new git clone and install python 3.10.6 (yesteday it works very nice in 3.10.11) with conda

My conda 3.10.6 is working as base.

### What should have happened?

Run as well

### Commit where the problem happens

I am not sure because it stop working, and then try do git pull and not solve, then try clean install

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 6000 above)

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
In old:
set PYTHON=
set GIT=
set VENV_DIR=
set PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.9,max_split_size_mb:512
set COMMANDLINE_ARGS=--medvram --precision full --no-half --no-half-vae --opt-split-attention --disable-nan-check --autolaunch --api --backend=directml
set SAFETENSORS_FAST_GPU=1
call webui.bat

Now:
Nothing and neither works
```

### List of extensions

Nothing

### Console logs

```Shell
Creating venv in directory C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\venv using python "C:\Users\NoeXVanitasXJunk\miniconda3\python.exe"
venv "C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 | packaged by conda-forge | (main, Oct 24 2022, 16:02:16) [MSC v.1916 64 bit (AMD64)]
Version: <none>
Commit hash: 4f46f9bd54e0ce25a50fa3c04b82e9bf74b97c66
Installing torch and torchvision
Collecting torch==2.0.0
  Using cached torch-2.0.0-cp310-cp310-win_amd64.whl (172.3 MB)
Collecting torchvision==0.15.1
  Using cached torchvision-0.15.1-cp310-cp310-win_amd64.whl (1.2 MB)
Collecting torch-directml
  Using cached torch_directml-0.2.0.dev230426-cp310-cp310-win_amd64.whl (8.2 MB)
Collecting networkx
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting jinja2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting filelock
  Using cached filelock-3.12.2-py3-none-any.whl (10 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.6.3-py3-none-any.whl (31 kB)
Collecting sympy
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting numpy
  Using cached numpy-1.25.0-cp310-cp310-win_amd64.whl (15.0 MB)
Collecting pillow!=8.3.*,>=5.3.0
  Using cached Pillow-9.5.0-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting requests
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.3-cp310-cp310-win_amd64.whl (17 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2023.5.7-py3-none-any.whl (156 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.1.0-cp310-cp310-win_amd64.whl (97 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.0.3-py3-none-any.whl (123 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting mpmath>=0.19
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, numpy, networkx, MarkupSafe, idna, filelock, charset-normalizer, certifi, requests, jinja2, torch, torchvision, torch-directml
Successfully installed MarkupSafe-2.1.3 certifi-2023.5.7 charset-normalizer-3.1.0 filelock-3.12.2 idna-3.4 jinja2-3.1.2 mpmath-1.3.0 networkx-3.1 numpy-1.25.0 pillow-9.5.0 requests-2.31.0 sympy-1.12 torch-2.0.0 torch-directml-0.2.0.dev230426 torchvision-0.15.1 typing-extensions-4.6.3 urllib3-2.0.3

[notice] A new release of pip available: 22.2.1 -> 23.1.2
[notice] To update, run: C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\venv\Scripts\python.exe -m pip install --upgrade pip
Installing gfpgan
Installing clip
Installing open_clip
Cloning Stable Diffusion into C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai...
Cloning Taming Transformers into C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\repositories\taming-transformers...
Cloning K-diffusion into C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\repositories\k-diffusion...
Cloning CodeFormer into C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\repositories\CodeFormer...
Cloning BLIP into C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\repositories\BLIP...
Installing requirements for CodeFormer
Installing requirements
Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
Downloading: "https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors" to C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors

100%|█████████████████████████████████████████████████████████████████████████████| 3.97G/3.97G [03:47<00:00, 18.7MB/s]
Calculating sha256 for C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors: Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 243.5s (import torch: 1.7s, import gradio: 1.7s, import ldm: 0.5s, other imports: 1.3s, setup codeformer: 0.1s, list SD models: 236.0s, load scripts: 1.4s, create ui: 0.7s, gradio launch: 0.2s).
6ce0161689b3853acaa03779ec93eafe75a02f4ced659bee03f50797806fa2fa
Loading weights [6ce0161689] from C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Downloading (…)olve/main/vocab.json: 961kB [00:00, 14.8MB/s]
Downloading (…)olve/main/merges.txt: 525kB [00:00, 13.0MB/s]
Downloading (…)cial_tokens_map.json: 100%|████████████████████████████████████████████████████| 389/389 [00:00<?, ?B/s]
Downloading (…)okenizer_config.json: 100%|████████████████████████████████████████████████████| 905/905 [00:00<?, ?B/s]
Downloading (…)lve/main/config.json: 4.52kB [00:00, ?B/s]
Applying optimization: InvokeAI... done.
Textual inversion embeddings loaded(0):
Model loaded in 21.7s (calculate hash: 13.4s, load weights from disk: 0.3s, create model: 2.1s, apply weights to model: 1.4s, apply half(): 1.3s, load VAE: 0.4s, move model to device: 2.7s).
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:38<00:00,  1.93s/it]
[W D:\a\_work\1\s\pytorch-directml-plugin\torch_directml\csrc\engine\dml_heap_allocator.cc:120] DML allocator out of memory!
Error completing request
Arguments: ('task(l2005mjtzkkxdor)', '', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0) {}
Traceback (most recent call last):
  File "C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\modules\txt2img.py", line 94, in txt2img
    processed = processing.process_images(p)
  File "C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\modules\processing.py", line 613, in process_images
    res = process_images_inner(p)
  File "C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\modules\processing.py", line 733, in process_images_inner
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\modules\processing.py", line 733, in <listcomp>
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 1572864 bytes.

Fatal read error on socket transport
protocol: <anyio._backends._asyncio.StreamProtocol object at 0x00000151B7D8C400>
transport: <_SelectorSocketTransport fd=6048 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "C:\Users\NoeXVanitasXJunk\miniconda3\lib\asyncio\selector_events.py", line 854, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
MemoryError
Error completing request
Arguments: ('task(nqodejhus8wt6c4)', '', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0) {}
Traceback (most recent call last):
  File "C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\modules\txt2img.py", line 94, in txt2img
    processed = processing.process_images(p)
  File "C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\modules\processing.py", line 613, in process_images
    res = process_images_inner(p)
  File "C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\modules\processing.py", line 721, in process_images_inner
    p.setup_conds()
  File "C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\modules\processing.py", line 1099, in setup_conds
    super().setup_conds()
  File "C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\modules\processing.py", line 337, in setup_conds
    self.uc = self.get_conds_with_caching(prompt_parser.get_learned_conditioning, self.negative_prompts, self.steps * self.step_multiplier, self.cached_uc)
  File "C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\modules\processing.py", line 328, in get_conds_with_caching
    cache[1] = function(shared.sd_model, required_prompts, steps)
  File "C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\modules\prompt_parser.py", line 143, in get_learned_conditioning
    conds = model.get_learned_conditioning(texts)
  File "C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 669, in get_learned_conditioning
    c = self.cond_stage_model(c)
  File "C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\modules\sd_hijack_clip.py", line 229, in forward
    z = self.process_tokens(tokens, multipliers)
  File "C:\Users\NoeXVanitasXJunk\stable-diffusion-webui-directml\modules\sd_hijack_clip.py", line 246, in process_tokens
    tokens = torch.asarray(remade_batch_tokens).to(devices.device)
RuntimeError
```

### Additional information

The only weird thing I've done today is to change the pagesfile.sys of my windows, from 27 gb (it was in automatic mode), so I set it to use a maximum of 8gb.

I have 24 GB of RAM
and my card rx6750 xt 14VRAM

but even this morning my stable diffusion was working perfectly, I don't understand what happened. My windows didn't update today

I have windows 11 22H2

**Comment by Milor123** [comment]
Its windows bug by the page, I've set it in automatic mode and solve the problem
![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/14153649/46a6fe6c-c090-40de-80e0-57d7faf67f5c)
