### ISSUE TITLE
[Bug]: OSError: libd3d12.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Kyr4l** [lshqqytiger/stable-diffusion-webui-directml#176]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

can't start the program

### Steps to reproduce the problem

clone the repo
create a python310 venv
install deps
try to  run the program

### What should have happened?

should've launched

### Commit where the problem happens

06296ff0011523f49022dee0e4b0476a8497c473

### What Python version are you running on ?

3.10
### What platforms do you use to access the UI ?

Linux

### What device are you running WebUI on?

AMD GPUs (RX 6000 above)

### What browsers do you use to access the UI ?

Firefox

### Command Line Arguments

```Shell
cd stable-diffusion-webui-directlml && source venv/bin/activate && TORCH_COMMAND='pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/rocm5.1.1' python launch.py --precision full --no-half
```

### List of extensions

no

### Console logs

```Shell
(venv) 18:11:22 (kyral@kdes)-[/mnt/hdd-datastore0/repositories/github/cloned/stable-diffusion-webui/stable-diffusion-webui-directml] 
(0)-$ TORCH_COMMAND='pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/rocm5.1.1' python launch.py --precision full --no-half
fatal: No names found, cannot describe anything.
Python 3.10.11 (main, Apr 27 2023, 21:52:36) [GCC]
Version: <none>
Commit hash: 06296ff0011523f49022dee0e4b0476a8497c473
Installing requirements
Launching Web UI with arguments: --precision full --no-half
No module 'xformers'. Proceeding without it.
Traceback (most recent call last):
  File "/mnt/hdd-datastore0/repositories/github/cloned/stable-diffusion-webui/stable-diffusion-webui-directml/launch.py", line 38, in <module>
    main()
  File "/mnt/hdd-datastore0/repositories/github/cloned/stable-diffusion-webui/stable-diffusion-webui-directml/launch.py", line 34, in main
    start()
  File "/mnt/hdd-datastore0/repositories/github/cloned/stable-diffusion-webui/stable-diffusion-webui-directml/modules/launch_utils.py", line 351, in start
    import webui
  File "/mnt/hdd-datastore0/repositories/github/cloned/stable-diffusion-webui/stable-diffusion-webui-directml/webui.py", line 42, in <module>
    from modules.call_queue import wrap_gradio_gpu_call, wrap_queued_call, queue_lock  # noqa: F401
  File "/mnt/hdd-datastore0/repositories/github/cloned/stable-diffusion-webui/stable-diffusion-webui-directml/modules/call_queue.py", line 7, in <module>
    from modules import shared, progress
  File "/mnt/hdd-datastore0/repositories/github/cloned/stable-diffusion-webui/stable-diffusion-webui-directml/modules/shared.py", line 78, in <module>
    devices.device, devices.device_interrogate, devices.device_gfpgan, devices.device_esrgan, devices.device_codeformer = \
  File "/mnt/hdd-datastore0/repositories/github/cloned/stable-diffusion-webui/stable-diffusion-webui-directml/modules/shared.py", line 79, in <genexpr>
    (devices.cpu if any(y in cmd_opts.use_cpu for y in [x, 'all']) else devices.get_optimal_device() for x in ['sd', 'interrogate', 'gfpgan', 'esrgan', 'codeformer'])
  File "/mnt/hdd-datastore0/repositories/github/cloned/stable-diffusion-webui/stable-diffusion-webui-directml/modules/devices.py", line 62, in get_optimal_device
    return torch.device(get_optimal_device_name())
  File "/mnt/hdd-datastore0/repositories/github/cloned/stable-diffusion-webui/stable-diffusion-webui-directml/modules/devices.py", line 54, in get_optimal_device_name
    import torch_directml
  File "/mnt/hdd-datastore0/repositories/github/cloned/stable-diffusion-webui/stable-diffusion-webui-directml/venv/lib64/python3.10/site-packages/torch_directml/__init__.py", line 13, in <module>
    torch.ops.load_library(directml_dll)
  File "/mnt/hdd-datastore0/repositories/github/cloned/stable-diffusion-webui/stable-diffusion-webui-directml/venv/lib64/python3.10/site-packages/torch/_ops.py", line 643, in load_library
    ctypes.CDLL(path)
  File "/usr/lib64/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libd3d12.so: cannot open shared object file: No such file or directory
```

### Additional information

OS : OpenSUSE Tumbleweed
GPU : RX 6700XT

**Comment by Kyr4l** [comment]
solved by running `opip install -r requirements.txt`

**Comment by Kyr4l** [comment]
my bad, still the same error  :
```
(venv) 18:38:53 (kyral@kdes)-[/mnt/hdd-datastore0/repositories/github/cloned/stable-diffusion-webui/stable-diffusion-webui-directml] 
(0)-$ TORCH_COMMAND='pip install torch torchvision --extra-index-url https://download.pytorch.org/whl/rocm5.1.1' python launch.py --precision full --no-half
fatal: No names found, cannot describe anything.
Python 3.10.11 (main, Apr 27 2023, 21:52:36) [GCC]
Version: <none>
Commit hash: 06296ff0011523f49022dee0e4b0476a8497c473
Installing requirements
Launching Web UI with arguments: --precision full --no-half
No module 'xformers'. Proceeding without it.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /mnt/hdd-datastore0/repositories/github/cloned/stable-diffusion-webui/stable-diffusion-webui-dir │
│ ectml/launch.py:38 in <module>                                                                   │
│                                                                                                  │
│   35                                                                                             │
│   36                                                                                             │
│   37 if __name__ == "__main__":                                                                  │
│ ❱ 38 │   main()                                                                                  │
│   39                                                                                             │
│                                                                                                  │
│ /mnt/hdd-datastore0/repositories/github/cloned/stable-diffusion-webui/stable-diffusion-webui-dir │
│ ectml/launch.py:34 in main                                                                       │
│                                                                                                  │
│   31 │   if args.test_server:                                                                    │
│   32 │   │   configure_for_tests()                                                               │
│   33 │                                                                                           │
│ ❱ 34 │   start()                                                                                 │
│   35                                                                                             │
│   36                                                                                             │
│   37 if __name__ == "__main__":                                                                  │
│                                                                                                  │
│ /mnt/hdd-datastore0/repositories/github/cloned/stable-diffusion-webui/stable-diffusion-webui-dir │
│ ectml/modules/launch_utils.py:351 in start                                                       │
│                                                                                                  │
│   348                                                                                            │
│   349 def start():                                                                               │
│   350 │   print(f"Launching {'API server' if '--nowebui' in sys.argv else 'Web UI'} with argum   │
│ ❱ 351 │   import webui                                                                           │
│   352 │   if '--nowebui' in sys.argv:                                                            │
│   353 │   │   webui.api_only()                                                                   │
│   354 │   else:                                                                                  │
│                                                                                                  │
│ /mnt/hdd-datastore0/repositories/github/cloned/stable-diffusion-webui/stable-diffusion-webui-dir │
│ ectml/webui.py:42 in <module>                                                                    │
│                                                                                                  │
│    39 startup_timer.record("import ldm")                                                         │
│    40                                                                                            │
│    41 from modules import extra_networks                                                         │
│ ❱  42 from modules.call_queue import wrap_gradio_gpu_call, wrap_queued_call, queue_lock  # noq   │
│    43                                                                                            │
│    44 # Truncate version number of nightly/local build of PyTorch to not cause exceptions with   │
│    45 if ".dev" in torch.__version__ or "+git" in torch.__version__:                             │
│                                                                                                  │
│ /mnt/hdd-datastore0/repositories/github/cloned/stable-diffusion-webui/stable-diffusion-webui-dir │
│ ectml/modules/call_queue.py:7 in <module>                                                        │
│                                                                                                  │
│     4 import traceback                                                                           │
│     5 import time                                                                                │
│     6                                                                                            │
│ ❱   7 from modules import shared, progress                                                       │
│     8                                                                                            │
│     9 queue_lock = threading.Lock()                                                              │
│    10                                                                                            │
│                                                                                                  │
│ /mnt/hdd-datastore0/repositories/github/cloned/stable-diffusion-webui/stable-diffusion-webui-dir │
│ ectml/modules/shared.py:78 in <module>                                                           │
│                                                                                                  │
│    75 cmd_opts.disable_extension_access = (cmd_opts.share or cmd_opts.listen or cmd_opts.serve   │
│    76                                                                                            │
│    77                                                                                            │
│ ❱  78 devices.device, devices.device_interrogate, devices.device_gfpgan, devices.device_esrgan   │
│    79 │   (devices.cpu if any(y in cmd_opts.use_cpu for y in [x, 'all']) else devices.get_opti   │
│    80                                                                                            │
│    81 devices.dtype = torch.float32 if cmd_opts.no_half else torch.float16                       │
│                                                                                                  │
│ /mnt/hdd-datastore0/repositories/github/cloned/stable-diffusion-webui/stable-diffusion-webui-dir │
│ ectml/modules/shared.py:79 in <genexpr>                                                          │
│                                                                                                  │
│    76                                                                                            │
│    77                                                                                            │
│    78 devices.device, devices.device_interrogate, devices.device_gfpgan, devices.device_esrgan   │
│ ❱  79 │   (devices.cpu if any(y in cmd_opts.use_cpu for y in [x, 'all']) else devices.get_opti   │
│    80                                                                                            │
│    81 devices.dtype = torch.float32 if cmd_opts.no_half else torch.float16                       │
│    82 devices.dtype_vae = torch.float32 if cmd_opts.no_half or cmd_opts.no_half_vae else torch   │
│                                                                                                  │
│ /mnt/hdd-datastore0/repositories/github/cloned/stable-diffusion-webui/stable-diffusion-webui-dir │
│ ectml/modules/devices.py:62 in get_optimal_device                                                │
│                                                                                                  │
│    59                                                                                            │
│    60                                                                                            │
│    61 def get_optimal_device():                                                                  │
│ ❱  62 │   return torch.device(get_optimal_device_name())                                         │
│    63                                                                                            │
│    64                                                                                            │
│    65 def get_device_for(task):                                                                  │
│                                                                                                  │
│ /mnt/hdd-datastore0/repositories/github/cloned/stable-diffusion-webui/stable-diffusion-webui-dir │
│ ectml/modules/devices.py:54 in get_optimal_device_name                                           │
│                                                                                                  │
│    51 │                                                                                          │
│    52 │   from modules import shared                                                             │
│    53 │   if shared.cmd_opts.backend == 'directml':                                              │
│ ❱  54 │   │   import torch_directml                                                              │
│    55 │   │   if torch_directml.is_available():                                                  │
│    56 │   │   │   return get_dml_device_string()                                                 │
│    57                                                                                            │
│                                                                                                  │
│ /mnt/hdd-datastore0/repositories/github/cloned/stable-diffusion-webui/stable-diffusion-webui-dir │
│ ectml/venv/lib64/python3.10/site-packages/torch_directml/__init__.py:13 in <module>              │
│                                                                                                  │
│   10 │   directml_dll = os.path.join(os.path.dirname(__file__), 'DirectML.dll')                  │
│   11 else:                                                                                       │
│   12 │   directml_dll = os.path.join(os.path.dirname(__file__), 'libdirectml.so')                │
│ ❱ 13 torch.ops.load_library(directml_dll)                                                        │
│   14                                                                                             │
│   15 # import native apis                                                                        │
│   16 import torch_directml_native                                                                │
│                                                                                                  │
│ /mnt/hdd-datastore0/repositories/github/cloned/stable-diffusion-webui/stable-diffusion-webui-dir │
│ ectml/venv/lib64/python3.10/site-packages/torch/_ops.py:643 in load_library                      │
│                                                                                                  │
│   640 │   │   │   # Import the shared library into the process, thus running its                 │
│   641 │   │   │   # static (global) initialization code in order to register custom              │
│   642 │   │   │   # operators with the JIT.                                                      │
│ ❱ 643 │   │   │   ctypes.CDLL(path)                                                              │
│   644 │   │   self.loaded_libraries.add(path)                                                    │
│   645                                                                                            │
│   646                                                                                            │
│                                                                                                  │
│ /usr/lib64/python3.10/ctypes/__init__.py:374 in __init__                                         │
│                                                                                                  │
│   371 │   │   self._FuncPtr = _FuncPtr                                                           │
│   372 │   │                                                                                      │
│   373 │   │   if handle is None:                                                                 │
│ ❱ 374 │   │   │   self._handle = _dlopen(self._name, mode)                                       │
│   375 │   │   else:                                                                              │
│   376 │   │   │   self._handle = handle                                                          │
│   377                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
OSError: libd3d12.so: cannot open shared object file: No such file or directory

```

**Comment by lshqqytiger** [comment]
DirectML requires DirectX runtime and most of Linux systems don't have it.

**Comment by Kyr4l** [comment]
so there's no way to run this on my system i guess

**Comment by lshqqytiger** [comment]
I don't know Microsoft has a plan to support DirectML on other Linux systems, currently it works on Windows and WSL.

**Comment by genassistdigital** [comment]
hi @lshqqytiger do you have an instructions how to use olive after it has been installed? i seem cant understand the instructions with only images, in the about page. Thank you!

**Comment by lshqqytiger** [comment]
You can find the instruction in #149.
