### ISSUE TITLE
[Bug]: Couldn't install torch

### ISSUE THREAD

**Issue by Bigwaterme1on** [lshqqytiger/stable-diffusion-webui-directml#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

after installed git and python,run webui-user.bat  it stucks in installing torch

### Steps to reproduce the problem

open webui-user.bat

### What should have happened?

torch should be installed properly

### Version or Commit where the problem happens

latest

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 6000 above), Other GPUs

### Cross attention optimization

Automatic

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
no
```

### List of extensions

no

### Console logs

```Shell
venv "D:\Stable diffusion-amd\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: ## 1.4.0
Commit hash: 265d626471eacd617321bdb51e50e4b87a7ca82e
Installing torch and torchvision
Collecting torch==2.0.0
  Downloading torch-2.0.0-cp310-cp310-win_amd64.whl (172.3 MB)
     ----- ---------------------------------- 23.7/172.3 MB 3.8 MB/s eta 0:00:39
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    torch==2.0.0 from https://files.pythonhosted.org/packages/87/e2/62dbdfc85d3b8f771bc4b1a979ee6a157dbaa8928981dabbf45afc6d13dc/torch-2.0.0-cp310-cp310-win_amd64.whl:
        Expected sha256 527f4ae68df7b8301ee6b1158ca56350282ea633686537b30dbb5d7b4a52622a
             Got        2b9f593cfe39eb1ea5681aa8c8460893df5aa40dc8a72bcd7e9839333fe8fa20

Traceback (most recent call last):
  File "D:\Stable diffusion-amd\stable-diffusion-webui-directml\launch.py", line 38, in <module>
    main()
  File "D:\Stable diffusion-amd\stable-diffusion-webui-directml\launch.py", line 29, in main
    prepare_environment()
  File "D:\Stable diffusion-amd\stable-diffusion-webui-directml\modules\launch_utils.py", line 285, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "D:\Stable diffusion-amd\stable-diffusion-webui-directml\modules\launch_utils.py", line 108, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install torch.
Command: "D:\Stable diffusion-amd\stable-diffusion-webui-directml\venv\Scripts\python.exe" -m pip install torch==2.0.0 torchvision==0.15.1 torch-directml
Error code: 1
```

**Comment by Bigwaterme1on** [comment]
problem fixed , try urn off VPN proxy when run webui-user.bat
