### ISSUE TITLE
[Bug] with extension sd-webui-xldemo-txt2img

### ISSUE THREAD

**Issue by StudioDUzes** [lshqqytiger/stable-diffusion-webui-directml#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

gradio.exceptions.Error: 'Error: Torch not compiled with CUDA enabled'

### Steps to reproduce the problem

1. Go to SDXL demo
2. Press GENERATE
3. ...

### What should have happened?

Should work with DirectML...

### Version or Commit where the problem happens

Version: ## 1.4.1

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

Other GPUs

### Cross attention optimization

Automatic

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --medvram --precision full --no-half --no-half-vae --opt-sub-quad-attention --opt-split-attention-v1 --disable-nan-check

git pull

call webui.bat
```

### List of extensions

[extensions.pdf](https://github.com/lshqqytiger/stable-diffusion-webui-directml/files/12080305/extensions.pdf)

### Console logs

```Shell
Already up to date.
venv "N:\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: ## 1.4.1
Commit hash: aa02899d39c3f0261db4b4b70b9ce262e61fe440
Installing requirements

Fetching updates for midas...
Checking out commit for midas with hash: 1645b7e...

current transparent-background 1.2.4

Installing requirements 1 for Infinite-Zoom




Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72

Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72

Installing sd-webui-xl-demo requirements_webui.txt

Installing imageio-ffmpeg requirement for depthmap script
Installing pyqt5 requirement for depthmap script

Installing requirements for TemporalKit extension

Launching Web UI with arguments: --medvram --precision full --no-half --no-half-vae --opt-sub-quad-attention --opt-split-attention-v1 --disable-nan-check
No module 'xformers'. Proceeding without it.
Warning: caught exception '', memory monitor disabled
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: N:\stable-diffusion-webui-directml\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
2023-07-18 14:08:40,563 - ControlNet - INFO - ControlNet v1.1.232
ControlNet preprocessor location: N:\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\downloads
2023-07-18 14:08:40,699 - ControlNet - INFO - ControlNet v1.1.232
2023-07-18 14:08:41,145 - roop - INFO - roop v0.0.2
2023-07-18 14:08:41,146 - roop - INFO - roop v0.0.2
2023-07-18 14:08:41,149 - roop - INFO - roop v0.0.2
Using SDXL 0.9
Loading model stabilityai/stable-diffusion-xl-base-0.9
text_encoder_2\model.safetensors not found
Loading model stabilityai/stable-diffusion-xl-refiner-0.9
vae\diffusion_pytorch_model.safetensors not found
Loading weights [ab0de91e50] from N:\stable-diffusion-webui-directml\models\Stable-diffusion\Realistic sd15\Realistic_Vision\Realistic_Vision_V4.0.safetensors
Creating model from config: N:\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
*Deforum ControlNet support: enabled*
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
[AgentScheduler] Runner is paused
[AgentScheduler] Registering APIs
Startup time: 47.2s (import torch: 2.2s, import gradio: 1.5s, import ldm: 0.5s, other imports: 1.8s, opts onchange: 0.3s, list SD models: 0.1s, load scripts: 38.0s, create ui: 1.8s, gradio launch: 0.2s, app_started_callback: 0.5s).
preload_extensions_git_metadata for 26 extensions took 2.10s
Loading VAE weights specified in settings: N:\stable-diffusion-webui-directml\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: sub-quadratic... done.
Textual inversion embeddings loaded(6): bad_prompt_version2-neg, kkw-bp, kkw-Demons, kkw-micro, ng_deepnegative_v1_75t, rmadanegative4_sd15-neg
Model loaded in 13.9s (load weights from disk: 1.3s, create model: 1.2s, apply weights to model: 9.5s, load VAE: 1.0s, calculate empty prompt: 0.8s).
Traceback (most recent call last):
  File "N:\stable-diffusion-webui-directml\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img.py", line 307, in do_xldemo_txt2img_infer
    return xldemo_txt2img.infer(prompt, negative, width, height, scale, seed, batch_count, batch_size, sampler, steps)
  File "N:\stable-diffusion-webui-directml\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img.py", line 229, in infer
    images = self.pipe(prompt=prompt, width=width, height=height, negative_prompt=negative, guidance_scale=cfg_scale,
  File "N:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "N:\stable-diffusion-webui-directml\venv\lib\site-packages\diffusers\pipelines\stable_diffusion_xl\pipeline_stable_diffusion_xl.py", line 698, in __call__
    ) = self.encode_prompt(
  File "N:\stable-diffusion-webui-directml\venv\lib\site-packages\diffusers\pipelines\stable_diffusion_xl\pipeline_stable_diffusion_xl.py", line 335, in encode_prompt
    text_input_ids.to(device),
  File "N:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "N:\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "N:\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "N:\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "N:\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "N:\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "N:\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "N:\stable-diffusion-webui-directml\extensions\sd-webui-xldemo-txt2img\xldemo_txt2img.py", line 310, in do_xldemo_txt2img_infer
    raise gr.Error(f"Error: {str(ex)}")
gradio.exceptions.Error: 'Error: Torch not compiled with CUDA enabled'
```

### Additional information

GPU Intel Arc a770

Thank's for your work...

**Comment by lshqqytiger** [comment]
I think you can get **much** better performance with IPEX.
And that extension seems to assume your device as CUDA.
There's [SD.Next](https://github.com/vladmandic/automatic) which is a fork of A1111 and supports DirectML and IPEX and SDXL.

**Comment by StudioDUzes** [comment]
> I think you can get **much** better performance with IPEX. And that extension seems to assume your device as CUDA. There's [SD.Next](https://github.com/vladmandic/automatic) which is a fork of A1111 and is more frequently updated and I'm contributing on and supports DirectML and IPEX and SDXL without any extensions.

Iit's only for linux
