### ISSUE TITLE
[Bug]: Suddenly unable to generate at certain resolutions as of a couple days ago

### ISSUE THREAD

**Issue by Convexity-ai** [lshqqytiger/stable-diffusion-webui-directml#196]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I'm not sure why, but as of a couple of days ago, images I was once able to generate throw different errors depending on the resolution.

Example:

Prompt: cat
Model: revAnimated_v122
Sampler: DPM++ 2M SDE Karras
Steps: 50
Seed: 8888

Resolution: 512x512
Result: `Success`

Resolution: 640x480
Result: `Success`

Resolution: 800x600
Result: `RuntimeError: Could not allocate tensor with 3600000000 bytes. There is not enough GPU video memory available!`

Resolution: 800x800
Result: `RuntimeError: The parameter is incorrect.`

Resolution: 1024x1024
Result: `Success`

Resolution: 1280x960
RuntimeError: `Not enough memory, use lower resolution (max approx. 1024x1024). Need: 0.9GB free, Have:0.7GB free`

I would typically be able to generate images as high as 1280x960 without issue.

I've tried disabling all extensions, switching models, removing and re-cloning the repo, and checking out a specific commit `831ec62` before the DirectML rework in case that was causing the issue. Below is the attached log from the 1280x960 generation.

I can somewhat remediate this issue by switching my cross attention optimization to `--opt-sub-quad` but this will frequently throw nan errors, which I believe is a known issue.

I'm running Windows 11 22621.1992 and using an AMD Radeon RX 6800 XT 16GB with driver version: 23.7.1

Has anyone encountered similar behaviour?

### Steps to reproduce the problem

- Enter parameters specified above.
- Click 'Generate'

### What should have happened?

Images would typically generate without error.

### Version or Commit where the problem happens

bd3de4b

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 6000 above)

### Cross attention optimization

Doggettx

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--medvram --no-half --no-half-vae --always-batch-cond-uncond
```

### List of extensions

Lora
extra-options-section
prompt-bracket-checker

### Console logs

```Shell
*** Error completing request
*** Arguments: ('task(t4i561f34vbxh3w)', 'cat', '', [], 50, 3, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 960, 1280, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], 0, False, 7, True, 1, 1, 1, 100, 'Constant', 0, 'Constant', 0, 4, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0) {}
    Traceback (most recent call last):
      File "C:\Program Files\stable-diffusion-webui-directml\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "C:\Program Files\stable-diffusion-webui-directml\modules\call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "C:\Program Files\stable-diffusion-webui-directml\modules\txt2img.py", line 94, in txt2img
        processed = processing.process_images(p)
      File "C:\Program Files\stable-diffusion-webui-directml\modules\processing.py", line 623, in process_images
        res = process_images_inner(p)
      File "C:\Program Files\stable-diffusion-webui-directml\modules\processing.py", line 742, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "C:\Program Files\stable-diffusion-webui-directml\modules\processing.py", line 995, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "C:\Program Files\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 439, in sample
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
      File "C:\Program Files\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 278, in launch_sampling
        return func()
      File "C:\Program Files\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 439, in <lambda>
        samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
      File "C:\Program Files\stable-diffusion-webui-directml\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Program Files\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\sampling.py", line 626, in sample_dpmpp_2m_sde
        denoised = model(x, sigmas[i] * s_in, **extra_args)
      File "C:\Program Files\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Program Files\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 158, in forward
        x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict([cond_in], image_cond_in))
      File "C:\Program Files\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Program Files\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
        eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
      File "C:\Program Files\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
        return self.inner_model.apply_model(*args, **kwargs)
      File "C:\Program Files\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "C:\Program Files\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "C:\Program Files\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
        x_recon = self.model(x_noisy, t, **cond)
      File "C:\Program Files\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1538, in _call_impl
        result = forward_call(*args, **kwargs)
      File "C:\Program Files\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
        out = self.diffusion_model(x, t, context=cc)
      File "C:\Program Files\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Program Files\stable-diffusion-webui-directml\modules\sd_unet.py", line 91, in UNetModel_forward
        return ldm.modules.diffusionmodules.openaimodel.copy_of_UNetModel_forward_for_webui(self, x, timesteps, context, *args, **kwargs)
      File "C:\Program Files\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 797, in forward
        h = module(h, emb, context)
      File "C:\Program Files\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Program Files\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
        x = layer(x, context)
      File "C:\Program Files\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Program Files\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 334, in forward
        x = block(x, context=context[i])
      File "C:\Program Files\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Program Files\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 269, in forward
        return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
      File "C:\Program Files\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 121, in checkpoint
        return CheckpointFunction.apply(func, len(inputs), *args)
      File "C:\Program Files\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\function.py", line 506, in apply
        return super().apply(*args, **kwargs)  # type: ignore[misc]
      File "C:\Program Files\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 136, in forward
        output_tensors = ctx.run_function(*ctx.input_tensors)
      File "C:\Program Files\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 272, in _forward
        x = self.attn1(self.norm1(x), context=context if self.disable_self_attn else None) + x
      File "C:\Program Files\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Program Files\stable-diffusion-webui-directml\modules\sd_hijack_optimizations.py", line 241, in split_cross_attention_forward
        raise RuntimeError(f'Not enough memory, use lower resolution (max approx. {max_res}x{max_res}). '
    RuntimeError: Not enough memory, use lower resolution (max approx. 1024x1024). Need: 0.9GB free, Have:0.7GB free

---
```

**Comment by Convexity-ai** [comment]
I think I've discovered what's been causing these specific vram issues. I went back and re-cloned the repo again and went through every setting I could until I found some odd behaviour. I set my cross attention back to `Doggettx` for the testing.

When using the command line argument `--always-batch-cond-uncond` with the UI option `Pad prompt/negative prompt to be same length`, images seem to require more vram than normal. Images that would otherwise generate normally will start to throw GPU memory errors.

For me the solution was to either remove `--always-batch-cond-uncond` form the command line arguments, or to disable the UI option `Pad prompt/negative prompt to be same length` These settings don't seem to like being enabled at the same time, at least on my setup.

After re-testing with the same prompt, the results are as expected:

Resolution: 512x512
Result: `Success`

Resolution: 640x480
Result: `Success`

Resolution: 800x600
Result: `Success`

Resolution: 800x800
Result: `Success`

Resolution: 1024x1024
Result: `Success`

Resolution: 1280x960
Result: `Success`

I don't know if this behaviour is a bug or by design. I'll close the issue for now.
