### ISSUE TITLE
[Bug]: This error shows up everytime it gets to 90% 

### ISSUE THREAD

**Issue by Spas120** [lshqqytiger/stable-diffusion-webui-directml#204]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

It crashes when ever it gets around 90%

### Steps to reproduce the problem

1. Press generate
2. wait for it to get to 90%
3. Crashes

### What should have happened?

It should of generated an image

### Version or Commit where the problem happens

1.4.1

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 5000 below)

### Cross attention optimization

Automatic

### Command Line Arguments

```Shell
--xformers --lowvram --autolaunch --no-half
```

### List of extensions

None

### Console logs

```Shell
*** Arguments: ('task(y8ewusud4ezei0b)', 'Pikachu', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 0, '', '', [], 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0) {}
    Traceback (most recent call last):
      File "C:\Users\user\Desktop\SD\stable-diffusion-webui-directml\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\user\Desktop\SD\stable-diffusion-webui-directml\modules\call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "C:\Users\user\Desktop\SD\stable-diffusion-webui-directml\modules\txt2img.py", line 64, in txt2img
        processed = processing.process_images(p)
      File "C:\Users\user\Desktop\SD\stable-diffusion-webui-directml\modules\processing.py", line 623, in process_images
        res = process_images_inner(p)
      File "C:\Users\user\Desktop\SD\stable-diffusion-webui-directml\modules\processing.py", line 744, in process_images_inner
        x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
      File "C:\Users\user\Desktop\SD\stable-diffusion-webui-directml\modules\processing.py", line 744, in <listcomp>
        x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
      File "C:\Users\user\Desktop\SD\stable-diffusion-webui-directml\modules\processing.py", line 525, in decode_first_stage
        x = model.decode_first_stage(x)
      File "C:\Users\user\Desktop\SD\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 17, in <lambda>
        setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
      File "C:\Users\user\Desktop\SD\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 28, in __call__
        return self.__orig_func(*args, **kwargs)
      File "C:\Users\user\Desktop\SD\stable-diffusion-webui-directml\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
        return func(*args, **kwargs)
      File "C:\Users\user\Desktop\SD\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 826, in decode_first_stage
        return self.first_stage_model.decode(z)
      File "C:\Users\user\Desktop\SD\stable-diffusion-webui-directml\modules\lowvram.py", line 54, in first_stage_model_decode_wrap
        return first_stage_model_decode(z)
      File "C:\Users\user\Desktop\SD\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 90, in decode
        dec = self.decoder(z)
      File "C:\Users\user\Desktop\SD\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\user\Desktop\SD\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 631, in forward
        h = self.mid.attn_1(h)
      File "C:\Users\user\Desktop\SD\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
        return forward_call(*args, **kwargs)
      File "C:\Users\user\Desktop\SD\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 258, in forward
        out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None, op=self.attention_op)
      File "C:\Users\user\Desktop\SD\stable-diffusion-webui-directml\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 192, in memory_efficient_attention
        return _memory_efficient_attention(
      File "C:\Users\user\Desktop\SD\stable-diffusion-webui-directml\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 290, in _memory_efficient_attention
        return _memory_efficient_attention_forward(
      File "C:\Users\user\Desktop\SD\stable-diffusion-webui-directml\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 306, in _memory_efficient_attention_forward
        op = _dispatch_fw(inp)
      File "C:\Users\user\Desktop\SD\stable-diffusion-webui-directml\venv\lib\site-packages\xformers\ops\fmha\dispatch.py", line 94, in _dispatch_fw
        return _run_priority_list(
      File "C:\Users\user\Desktop\SD\stable-diffusion-webui-directml\venv\lib\site-packages\xformers\ops\fmha\dispatch.py", line 69, in _run_priority_list
        raise NotImplementedError(msg)
    NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
         query       : shape=(1, 4096, 1, 512) (torch.float32)
         key         : shape=(1, 4096, 1, 512) (torch.float32)
         value       : shape=(1, 4096, 1, 512) (torch.float32)
         attn_bias   : <class 'NoneType'>
         p           : 0.0
    `cutlassF` is not supported because:
        device=privateuseone (supported: {'cuda'})
        Operator wasn't built - see `python -m xformers.info` for more info
    `flshattF` is not supported because:
        device=privateuseone (supported: {'cuda'})
        dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
        max(query.shape[-1] != value.shape[-1]) > 128
        Operator wasn't built - see `python -m xformers.info` for more info
    `tritonflashattF` is not supported because:
        device=privateuseone (supported: {'cuda'})
        dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
        max(query.shape[-1] != value.shape[-1]) > 128
        Operator wasn't built - see `python -m xformers.info` for more info
        triton is not available
    `smallkF` is not supported because:
        device=privateuseone (supported: {'cuda', 'cpu'})
        max(query.shape[-1] != value.shape[-1]) > 32
        Operator wasn't built - see `python -m xformers.info` for more info
        unsupported embed per head: 512

---
```

**Comment by lshqqytiger** [comment]
#5
