### ISSUE TITLE
RuntimeError: ADL2: Failed to get MemoryInfo2 after git pull today

### ISSUE THREAD

**Issue by rs-sim-x** [lshqqytiger/stable-diffusion-webui-directml#216]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

After git pull the UI doesn't start and runs into `RuntimeError: ADL2: Failed to get MemoryInfo2`

### Steps to reproduce the problem

git pull on my backup folder, which I keep with only base model, to use for git pulls before doing it on my main install:

```
Updating 4873e6aa..723974a8
Fast-forward
 modules/dml/__init__.py                            | 40 ++++++++--
 modules/dml/backend.py                             | 46 ++++--------
 modules/dml/memctl/amd/__init__.py                 |  8 --
 modules/dml/memctl/intel/__init__.py               |  6 --
 modules/dml/memctl/memctl.py                       |  8 --
 modules/dml/memctl/nvidia/__init__.py              |  6 --
 modules/dml/memctl/unknown/__init__.py             |  5 --
 modules/dml/memory.py                              | 31 ++++++++
 modules/dml/memory_amd/__init__.py                 |  7 ++
 .../{memctl/amd => memory_amd}/driver/atiadlxx.py  |  0
 .../amd => memory_amd}/driver/atiadlxx_apis.py     |  0
 .../amd => memory_amd}/driver/atiadlxx_defines.py  |  0
 .../driver/atiadlxx_structures.py                  |  0
 modules/dml/pdh/__init__.py                        | 85 ++++++++++++++++++++++
 modules/dml/pdh/apis.py                            | 36 +++++++++
 modules/dml/pdh/defines.py                         | 22 ++++++
 modules/dml/pdh/errors.py                          |  3 +
 modules/dml/pdh/msvcrt.py                          | 11 +++
 modules/dml/pdh/structures.py                      | 41 +++++++++++
 modules/memmon.py                                  | 17 +++--
 modules/shared.py                                  | 10 +--
 modules/ui.py                                      |  2 +
 22 files changed, 305 insertions(+), 79 deletions(-)
 delete mode 100644 modules/dml/memctl/amd/__init__.py
 delete mode 100644 modules/dml/memctl/intel/__init__.py
 delete mode 100644 modules/dml/memctl/memctl.py
 delete mode 100644 modules/dml/memctl/nvidia/__init__.py
 delete mode 100644 modules/dml/memctl/unknown/__init__.py
 create mode 100644 modules/dml/memory.py
 create mode 100644 modules/dml/memory_amd/__init__.py
 rename modules/dml/{memctl/amd => memory_amd}/driver/atiadlxx.py (100%)
 rename modules/dml/{memctl/amd => memory_amd}/driver/atiadlxx_apis.py (100%)
 rename modules/dml/{memctl/amd => memory_amd}/driver/atiadlxx_defines.py (100%)
 rename modules/dml/{memctl/amd => memory_amd}/driver/atiadlxx_structures.py (100%)
 create mode 100644 modules/dml/pdh/__init__.py
 create mode 100644 modules/dml/pdh/apis.py
 create mode 100644 modules/dml/pdh/defines.py
 create mode 100644 modules/dml/pdh/errors.py
 create mode 100644 modules/dml/pdh/msvcrt.py
 create mode 100644 modules/dml/pdh/structures.py
```
starting webui with

```
@echo off
set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--medvram --opt-sub-quad-attention --disable-nan-check
call webui.bat
```
produces

```
venv "C:\stable-diffusion-webui-directml - backup\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.5.1
Commit hash: 723974a8b74ffd5acc1a1fdaf36e9c2426651537
Launching Web UI with arguments: --medvram --opt-sub-quad-attention --disable-nan-check
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-directml - backup\launch.py", line 39, in <module>
    main()
  File "C:\stable-diffusion-webui-directml - backup\launch.py", line 35, in main
    start()
  File "C:\stable-diffusion-webui-directml - backup\modules\launch_utils.py", line 443, in start
    import webui
  File "C:\stable-diffusion-webui-directml - backup\webui.py", line 54, in <module>
    from modules.call_queue import wrap_gradio_gpu_call, wrap_queued_call, queue_lock  # noqa: F401
  File "C:\stable-diffusion-webui-directml - backup\modules\call_queue.py", line 6, in <module>
    from modules import shared, progress, errors
  File "C:\stable-diffusion-webui-directml - backup\modules\shared.py", line 72, in <module>
    directml_init()
  File "C:\stable-diffusion-webui-directml - backup\modules\dml\__init__.py", line 38, in directml_init
    from modules.dml.backend import DirectML # pylint: disable=ungrouped-imports
  File "C:\stable-diffusion-webui-directml - backup\modules\dml\backend.py", line 10, in <module>
    from .memory_amd import AMDMemoryProvider
  File "C:\stable-diffusion-webui-directml - backup\modules\dml\memory_amd\__init__.py", line 3, in <module>
    class AMDMemoryProvider:
  File "C:\stable-diffusion-webui-directml - backup\modules\dml\memory_amd\__init__.py", line 4, in AMDMemoryProvider
    driver: ATIADLxx = ATIADLxx()
  File "C:\stable-diffusion-webui-directml - backup\modules\dml\memory_amd\driver\atiadlxx.py", line 22, in __init__
    self.iHyperMemorySize = self.get_memory_info2(0).iHyperMemorySize
  File "C:\stable-diffusion-webui-directml - backup\modules\dml\memory_amd\driver\atiadlxx.py", line 28, in get_memory_info2
    raise RuntimeError("ADL2: Failed to get MemoryInfo2")
RuntimeError: ADL2: Failed to get MemoryInfo2
```
temp solution: running `git reset --keep HEAD@{1}` , the ui can be started normal again and can generate

### What should have happened?

start normal, this is the output after running `git reset --keep HEAD@{1}`

venv "C:\stable-diffusion-webui-directml - backup\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.5.1
Commit hash: 4873e6aaba62c2fa2e4481798e85098e50e1e2c6
Launching Web UI with arguments: --medvram --opt-sub-quad-attention --disable-nan-check
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Warning: caught exception '', memory monitor disabled
Loading weights [6ce0161689] from C:\stable-diffusion-webui-directml - backup\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: C:\stable-diffusion-webui-directml - backup\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 14.4s (launcher: 0.8s, import torch: 3.8s, import gradio: 1.4s, setup paths: 0.8s, other imports: 4.6s, setup codeformer: 0.2s, load scripts: 1.9s, create ui: 0.4s, gradio launch: 0.3s).
DiffusionWrapper has 859.52 M params.
Applying attention optimization: sub-quadratic... done.
Model loaded in 9.1s (load weights from disk: 0.7s, create model: 0.6s, apply weights to model: 5.9s, apply half(): 1.5s, calculate empty prompt: 0.4s).
```

### Version or Commit where the problem happens

1.5.1

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 6000 above)

### Cross attention optimization

Automatic

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
set COMMANDLINE_ARGS=--medvram --opt-sub-quad-attention --disable-nan-check
```

### List of extensions

No

### Console logs

```Shell
venv "C:\stable-diffusion-webui-directml - backup\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.5.1
Commit hash: 723974a8b74ffd5acc1a1fdaf36e9c2426651537
Launching Web UI with arguments: --medvram --opt-sub-quad-attention --disable-nan-check
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-directml - backup\launch.py", line 39, in <module>
    main()
  File "C:\stable-diffusion-webui-directml - backup\launch.py", line 35, in main
    start()
  File "C:\stable-diffusion-webui-directml - backup\modules\launch_utils.py", line 443, in start
    import webui
  File "C:\stable-diffusion-webui-directml - backup\webui.py", line 54, in <module>
    from modules.call_queue import wrap_gradio_gpu_call, wrap_queued_call, queue_lock  # noqa: F401
  File "C:\stable-diffusion-webui-directml - backup\modules\call_queue.py", line 6, in <module>
    from modules import shared, progress, errors
  File "C:\stable-diffusion-webui-directml - backup\modules\shared.py", line 72, in <module>
    directml_init()
  File "C:\stable-diffusion-webui-directml - backup\modules\dml\__init__.py", line 38, in directml_init
    from modules.dml.backend import DirectML # pylint: disable=ungrouped-imports
  File "C:\stable-diffusion-webui-directml - backup\modules\dml\backend.py", line 10, in <module>
    from .memory_amd import AMDMemoryProvider
  File "C:\stable-diffusion-webui-directml - backup\modules\dml\memory_amd\__init__.py", line 3, in <module>
    class AMDMemoryProvider:
  File "C:\stable-diffusion-webui-directml - backup\modules\dml\memory_amd\__init__.py", line 4, in AMDMemoryProvider
    driver: ATIADLxx = ATIADLxx()
  File "C:\stable-diffusion-webui-directml - backup\modules\dml\memory_amd\driver\atiadlxx.py", line 22, in __init__
    self.iHyperMemorySize = self.get_memory_info2(0).iHyperMemorySize
  File "C:\stable-diffusion-webui-directml - backup\modules\dml\memory_amd\driver\atiadlxx.py", line 28, in get_memory_info2
    raise RuntimeError("ADL2: Failed to get MemoryInfo2")
RuntimeError: ADL2: Failed to get MemoryInfo2
```

### Additional information

running `git reset --keep HEAD@{1}` in the folder, the ui can be started normal again

GPU is a Radeon (TM) Pro WX 7100 Graphics with 8GB, drivers are 23.5.2, 16GB computer memory

**Comment by lshqqytiger** [comment]
Change `DirectML mmory stats provider` to `Performance Counter` or `None` in Settings -> Optimization.

**Comment by rs-sim-x** [comment]
> Change `DirectML memory stats provider` to `Performance Counter` or `None` in Settings -> Optimization. If webui does not launch, edit `config.json` like [#219 (comment)](https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/219#issuecomment-1660672745)

I don't have the setting:

![optimizations](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/138529218/5f31fef4-ba8b-4b24-9066-cf98dc7f550e)

and this is the config.json after git pull, also no directml 

```
{
    "samples_save": true,
    "samples_format": "png",
    "samples_filename_pattern": "",
    "save_images_add_number": true,
    "grid_save": false,
    "grid_format": "png",
    "grid_extended_filename": true,
    "grid_only_if_multiple": true,
    "grid_prevent_empty_spots": false,
    "n_rows": -1,
    "enable_pnginfo": true,
    "save_txt": true,
    "save_images_before_face_restoration": true,
    "save_images_before_highres_fix": true,
    "save_images_before_color_correction": true,
    "save_mask": false,
    "save_mask_composite": false,
    "jpeg_quality": 80,
    "webp_lossless": false,
    "export_for_4chan": true,
    "img_downscale_threshold": 4.0,
    "target_side_length": 4000,
    "img_max_size_mp": 200,
    "use_original_name_batch": true,
    "use_upscaler_name_as_suffix": false,
    "save_selected_only": true,
    "save_init_img": false,
    "temp_dir": "",
    "clean_temp_dir_at_start": false,
    "outdir_samples": "",
    "outdir_txt2img_samples": "outputs/txt2img-images",
    "outdir_img2img_samples": "outputs/img2img-images",
    "outdir_extras_samples": "outputs/extras-images",
    "outdir_grids": "",
    "outdir_txt2img_grids": "outputs/txt2img-grids",
    "outdir_img2img_grids": "outputs/img2img-grids",
    "outdir_save": "log/images",
    "outdir_init_images": "outputs/init-images",
    "save_to_dirs": true,
    "grid_save_to_dirs": true,
    "use_save_to_dirs_for_ui": false,
    "directories_filename_pattern": "[date]",
    "directories_max_prompt_words": 8,
    "ESRGAN_tile": 192,
    "ESRGAN_tile_overlap": 8,
    "realesrgan_enabled_models": [
        "R-ESRGAN 4x+",
        "R-ESRGAN 4x+ Anime6B"
    ],
    "upscaler_for_img2img": null,
    "face_restoration_model": "CodeFormer",
    "code_former_weight": 0.5,
    "face_restoration_unload": false,
    "show_warnings": false,
    "memmon_poll_rate": 8,
    "samples_log_stdout": false,
    "multiple_tqdm": true,
    "print_hypernet_extra": false,
    "list_hidden_files": true,
    "unload_models_when_training": false,
    "pin_memory": false,
    "save_optimizer_state": false,
    "save_training_settings_to_txt": true,
    "dataset_filename_word_regex": "",
    "dataset_filename_join_string": " ",
    "training_image_repeats_per_epoch": 1,
    "training_write_csv_every": 500,
    "training_xattention_optimizations": false,
    "training_enable_tensorboard": false,
    "training_tensorboard_save_images": false,
    "training_tensorboard_flush_every": 120,
    "sd_model_checkpoint": "v1-5-pruned-emaonly.safetensors [6ce0161689]",
    "sd_checkpoint_cache": 0,
    "sd_vae_checkpoint_cache": 0,
    "sd_vae": "None",
    "sd_vae_as_default": false,
    "inpainting_mask_weight": 1.0,
    "initial_noise_multiplier": 1.0,
    "img2img_color_correction": false,
    "img2img_fix_steps": false,
    "img2img_background_color": "#ffffff",
    "enable_quantization": false,
    "enable_emphasis": true,
    "enable_batch_seeds": true,
    "comma_padding_backtrack": 20,
    "CLIP_stop_at_last_layers": 1,
    "upcast_attn": false,
    "randn_source": "GPU",
    "cross_attention_optimization": "Automatic",
    "s_min_uncond": 0,
    "token_merging_ratio": 0.0,
    "token_merging_ratio_img2img": 0.0,
    "token_merging_ratio_hr": 0.0,
    "use_old_emphasis_implementation": false,
    "use_old_karras_scheduler_sigmas": false,
    "no_dpmpp_sde_batch_determinism": false,
    "use_old_hires_fix_width_height": false,
    "dont_fix_second_order_samplers_schedule": false,
    "interrogate_keep_models_in_memory": false,
    "interrogate_return_ranks": false,
    "interrogate_clip_num_beams": 1,
    "interrogate_clip_min_length": 24,
    "interrogate_clip_max_length": 48,
    "interrogate_clip_dict_limit": 1500,
    "interrogate_clip_skip_categories": [],
    "interrogate_deepbooru_score_threshold": 0.5,
    "deepbooru_sort_alpha": true,
    "deepbooru_use_spaces": true,
    "deepbooru_escape": true,
    "deepbooru_filter_tags": "",
    "extra_networks_show_hidden_directories": true,
    "extra_networks_hidden_models": "When searched",
    "extra_networks_default_view": "cards",
    "extra_networks_default_multiplier": 1.0,
    "extra_networks_card_width": 0,
    "extra_networks_card_height": 0,
    "extra_networks_add_text_separator": " ",
    "ui_extra_networks_tab_reorder": "",
    "sd_hypernetwork": "None",
    "localization": "None",
    "gradio_theme": "Default",
    "img2img_editor_height": 720,
    "return_grid": true,
    "return_mask": false,
    "return_mask_composite": false,
    "do_not_show_images": false,
    "send_seed": true,
    "send_size": true,
    "font": "",
    "js_modal_lightbox": true,
    "js_modal_lightbox_initially_zoomed": true,
    "js_modal_lightbox_gamepad": false,
    "js_modal_lightbox_gamepad_repeat": 250,
    "show_progress_in_title": true,
    "samplers_in_dropdown": true,
    "dimensions_and_batch_together": true,
    "keyedit_precision_attention": 0.1,
    "keyedit_precision_extra": 0.05,
    "keyedit_delimiters": ".,\\/!?%^*;:{}=`~()",
    "quicksettings_list": [
        "sd_model_checkpoint"
    ],
    "ui_tab_order": [],
    "hidden_tabs": [],
    "ui_reorder": "inpaint, sampler, checkboxes, hires_fix, dimensions, cfg, seed, batch, override_settings, scripts",
    "hires_fix_show_sampler": false,
    "hires_fix_show_prompts": false,
    "add_model_hash_to_info": true,
    "add_model_name_to_info": true,
    "add_version_to_infotext": true,
    "disable_weights_auto_swap": true,
    "show_progressbar": true,
    "live_previews_enable": true,
    "live_previews_image_format": "png",
    "show_progress_grid": true,
    "show_progress_every_n_steps": 10,
    "show_progress_type": "Approx cheap",
    "live_preview_content": "Prompt",
    "live_preview_refresh_period": 1000,
    "hide_samplers": [],
    "eta_ddim": 0.0,
    "eta_ancestral": 1.0,
    "ddim_discretize": "uniform",
    "s_churn": 0.0,
    "s_tmin": 0.0,
    "s_noise": 1.0,
    "eta_noise_seed_delta": 0,
    "always_discard_next_to_last_sigma": false,
    "uni_pc_variant": "bh1",
    "uni_pc_skip_type": "time_uniform",
    "uni_pc_order": 3,
    "uni_pc_lower_order_final": true,
    "postprocessing_enable_in_main_ui": [],
    "postprocessing_operation_order": [],
    "upscaling_max_images_in_cache": 5,
    "disabled_extensions": [],
    "disable_all_extensions": "none",
    "restore_config_state_file": "",
    "sd_checkpoint_hash": "6ce0161689b3853acaa03779ec93eafe75a02f4ced659bee03f50797806fa2fa",
    "ldsr_steps": 100,
    "ldsr_cached": false,
    "SCUNET_tile": 256,
    "SCUNET_tile_overlap": 8,
    "SWIN_tile": 192,
    "SWIN_tile_overlap": 8,
    "lora_functional": false,
    "sd_lora": "None",
    "lora_preferred_name": "Alias from file",
    "lora_add_hashes_to_infotext": true,
    "control_net_model_config": "models\\cldm_v15.yaml",
    "control_net_model_adapter_config": "models\\t2iadapter_sketch_sd14v1.yaml",
    "control_net_detectedmap_dir": "detected_maps",
    "control_net_models_path": "",
    "control_net_modules_path": "",
    "control_net_max_models_num": 3,
    "control_net_model_cache_size": 1,
    "control_net_no_detectmap": false,
    "control_net_detectmap_autosaving": false,
    "control_net_allow_script_control": false,
    "control_net_sync_field_args": false,
    "controlnet_show_batch_images_in_ui": false,
    "controlnet_increment_seed_during_batch": false,
    "controlnet_disable_control_type": false,
    "controlnet_disable_openpose_edit": false,
    "ui_reorder_list": [
        "inpaint",
        "sampler",
        "checkboxes",
        "hires_fix",
        "dimensions",
        "cfg",
        "seed",
        "batch",
        "override_settings",
        "scripts"
    ],
    "grid_zip_filename_pattern": "",
    "grid_text_active_color": "#000000",
    "grid_text_inactive_color": "#999999",
    "grid_background_color": "#ffffff",
    "disable_mmap_load_safetensors": false,
    "sd_unet": "Automatic",
    "auto_vae_precision": true,
    "sdxl_crop_top": 0.0,
    "sdxl_crop_left": 0.0,
    "sdxl_refiner_low_aesthetic_score": 2.5,
    "sdxl_refiner_high_aesthetic_score": 6.0,
    "enable_mem_pattern": true,
    "enable_mem_reuse": true,
    "reload_model_before_each_generation": false,
    "offload_state_dict": false,
    "pad_cond_uncond": false,
    "experimental_persistent_cond_cache": false,
    "hires_fix_use_firstpass_conds": false,
    "extra_networks_card_text_scale": 1,
    "extra_networks_card_show_desc": true,
    "textual_inversion_print_at_load": false,
    "textual_inversion_add_hashes_to_infotext": true,
    "lora_show_all": false,
    "lora_hide_unknown_for_versions": [],
    "keyedit_move": true,
    "disable_token_counters": false,
    "extra_options": [],
    "extra_options_accordion": false,
    "add_user_name_to_info": false,
    "infotext_styles": "Apply if any",
    "k_sched_type": "Automatic",
    "sigma_min": 0.0,
    "sigma_max": 0.0,
    "rho": 0.0,
    "canvas_hotkey_zoom": "Alt",
    "canvas_hotkey_adjust": "Ctrl",
    "canvas_hotkey_move": "F",
    "canvas_hotkey_fullscreen": "S",
    "canvas_hotkey_reset": "R",
    "canvas_hotkey_overlap": "O",
    "canvas_show_tooltip": true,
    "canvas_blur_prompt": false,
    "canvas_disabled_functions": [
        "Overlap"
    ]
}
```

**Comment by rs-sim-x** [comment]
It would seem that that at some point the updates didn't work properly for something else here. 

I have cloned it new and started it without any arguments. After this install finished and started, I closed the UI and ended the process. 

Then I started the old backup (still before git pull), I checked the settings and now the settings showed the `DirectML memory stats provider` settings. Remember, I didn't touch that backup folder and my previous post showed the settings, as you can see, its missing. So it seems that previous updates failed somehow, no?

Anyways, my issue solved, going to use the new clone as new main. If you need any information else, let me know, else this issue can be closed. Cheers :)
