### ISSUE TITLE
[Bug]: Cannot start up SD

### ISSUE THREAD

**Issue by NinePT** [lshqqytiger/stable-diffusion-webui-directml#217]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I got the opts error and uninstalled and installed again and now i get this error, I switched commits with the ones that got fixed on the opts error but nothing working

venv "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.5.1
Commit hash: 723974a8b74ffd5acc1a1fdaf36e9c2426651537

Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72

Installing requirements for TemporalKit extension

Launching Web UI with arguments: --medvram --always-batch-cond-uncond --api --precision full --opt-sdp-attention --no-half --opt-split-attention --opt-sub-quad-attention --sub-quad-q-chunk-size 512 --sub-quad-kv-chunk-size 512 --sub-quad-chunk-threshold 80 --use-cpu interrogate gfpgan codeformer --upcast-sampling --api --autolaunch
Traceback (most recent call last):
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\launch.py", line 39, in <module>
    main()
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\launch.py", line 35, in main
    start()
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\modules\launch_utils.py", line 443, in start
    import webui
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\webui.py", line 39, in <module>
    import pytorch_lightning   # noqa: F401 # pytorch_lightning should be imported after torch, but it re-enables warnings on import so import once to disable them
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\callbacks\batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\callbacks\callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\types.py", line 27, in <module>
    from torchmetrics import Metric
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torchmetrics\__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torchmetrics\functional\__init__.py", line 121, in <module>
    from torchmetrics.functional.text._deprecated import _bleu_score as bleu_score
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torchmetrics\functional\text\__init__.py", line 31, in <module>
    from torchmetrics.functional.text.bert import bert_score
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torchmetrics\functional\text\bert.py", line 25, in <module>
    from torchmetrics.functional.text.helper_embedding_metric import (
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torchmetrics\functional\text\helper_embedding_metric.py", line 27, in <module>
    from transformers import AutoModelForMaskedLM, AutoTokenizer, PreTrainedModel, PreTrainedTokenizerBase
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\utils\__init__.py", line 34, in <module>
    from .generic import (
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\utils\generic.py", line 29, in <module>
    from .import_utils import is_flax_available, is_tf_available, is_torch_available, is_torch_fx_proxy
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\utils\import_utils.py", line 34, in <module>
    from . import logging
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\utils\logging.py", line 31, in <module>
    from tqdm import auto as tqdm_lib
ImportError: cannot import name 'auto' from 'tqdm' (E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\tqdm\__init__.py)
Press any key to continue . . .

### Steps to reproduce the problem

1. Go to SD folder 
2. Press webui-user.bat
3. Open SD

### What should have happened?

Opened SD without getting an error

### Version or Commit where the problem happens

723974a

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 5000 below)

### Cross attention optimization

Automatic

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--medvram --always-batch-cond-uncond --api --precision full --opt-sdp-attention --no-half --opt-split-attention --opt-sub-quad-attention --sub-quad-q-chunk-size 512 --sub-quad-kv-chunk-size 512 --sub-quad-chunk-threshold 80  --use-cpu interrogate gfpgan codeformer --upcast-sampling --api  --autolaunch
```

### List of extensions

![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/78700203/84071df9-011b-42a5-8d23-4bc80eaabc64)

### Console logs

```Shell
venv "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.5.1
Commit hash: 723974a8b74ffd5acc1a1fdaf36e9c2426651537


Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72


Installing requirements for TemporalKit extension

Launching Web UI with arguments: --medvram --always-batch-cond-uncond --api --precision full --opt-sdp-attention --no-half --opt-split-attention --opt-sub-quad-attention --sub-quad-q-chunk-size 512 --sub-quad-kv-chunk-size 512 --sub-quad-chunk-threshold 80 --use-cpu interrogate gfpgan codeformer --upcast-sampling --api --autolaunch
Traceback (most recent call last):
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\launch.py", line 39, in <module>
    main()
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\launch.py", line 35, in main
    start()
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\modules\launch_utils.py", line 443, in start
    import webui
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\webui.py", line 39, in <module>
    import pytorch_lightning   # noqa: F401 # pytorch_lightning should be imported after torch, but it re-enables warnings on import so import once to disable them
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\__init__.py", line 35, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\callbacks\__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\callbacks\batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\callbacks\callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\types.py", line 27, in <module>
    from torchmetrics import Metric
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torchmetrics\__init__.py", line 14, in <module>
    from torchmetrics import functional  # noqa: E402
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torchmetrics\functional\__init__.py", line 121, in <module>
    from torchmetrics.functional.text._deprecated import _bleu_score as bleu_score
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torchmetrics\functional\text\__init__.py", line 31, in <module>
    from torchmetrics.functional.text.bert import bert_score
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torchmetrics\functional\text\bert.py", line 25, in <module>
    from torchmetrics.functional.text.helper_embedding_metric import (
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torchmetrics\functional\text\helper_embedding_metric.py", line 27, in <module>
    from transformers import AutoModelForMaskedLM, AutoTokenizer, PreTrainedModel, PreTrainedTokenizerBase
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\__init__.py", line 30, in <module>
    from . import dependency_versions_check
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\dependency_versions_check.py", line 17, in <module>
    from .utils.versions import require_version, require_version_core
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\utils\__init__.py", line 34, in <module>
    from .generic import (
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\utils\generic.py", line 29, in <module>
    from .import_utils import is_flax_available, is_tf_available, is_torch_available, is_torch_fx_proxy
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\utils\import_utils.py", line 34, in <module>
    from . import logging
  File "E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\utils\logging.py", line 31, in <module>
    from tqdm import auto as tqdm_lib
ImportError: cannot import name 'auto' from 'tqdm' (E:\Ambiente de Trabalho\Stable Diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\tqdm\__init__.py)
Press any key to continue . . .
```

**Comment by lshqqytiger** [comment]
Reinstall `tqdm` or remove `venv` folder.

**Comment by NinePT** [comment]
Removing venv didnt work for me, i did a clean install and it worked, after adding all my models and extensions try to run but appeared the same error, and i have been moving my stuff from the backup to the clean install one by one and when i moved the temporal kit extension to the clean install,  the error appeared and even if i remove the temporal kit folder it continues
