### ISSUE TITLE
[Bug]: RuntimeError: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.

### ISSUE THREAD

**Issue by Lack-Of-Name** [lshqqytiger/stable-diffusion-webui-directml#22]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

started the ui up with the following arguments: --lowvram --opt-split-attention --precision full --no-half
It started up just fine, loaded the model well, and then it generated the picture fine until 100%, after which it gave me this sprawling error:

100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [12:23<00:00, 37.18s/it]
Error completing request███████████████████████████████████████████████████████████████| 20/20 [11:36<00:00, 43.12s/it]
Arguments: ('task(cv2lpkdnznq2b01)', 'cactus', 'person, people', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "E:\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "E:\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "E:\stable-diffusion-webui-directml\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "E:\stable-diffusion-webui-directml\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "E:\stable-diffusion-webui-directml\modules\processing.py", line 634, in process_images_inner
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "E:\stable-diffusion-webui-directml\modules\processing.py", line 634, in <listcomp>
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "E:\stable-diffusion-webui-directml\modules\processing.py", line 423, in decode_first_stage
    x = model.decode_first_stage(x)
  File "E:\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "E:\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 826, in decode_first_stage
    return self.first_stage_model.decode(z)
  File "E:\stable-diffusion-webui-directml\modules\lowvram.py", line 52, in first_stage_model_decode_wrap
    return first_stage_model_decode(z)
  File "E:\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 90, in decode
    dec = self.decoder(z)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 649, in forward
    h = self.conv_out(h)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\stable-diffusion-webui-directml\extensions-builtin\Lora\lora.py", line 182, in lora_Conv2d_forward
    return lora_forward(self, input, torch.nn.Conv2d_forward_before_lora(self, input))
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.

So far I have tried re-installing all of the dependencies and the ui. still gave me this error

### Steps to reproduce the problem

1. open stable-diffusion-webui-directml folder, and open the webui-user.bat file (Running on ssd drive)

2.load the ui w/ anything v4.5 ckpt

3.generate a picture

4. tada! an error!

### What should have happened?

finished processing the picture.

### Commit where the problem happens

 6a6dd5879811156baeea3a1c5b8c6aa306ec9dd9

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--lowvram --opt-split-attention --precision full --no-half
```

### List of extensions

Lastpass

### Console logs

```Shell
venv "E:\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: 6a6dd5879811156baeea3a1c5b8c6aa306ec9dd9
Installing requirements for Web UI
Launching Web UI with arguments: --lowvram --opt-split-attention --precision full --no-half
Warning: experimental graphic memory optimization is disabled due to gpu vendor. Currently this optimization is only available for AMDGPUs.
Disabled experimental graphic memory optimizations.
Interrogate will be fallen back to cpu. Because DirectML device does not support it.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
Loading weights [e4b17ce185] from E:\stable-diffusion-webui-directml\models\Stable-diffusion\anything-v4.5-pruned.ckpt
Creating model from config: E:\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(0):
Model loaded in 103.4s (load weights from disk: 100.7s, create model: 1.3s, apply weights to model: 1.2s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [12:23<00:00, 37.18s/it]
Error completing request███████████████████████████████████████████████████████████████| 20/20 [11:36<00:00, 43.12s/it]
Arguments: ('task(cv2lpkdnznq2b01)', 'cactus', 'person, people', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "E:\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "E:\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "E:\stable-diffusion-webui-directml\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "E:\stable-diffusion-webui-directml\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "E:\stable-diffusion-webui-directml\modules\processing.py", line 634, in process_images_inner
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "E:\stable-diffusion-webui-directml\modules\processing.py", line 634, in <listcomp>
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "E:\stable-diffusion-webui-directml\modules\processing.py", line 423, in decode_first_stage
    x = model.decode_first_stage(x)
  File "E:\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "E:\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 826, in decode_first_stage
    return self.first_stage_model.decode(z)
  File "E:\stable-diffusion-webui-directml\modules\lowvram.py", line 52, in first_stage_model_decode_wrap
    return first_stage_model_decode(z)
  File "E:\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 90, in decode
    dec = self.decoder(z)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 649, in forward
    h = self.conv_out(h)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\stable-diffusion-webui-directml\extensions-builtin\Lora\lora.py", line 182, in lora_Conv2d_forward
    return lora_forward(self, input, torch.nn.Conv2d_forward_before_lora(self, input))
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "E:\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: The GPU device instance has been suspended. Use GetDeviceRemovedReason to determine the appropriate action.
```

### Additional information

-

**Comment by lshqqytiger** [comment]
It seems to be a DirectX API error..

**Comment by Lack-Of-Name** [comment]
Thank you for your reply. I will try reinstalling directX

**Comment by Lack-Of-Name** [comment]
Note: It worked! Thx, there was nothing else that matched my error

**Comment by GitGudGandalf** [comment]
Same error here. how did you reinstall directx? on my windows 10 I tried with the old installer for directx10 and 11 but it did not help. cant find how to reinstall directx12..

**Comment by lshqqytiger** [comment]
There is no stand-alone package for DirectX.
Check your Windows updates.
[More Information](https://support.microsoft.com/en-us/topic/how-to-install-the-latest-version-of-directx-d1f5ffa5-dae2-246c-91b1-ee1e973ed8c2)

**Comment by Krblanc** [comment]
I am using directx12 and I still get this error. Do I need to reinstall directx12, install an older version, or is there another fix. Link video/resource if possible.
No prompt produces an image after clicking generate because of this runtime error.

**Comment by oStarlight** [comment]
I still have this exact issue. My DirectX version in on version 12

**Comment by mikeyang01** [comment]
+1

**Comment by duclong2502** [comment]
![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/38269972/2aa7a603-e37e-4303-b562-964de100ff9e)
This is my error. Help me!

**Comment by Lack-Of-Name** [comment]
I have found that this error can also be replicated by over-allocating your VRAM - try setting your resolution lower and restarting after X amount of uses.

Meanwhile, I'm now running Stable Diffusion + Controlnet on a spare MAC, instead of my intel XE graphics card... can't replicate it if I try.
