### ISSUE TITLE
[Bug]: Check failed: !is_dim_broadcast || non_broadcast_dim_size == 1

### ISSUE THREAD

**Issue by popsoda27** [lshqqytiger/stable-diffusion-webui-directml#227]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Error upon first generation

### Steps to reproduce the problem

1. Input positive/negative prompts
2. Set parameters: 512x768, Steps=35, CFG=6, DPM++ 2M SDE Karras, Batch count/size=1, Adetailer enabled
3. Generate

### What should have happened?

Generate 1st image

### Version or Commit where the problem happens

https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/3f69a46aced47d8b14a9abb24181231ae7976966

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

AMD GPUs (RX 6000 above)

### Cross attention optimization

Automatic

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
set PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.5,max_split_size_mb:256
set COMMANDLINE_ARGS=--opt-split-attention --precision full --always-batch-cond-uncond --disable-nan-check --api  --medvram --no-half --no-half-vae --sub-quad-q-chunk-size 1024 --sub-quad-kv-chunk-size 256 --sub-quad-chunk-threshold 75 --use-cpu interrogate clip --no-hashing --autolaunch --api
set SAFETENSORS_FAST_GPU=1
```

### List of extensions

a1111-sd-webui-lycoris
adetailer
multidiffusion-upscaler-for-automatic1111
openpose-editor
sd-dynamic-prompts
sd-dynamic-thresholding
sd-web-ui-quickcss
sd-webui-controlnet
sd-webui-cutoff
sd-webui-infinite-image-browsing
sd-webui-lora-block-weight
sd-webui-model-converter
sd_civitai_extension
stable-diffusion-webui
stable-diffusion-webui-wd14-tagger
ultimate-upscale-for-automatic1111

### Console logs

```Shell
venv "E:\Downloads\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.5.1
Commit hash: 3f69a46aced47d8b14a9abb24181231ae7976966





#######################################################################################################
Initializing Civitai Link
If submitting an issue on github, please provide the below text for debugging purposes:

Python revision: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Civitai Link revision: 2dfc03c17304278ca0b456366cc7871a2af8377b
SD-WebUI revision: 3f69a46aced47d8b14a9abb24181231ae7976966

Checking Civitai Link requirements...
[!] python-socketio[client] version 5.7.2 NOT installed.

#######################################################################################################

Launching Web UI with arguments: --opt-split-attention --precision full --always-batch-cond-uncond --disable-nan-check --api --medvram --no-half --no-half-vae --sub-quad-q-chunk-size 1024 --sub-quad-kv-chunk-size 256 --sub-quad-chunk-threshold 75 --use-cpu interrogate clip --no-hashing --autolaunch --api
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
*** Error loading script: GenGif.py
    Traceback (most recent call last):
      File "E:\Downloads\stable-diffusion-webui-directml\modules\scripts.py", line 319, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "E:\Downloads\stable-diffusion-webui-directml\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "E:\Downloads\stable-diffusion-webui-directml\scripts\GenGif.py", line 13, in <module>
        dimY = int(sys.argv[1])
    ValueError: invalid literal for int() with base 10: '--opt-split-attention'

---
[-] ADetailer initialized. version: 23.7.11, num models: 10
2023-08-05 04:07:08,970 - ControlNet - INFO - ControlNet v1.1.235
ControlNet preprocessor location: E:\Downloads\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\downloads
2023-08-05 04:07:09,073 - ControlNet - INFO - ControlNet v1.1.235
Civitai: API loaded
Loading weights [879db523c3] from E:\Downloads\stable-diffusion-webui-directml\models\Stable-diffusion\dreamshaper_8.safetensors
Creating model from config: E:\Downloads\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
DiffusionWrapper has 859.52 M params.
Civitai: Check resources for missing preview images
Startup time: 32.7s (launcher: 6.0s, import torch: 4.2s, import gradio: 1.1s, setup paths: 0.9s, other imports: 3.4s, opts onchange: 0.5s, setup codeformer: 0.2s, load scripts: 14.8s, create ui: 1.0s, gradio launch: 0.4s).
Civitai: Found 1 resources missing preview images
Civitai: Found 1 hash matches
Civitai: Updated 0 preview images
Loading VAE weights specified in settings: E:\Downloads\stable-diffusion-webui-directml\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: Doggettx... done.
Model loaded in 13.9s (load weights from disk: 0.9s, create model: 0.6s, apply weights to model: 10.3s, load VAE: 1.4s, calculate empty prompt: 0.6s).
  0%|                                                                                           | 0/35 [00:00<?, ?it/s][F D:\a\_work\1\s\pytorch-directml-plugin\torch_directml\csrc\engine\dml_tensor_desc.cc:135] Check failed: !is_dim_broadcast || non_broadcast_dim_size == 1
```

### Additional information

None

**Comment by EygenCat** [comment]
On Rx 6700xt, exactly the same problem.  But from this [Author ](https://civitai.com/user/eeeeeqeq/models)  does not work. But this [Lyco](https://civitai.com/models/20735/mejiro-ardan-umamusume)  works
