### ISSUE TITLE
[Bug]: Expected a value of type 'List[int]' for argument 'pad' but instead found type 'Tensor (inferred)'.

### ISSUE THREAD

**Issue by sdn3rd** [lshqqytiger/stable-diffusion-webui-directml#249]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

D:\sd>webui-user.bat
venv "D:\sd\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: ee3d3904c327031ed193a1e6d8472c3eed9409c7
Installing requirements for Web UI
Launching Web UI with arguments: --opt-sub-quad-attention --disable-nan-check
Thank you for helping to bring diversity to the graphics card market.
Disabled experimental graphic memory optimizations.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
Traceback (most recent call last):
  File "D:\sd\launch.py", line 353, in <module>
    start()
  File "D:\sd\launch.py", line 344, in start
    import webui
  File "D:\sd\webui.py", line 15, in <module>
    from modules import import_hook, errors, extra_networks, ui_extra_networks_checkpoints
  File "D:\sd\modules\ui_extra_networks_checkpoints.py", line 6, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "D:\sd\modules\sd_models.py", line 15, in <module>
    from modules import paths, shared, modelloader, devices, script_callbacks, sd_vae, sd_disable_initialization, errors, hashes, sd_models_config
  File "D:\sd\modules\sd_disable_initialization.py", line 1, in <module>
    import ldm.modules.encoders.modules
  File "D:\sd\repositories\stable-diffusion-stability-ai\ldm\modules\encoders\modules.py", line 3, in <module>
    import kornia
  File "D:\sd\venv\lib\site-packages\kornia\__init__.py", line 11, in <module>
    from . import augmentation, color, contrib, core, enhance, feature, io, losses, metrics, morphology, tracking, utils, x
  File "D:\sd\venv\lib\site-packages\kornia\augmentation\__init__.py", line 1, in <module>
    from kornia.augmentation._2d import (
  File "D:\sd\venv\lib\site-packages\kornia\augmentation\_2d\__init__.py", line 3, in <module>
    from kornia.augmentation._2d.mix import *
  File "D:\sd\venv\lib\site-packages\kornia\augmentation\_2d\mix\__init__.py", line 1, in <module>
    from kornia.augmentation._2d.mix.cutmix import RandomCutMix, RandomCutMixV2
  File "D:\sd\venv\lib\site-packages\kornia\augmentation\_2d\mix\cutmix.py", line 7, in <module>
    from kornia.augmentation._2d.mix.base import MixAugmentationBase, MixAugmentationBaseV2
  File "D:\sd\venv\lib\site-packages\kornia\augmentation\_2d\mix\base.py", line 10, in <module>
    from kornia.geometry.boxes import Boxes
  File "D:\sd\venv\lib\site-packages\kornia\geometry\boxes.py", line 582, in <module>
    class Boxes3D:
  File "D:\sd\venv\lib\site-packages\torch\jit\_script.py", line 1323, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "D:\sd\venv\lib\site-packages\torch\jit\_recursive.py", line 47, in _compile_and_register_class
    script_class = torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
  File "D:\sd\venv\lib\site-packages\torch\jit\_recursive.py", line 863, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "D:\sd\venv\lib\site-packages\torch\jit\_script.py", line 1343, in script
    fn = torch._C._jit_script_compile(
  File "D:\sd\venv\lib\site-packages\torch\jit\_recursive.py", line 863, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "D:\sd\venv\lib\site-packages\torch\jit\_script.py", line 1343, in script
    fn = torch._C._jit_script_compile(
  File "D:\sd\venv\lib\site-packages\torch\jit\_recursive.py", line 863, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "D:\sd\venv\lib\site-packages\torch\jit\_script.py", line 1343, in script
    fn = torch._C._jit_script_compile(
  File "D:\sd\venv\lib\site-packages\torch\jit\_recursive.py", line 863, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "D:\sd\venv\lib\site-packages\torch\jit\_script.py", line 1343, in script
    fn = torch._C._jit_script_compile(
RuntimeError:

aten::pad(Tensor self, int[] pad, str mode="constant", float? value=None) -> Tensor:
Expected a value of type 'List[int]' for argument 'pad' but instead found type 'Tensor (inferred)'.
Inferred the value for argument 'pad' to be of type 'Tensor' because it was not annotated with an explicit type.
:
  File "D:\sd\modules\devices.py", line 243
def pad(input, pad, mode='constant', value=None):
    if input.dtype == torch.float16 and input.device.type == 'privateuseone':
        return _pad(input.float(), pad, mode, value).type(input.dtype)
               ~~~~ <--- HERE
    else:
        return _pad(input, pad, mode, value)
'pad' is being compiled since it was called from 'convert_points_to_homogeneous'
  File "D:\sd\venv\lib\site-packages\kornia\geometry\conversions.py", line 199
        raise ValueError(f"Input must be at least a 2D tensor. Got {points.shape}")

    return torch.nn.functional.pad(points, [0, 1], "constant", 1.0)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
'convert_points_to_homogeneous' is being compiled since it was called from 'transform_points'
  File "D:\sd\venv\lib\site-packages\kornia\geometry\linalg.py", line 189
    trans_01 = torch.repeat_interleave(trans_01, repeats=points_1.shape[0] // trans_01.shape[0], dim=0)
    # to homogeneous
    points_1_h = convert_points_to_homogeneous(points_1)  # BxNxD+1
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    # transform coordinates
    points_0_h = torch.bmm(points_1_h, trans_01.permute(0, 2, 1))
'transform_points' is being compiled since it was called from '_transform_boxes'
  File "D:\sd\venv\lib\site-packages\kornia\geometry\boxes.py", line 53
        )

    transformed_boxes: torch.Tensor = transform_points(M, points)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    transformed_boxes = transformed_boxes.view_as(boxes)
    return transformed_boxes
'_transform_boxes' is being compiled since it was called from 'Boxes3D.transform_boxes'
  File "D:\sd\venv\lib\site-packages\kornia\geometry\boxes.py", line 897
        # Due to some torch.jit.script bug (at least <= 1.9), you need to pass all arguments to __init__ when
        # constructing the class from inside of a method.
        transformed_boxes = _transform_boxes(self._data, M)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        if inplace:
            self._data = transformed_boxes

Press any key to continue . . .

### Steps to reproduce the problem

1. Git pull and pull in all repositories as per the requirements
2. launch the webui-user.bat
3. Error


### What should have happened?

Webui launches without crashing

### Version or Commit where the problem happens

commit ee3d3904c327031ed193a1e6d8472c3eed9409c7 (HEAD -> master, origin/master, origin/HEAD) Author: Aloereed <58137529+Aloereed@users.noreply.github.com> Date:   Sat Mar 25 14:30:47 2023 +0800

### What Python version are you running on ?

Python 3.10.x

### What platforms do you use to access the UI ?

Windows

### What device are you running WebUI on?

Intel ARC GPUs

### Cross attention optimization

None 

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
Launching Web UI with arguments: --opt-sub-quad-attention --disable-nan-check
```


### List of extensions

Default, installed none

### Console logs

```Shell
D:\sd>webui-user.bat
venv "D:\sd\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: ee3d3904c327031ed193a1e6d8472c3eed9409c7
Installing requirements for Web UI
Launching Web UI with arguments: --opt-sub-quad-attention --disable-nan-check
Thank you for helping to bring diversity to the graphics card market.
Disabled experimental graphic memory optimizations.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
Traceback (most recent call last):
  File "D:\sd\launch.py", line 353, in <module>
    start()
  File "D:\sd\launch.py", line 344, in start
    import webui
  File "D:\sd\webui.py", line 15, in <module>
    from modules import import_hook, errors, extra_networks, ui_extra_networks_checkpoints
  File "D:\sd\modules\ui_extra_networks_checkpoints.py", line 6, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "D:\sd\modules\sd_models.py", line 15, in <module>
    from modules import paths, shared, modelloader, devices, script_callbacks, sd_vae, sd_disable_initialization, errors, hashes, sd_models_config
  File "D:\sd\modules\sd_disable_initialization.py", line 1, in <module>
    import ldm.modules.encoders.modules
  File "D:\sd\repositories\stable-diffusion-stability-ai\ldm\modules\encoders\modules.py", line 3, in <module>
    import kornia
  File "D:\sd\venv\lib\site-packages\kornia\__init__.py", line 11, in <module>
    from . import augmentation, color, contrib, core, enhance, feature, io, losses, metrics, morphology, tracking, utils, x
  File "D:\sd\venv\lib\site-packages\kornia\augmentation\__init__.py", line 1, in <module>
    from kornia.augmentation._2d import (
  File "D:\sd\venv\lib\site-packages\kornia\augmentation\_2d\__init__.py", line 3, in <module>
    from kornia.augmentation._2d.mix import *
  File "D:\sd\venv\lib\site-packages\kornia\augmentation\_2d\mix\__init__.py", line 1, in <module>
    from kornia.augmentation._2d.mix.cutmix import RandomCutMix, RandomCutMixV2
  File "D:\sd\venv\lib\site-packages\kornia\augmentation\_2d\mix\cutmix.py", line 7, in <module>
    from kornia.augmentation._2d.mix.base import MixAugmentationBase, MixAugmentationBaseV2
  File "D:\sd\venv\lib\site-packages\kornia\augmentation\_2d\mix\base.py", line 10, in <module>
    from kornia.geometry.boxes import Boxes
  File "D:\sd\venv\lib\site-packages\kornia\geometry\boxes.py", line 582, in <module>
    class Boxes3D:
  File "D:\sd\venv\lib\site-packages\torch\jit\_script.py", line 1323, in script
    _compile_and_register_class(obj, _rcb, qualified_name)
  File "D:\sd\venv\lib\site-packages\torch\jit\_recursive.py", line 47, in _compile_and_register_class
    script_class = torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
  File "D:\sd\venv\lib\site-packages\torch\jit\_recursive.py", line 863, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "D:\sd\venv\lib\site-packages\torch\jit\_script.py", line 1343, in script
    fn = torch._C._jit_script_compile(
  File "D:\sd\venv\lib\site-packages\torch\jit\_recursive.py", line 863, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "D:\sd\venv\lib\site-packages\torch\jit\_script.py", line 1343, in script
    fn = torch._C._jit_script_compile(
  File "D:\sd\venv\lib\site-packages\torch\jit\_recursive.py", line 863, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "D:\sd\venv\lib\site-packages\torch\jit\_script.py", line 1343, in script
    fn = torch._C._jit_script_compile(
  File "D:\sd\venv\lib\site-packages\torch\jit\_recursive.py", line 863, in try_compile_fn
    return torch.jit.script(fn, _rcb=rcb)
  File "D:\sd\venv\lib\site-packages\torch\jit\_script.py", line 1343, in script
    fn = torch._C._jit_script_compile(
RuntimeError:

aten::pad(Tensor self, int[] pad, str mode="constant", float? value=None) -> Tensor:
Expected a value of type 'List[int]' for argument 'pad' but instead found type 'Tensor (inferred)'.
Inferred the value for argument 'pad' to be of type 'Tensor' because it was not annotated with an explicit type.
:
  File "D:\sd\modules\devices.py", line 243
def pad(input, pad, mode='constant', value=None):
    if input.dtype == torch.float16 and input.device.type == 'privateuseone':
        return _pad(input.float(), pad, mode, value).type(input.dtype)
               ~~~~ <--- HERE
    else:
        return _pad(input, pad, mode, value)
'pad' is being compiled since it was called from 'convert_points_to_homogeneous'
  File "D:\sd\venv\lib\site-packages\kornia\geometry\conversions.py", line 199
        raise ValueError(f"Input must be at least a 2D tensor. Got {points.shape}")

    return torch.nn.functional.pad(points, [0, 1], "constant", 1.0)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
'convert_points_to_homogeneous' is being compiled since it was called from 'transform_points'
  File "D:\sd\venv\lib\site-packages\kornia\geometry\linalg.py", line 189
    trans_01 = torch.repeat_interleave(trans_01, repeats=points_1.shape[0] // trans_01.shape[0], dim=0)
    # to homogeneous
    points_1_h = convert_points_to_homogeneous(points_1)  # BxNxD+1
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    # transform coordinates
    points_0_h = torch.bmm(points_1_h, trans_01.permute(0, 2, 1))
'transform_points' is being compiled since it was called from '_transform_boxes'
  File "D:\sd\venv\lib\site-packages\kornia\geometry\boxes.py", line 53
        )

    transformed_boxes: torch.Tensor = transform_points(M, points)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    transformed_boxes = transformed_boxes.view_as(boxes)
    return transformed_boxes
'_transform_boxes' is being compiled since it was called from 'Boxes3D.transform_boxes'
  File "D:\sd\venv\lib\site-packages\kornia\geometry\boxes.py", line 897
        # Due to some torch.jit.script bug (at least <= 1.9), you need to pass all arguments to __init__ when
        # constructing the class from inside of a method.
        transformed_boxes = _transform_boxes(self._data, M)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        if inplace:
            self._data = transformed_boxes

Press any key to continue . . .

D:\sd>webui-user.bat
venv "D:\sd\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: ee3d3904c327031ed193a1e6d8472c3eed9409c7
Installing requirements for Web UI
Traceback (most recent call last):
  File "D:\sd\launch.py", line 352, in <module>
    prepare_environment()
  File "D:\sd\launch.py", line 303, in prepare_environment
    run_pip(f"install -r {requirements_file}", "requirements for Web UI")
  File "D:\sd\launch.py", line 137, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "D:\sd\launch.py", line 95, in run
    result = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, shell=True, env=os.environ if custom_env is None else custom_env)
  File "C:\Users\timln\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 505, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "C:\Users\timln\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1154, in communicate
    stdout, stderr = self._communicate(input, endtime, timeout)
  File "C:\Users\timln\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1528, in _communicate
    self.stdout_thread.join(self._remaining_time(endtime))
  File "C:\Users\timln\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1096, in join
    self._wait_for_tstate_lock()
  File "C:\Users\timln\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1116, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
KeyboardInterrupt
^CTerminate batch job (Y/N)? y

D:\sd>git pull
Already up to date.

D:\sd>Warning: caught exception 'Torch not compiled with CUDA enabled', memg
'Warning:' is not recognized as an internal or external command,
operable program or batch file.

D:\sd>git log
commit ee3d3904c327031ed193a1e6d8472c3eed9409c7 (HEAD -> master, origin/master, origin/HEAD)
Author: Aloereed <58137529+Aloereed@users.noreply.github.com>
Date:   Sat Mar 25 14:30:47 2023 +0800

    Update README_ZH.md

commit addf81e32deed6909afbedcb94f295a5ce0c371a
Author: Aloereed <58137529+Aloereed@users.noreply.github.com>
Date:   Sat Mar 25 14:29:48 2023 +0800

    Update README.md

commit ce527204a1bcc424ebae8442498482b276da5900
Author: Aloereed <58137529+Aloereed@users.noreply.github.com>
Date:   Thu Feb 23 11:48:36 2023 +0800

    Update webui-user.bat

commit 815c225e0a4f6eb2d83edf2f407c49b451b034dd
Author: Aloereed <58137529+Aloereed@users.noreply.github.com>
Date:   Thu Feb 23 11:48:25 2023 +0800

    Update webui-user.bat

commit e38a1cacb5e848c731f45f7b757f070d13394e38
Author: Aloereed <58137529+Aloereed@users.noreply.github.com>
Date:   Tue Feb 21 14:21:17 2023 +0800

    Update README_ZH.md
```


### Additional information

_No response_

**Comment by lshqqytiger** [comment]
25 Mar? I pushed some commits yesterday. If you don't know which repo/tree you are, re-clone and try again.
