### ISSUE TITLE
 [Bug]: web ui找不到存储库

### ISSUE THREAD

**Issue by lulvya** [lshqqytiger/stable-diffusion-webui-directml#26]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

venv "D:\aihuihua\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Commit hash: 3e8555242836192c9e3e79c91962418e1f51d5d6
Installing requirements for Web UI
Launching Web UI with arguments:
Traceback (most recent call last):
  File "D:\aihuihua\stable-diffusion-webui-directml\launch.py", line 360, in <module>
    start()
  File "D:\aihuihua\stable-diffusion-webui-directml\launch.py", line 351, in start
    import webui
  File "D:\aihuihua\stable-diffusion-webui-directml\webui.py", line 15, in <module>
    from modules import import_hook, errors, extra_networks, ui_extra_networks_checkpoints
  File "D:\aihuihua\stable-diffusion-webui-directml\modules\ui_extra_networks_checkpoints.py", line 6, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "D:\aihuihua\stable-diffusion-webui-directml\modules\shared.py", line 12, in <module>
    import modules.interrogate
  File "D:\aihuihua\stable-diffusion-webui-directml\modules\interrogate.py", line 15, in <module>
    from modules import devices, paths, shared, lowvram, modelloader, errors
  File "D:\aihuihua\stable-diffusion-webui-directml\modules\paths.py", line 26, in <module>
    assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_sd_paths)
AssertionError: Couldn't find Stable Diffusion in any of: ['D:\\aihuihua\\stable-diffusion-webui-directml\\repositories/stable-diffusion-stability-ai', '.', 'D:\\aihuihua']

### Steps to reproduce the problem

1. 运行webui.bat

### What should have happened?

出现本地网址

### Commit where the problem happens

Traceback (most recent call last):   File "D:\aihuihua\stable-diffusion-webui-directml\launch.py", line 360, in <module>     start()   File "D:\aihuihua\stable-diffusion-webui-directml\launch.py", line 351, in start     import webui   File "D:\aihuihua\stable-diffusion-webui-directml\webui.py", line 15, in <module>     from modules import import_hook, errors, extra_networks, ui_extra_networks_checkpoints   File "D:\aihuihua\stable-diffusion-webui-directml\modules\ui_extra_networks_checkpoints.py", line 6, in <module>     from modules import shared, ui_extra_networks, sd_models   File "D:\aihuihua\stable-diffusion-webui-directml\modules\shared.py", line 12, in <module>     import modules.interrogate   File "D:\aihuihua\stable-diffusion-webui-directml\modules\interrogate.py", line 15, in <module>     from modules import devices, paths, shared, lowvram, modelloader, errors   File "D:\aihuihua\stable-diffusion-webui-directml\modules\paths.py", line 26, in <module>     assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_sd_paths) AssertionError: Couldn't find Stable Diffusion in

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
否
```

### List of extensions

否

### Console logs

```Shell
Traceback (most recent call last):
  File "D:\aihuihua\stable-diffusion-webui-directml\launch.py", line 360, in <module>
    start()
  File "D:\aihuihua\stable-diffusion-webui-directml\launch.py", line 351, in start
    import webui
  File "D:\aihuihua\stable-diffusion-webui-directml\webui.py", line 15, in <module>
    from modules import import_hook, errors, extra_networks, ui_extra_networks_checkpoints
  File "D:\aihuihua\stable-diffusion-webui-directml\modules\ui_extra_networks_checkpoints.py", line 6, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "D:\aihuihua\stable-diffusion-webui-directml\modules\shared.py", line 12, in <module>
    import modules.interrogate
  File "D:\aihuihua\stable-diffusion-webui-directml\modules\interrogate.py", line 15, in <module>
    from modules import devices, paths, shared, lowvram, modelloader, errors
  File "D:\aihuihua\stable-diffusion-webui-directml\modules\paths.py", line 26, in <module>
    assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_sd_paths)
AssertionError: Couldn't find Stable Diffusion in any of: ['D:\\aihuihua\\stable-diffusion-webui-directml\\repositories/stable-diffusion-stability-ai', '.', 'D:\\aihuihua']
```

**Comment by ClashSAN** [comment]
you would need to follow installation: git clone https://github.com/lshqqytiger/stable-diffusion-webui-directml && cd stable-diffusion-webui-directml && git submodule init && git submodule update


on > https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs

**Comment by lulvya** [comment]
venv "D:\aihuihua\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Commit hash: 3e8555242836192c9e3e79c91962418e1f51d5d6
Installing requirements for Web UI
Launching Web UI with arguments:
Interrogations are fallen back to cpu. This doesn't affect on image generation. But if you want to use interrogate (CLIP or DeepBooru), check out this issue: https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/10
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
Loading weights [6ce0161689] from D:\aihuihua\stable-diffusion-webui-directml\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: D:\aihuihua\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (InvokeAI).
Textual inversion embeddings loaded(0):
Model loaded in 3.1s (create model: 0.5s, apply weights to model: 1.0s, apply half(): 0.7s, move model to device: 0.9s).
Traceback (most recent call last):
  File "D:\aihuihua\stable-diffusion-webui-directml\launch.py", line 360, in <module>
    start()
  File "D:\aihuihua\stable-diffusion-webui-directml\launch.py", line 355, in start
    webui.webui()
  File "D:\aihuihua\stable-diffusion-webui-directml\webui.py", line 218, in webui
    app, local_url, share_url = shared.demo.launch(
  File "D:\aihuihua\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 1418, in launch
    raise ValueError(
ValueError: When localhost is not accessible, a shareable link must be created. Please set share=True.
请按任意键继续. . .

又出现这个问题
