### ISSUE TITLE
[Bug]: RuntimeError: The GPU device does not support Double (Float64) operations!

### ISSUE THREAD

**Issue by StudioDUzes** [lshqqytiger/stable-diffusion-webui-directml#269]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Hello, there were some problems since version 1.6, but this morning after an update it was impossible to generate a simple text2img: 

RuntimeError: The GPU device does not support Double (Float64) operations!

### Steps to reproduce the problem

1. text2img
2. generate
3. RuntimeError: The GPU device does not support Double (Float64) operations!

### What should have happened?

generate

### Sysinfo

[sysinfo-2023-09-09-07-24.txt](https://github.com/lshqqytiger/stable-diffusion-webui-directml/files/12565210/sysinfo-2023-09-09-07-24.txt)

### What browsers do you use to access the UI ?

Google Chrome

### Console logs

```Shell
Already up to date.
venv "N:\1.6\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.6.0
Commit hash: 92849df26f73b416d396b95c3fb8c64070fe3ad8
Launching Web UI with arguments: --device-id 1 --port 7861 --medvram --always-batch-cond-uncond --upcast-sampling --precision full --no-half-vae --disable-nan-check --use-cpu interrogate codeformer --api --autolaunch
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Warning: caught exception 'Something went wrong.', memory monitor disabled
Loading weights [31e35c80fc] from N:\1.6\stable-diffusion-webui-directml\models\Stable-diffusion\SDXL\sd_xl_base_1.0.safetensors
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
Startup time: 7.7s (prepare environment: 0.3s, import torch: 2.9s, import gradio: 1.0s, setup paths: 0.5s, initialize shared: 1.1s, other imports: 0.2s, load scripts: 1.0s, create ui: 0.3s, gradio launch: 0.3s).
Creating model from config: N:\1.6\stable-diffusion-webui-directml\repositories\generative-models\configs\inference\sd_xl_base.yaml
Applying attention optimization: sdp... done.
Model loaded in 8.3s (load weights from disk: 2.9s, create model: 0.9s, apply weights to model: 1.3s, calculate empty prompt: 3.1s).
*** Error completing request
*** Arguments: ('task(sx9j1d6hakx7adh)', 'https://github.com/lshqqytiger/stable-diffusion-webui-directml', '', [], 20, 'DPM++ 2M Karras', 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x000001E8591B2FB0>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "N:\1.6\stable-diffusion-webui-directml\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "N:\1.6\stable-diffusion-webui-directml\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "N:\1.6\stable-diffusion-webui-directml\modules\txt2img.py", line 64, in txt2img
        processed = processing.process_images(p)
      File "N:\1.6\stable-diffusion-webui-directml\modules\processing.py", line 733, in process_images
        res = process_images_inner(p)
      File "N:\1.6\stable-diffusion-webui-directml\modules\processing.py", line 871, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "N:\1.6\stable-diffusion-webui-directml\modules\processing.py", line 1144, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "N:\1.6\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 201, in sample
        sigmas = self.get_sigmas(p, steps)
      File "N:\1.6\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 128, in get_sigmas
        self.model_wrap.sigmas.__str__() # DML stringify
      File "N:\1.6\stable-diffusion-webui-directml\venv\lib\site-packages\torch\_tensor.py", line 426, in __repr__
        return torch._tensor_str._str(self, tensor_contents=tensor_contents)
      File "N:\1.6\stable-diffusion-webui-directml\venv\lib\site-packages\torch\_tensor_str.py", line 636, in _str
        return _str_intern(self, tensor_contents=tensor_contents)
      File "N:\1.6\stable-diffusion-webui-directml\venv\lib\site-packages\torch\_tensor_str.py", line 567, in _str_intern
        tensor_str = _tensor_str(self, indent)
      File "N:\1.6\stable-diffusion-webui-directml\venv\lib\site-packages\torch\_tensor_str.py", line 327, in _tensor_str
        formatter = _Formatter(get_summarized_data(self) if summarize else self)
      File "N:\1.6\stable-diffusion-webui-directml\venv\lib\site-packages\torch\_tensor_str.py", line 124, in __init__
        nonzero_finite_abs = tensor_totype(nonzero_finite_vals.abs())
      File "N:\1.6\stable-diffusion-webui-directml\venv\lib\site-packages\torch\_tensor_str.py", line 96, in tensor_totype
        return t.to(dtype=dtype)
    RuntimeError: The GPU device does not support Double (Float64) operations!

---
*** Error completing request
*** Arguments: ('task(oasu5j24iv9fz1f)', 'https://github.com/lshqqytiger/stable-diffusion-webui-directml', '', [], 20, 'DPM++ 2M Karras', 1, 1, 7, 1024, 1024, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x000001E88B524DC0>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "N:\1.6\stable-diffusion-webui-directml\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "N:\1.6\stable-diffusion-webui-directml\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "N:\1.6\stable-diffusion-webui-directml\modules\txt2img.py", line 64, in txt2img
        processed = processing.process_images(p)
      File "N:\1.6\stable-diffusion-webui-directml\modules\processing.py", line 733, in process_images
        res = process_images_inner(p)
      File "N:\1.6\stable-diffusion-webui-directml\modules\processing.py", line 871, in process_images_inner
        samples_ddim = p.sample(conditioning=p.c, unconditional_conditioning=p.uc, seeds=p.seeds, subseeds=p.subseeds, subseed_strength=p.subseed_strength, prompts=p.prompts)
      File "N:\1.6\stable-diffusion-webui-directml\modules\processing.py", line 1144, in sample
        samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
      File "N:\1.6\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 201, in sample
        sigmas = self.get_sigmas(p, steps)
      File "N:\1.6\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 128, in get_sigmas
        self.model_wrap.sigmas.__str__() # DML stringify
      File "N:\1.6\stable-diffusion-webui-directml\venv\lib\site-packages\torch\_tensor.py", line 426, in __repr__
        return torch._tensor_str._str(self, tensor_contents=tensor_contents)
      File "N:\1.6\stable-diffusion-webui-directml\venv\lib\site-packages\torch\_tensor_str.py", line 636, in _str
        return _str_intern(self, tensor_contents=tensor_contents)
      File "N:\1.6\stable-diffusion-webui-directml\venv\lib\site-packages\torch\_tensor_str.py", line 567, in _str_intern
        tensor_str = _tensor_str(self, indent)
      File "N:\1.6\stable-diffusion-webui-directml\venv\lib\site-packages\torch\_tensor_str.py", line 327, in _tensor_str
        formatter = _Formatter(get_summarized_data(self) if summarize else self)
      File "N:\1.6\stable-diffusion-webui-directml\venv\lib\site-packages\torch\_tensor_str.py", line 124, in __init__
        nonzero_finite_abs = tensor_totype(nonzero_finite_vals.abs())
      File "N:\1.6\stable-diffusion-webui-directml\venv\lib\site-packages\torch\_tensor_str.py", line 96, in tensor_totype
        return t.to(dtype=dtype)
    RuntimeError: The GPU device does not support Double (Float64) operations!

---
```

### Additional information

GPU INTEL ARC a770 16 go

**Comment by lshqqytiger** [comment]
May be fixed in deb4ac6ae92c562492cc7aa1b95aa17e496d1000. But it may occur [terminal hang up issue](https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/260) because current known solution requires float64 operation (stringify).

**Comment by StudioDUzes** [comment]
Thank you, text2img work with update...

**Comment by StudioDUzes** [comment]
disabled  "Cache cond persistant" is better for inpainting and other operation
