### ISSUE TITLE
[Bug]: VRAM fills up and stays at 100% all the time

### ISSUE THREAD

**Issue by el-ef** [lshqqytiger/stable-diffusion-webui-directml#27]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Hey there,

I have serious issues running the program on Windows 11 with an AMD 6900XT.
As soon as I start the rendering the process I can see the dedicated memory usage in GPU-Z climbing up from 4.4 GB idle (WebUI launched, doing nothing) to the maximum of 16 GB. After a few seconds the rendering fails.

`
RuntimeError: Could not allocate tensor with 4719616 bytes. There is not enough GPU video memory available!`

The issue occurs at default settings, 512x512px. Once the VRAM is full it stays at 100% until I exit the cmd.
I have tried every ARGS-command suggested over at [Windows + AMD GPUs (DirectML) #7870](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/7870). No success.

### Steps to reproduce the problem

Install on W11 machine following the guide.
Run the UI and a test prompt @ 512px @ default settings.

### What should have happened?

Render an image.

### Commit where the problem happens

3e855524

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
Everything from "--opt-split-attention-v1 --opt-sub-quad-attention --always-batch-cond-uncond --disable-nan-check --sub-quad-kv-chunk-size 512 --sub-quad-q-chunk-size 512 --sub-quad-chunk-threshold 25 --no-half --no-half-vae --precision full --medvram" to nothing.
```

### List of extensions

No

### Console logs

```Shell
venv "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Commit hash: 3e8555242836192c9e3e79c91962418e1f51d5d6
Installing requirements for Web UI
Launching Web UI with arguments:
Interrogations are fallen back to cpu. This doesn't affect on image generation. But if you want to use interrogate (CLIP or DeepBooru), check out this issue: https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/10
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
Loading weights [88ecb78256] from C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\models\Stable-diffusion\v2-1_512-ema-pruned.ckpt
Creating model from config: C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\models\Stable-diffusion\v2-1_512-ema-pruned.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 865.91 M params.
Applying cross attention optimization (InvokeAI).
Textual inversion embeddings loaded(0):
Model loaded in 5.7s (load weights from disk: 0.9s, create model: 0.1s, apply weights to model: 0.6s, apply half(): 0.6s, move model to device: 3.5s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\venv\lib\site-packages\torch\amp\autocast_mode.py:202: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py:63: UserWarning: The operator 'aten::linspace.out' is not currently supported on the DML backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at D:\a\_work\1\s\pytorch-directml-plugin\torch_directml\csrc\dml\dml_cpu_fallback.cpp:17.)
  t = torch.linspace(t_max, 0, n, device=self.sigmas.device)
 30%|██████████████████████████████▌                                                                       | 6/20 [00:29<01:07,  4.85s/it]
Error completing request██████████████████████▊                                                            | 6/20 [00:21<01:03,  4.54s/it]
Arguments: ('task(2xnvnyshi5wky2r)', 'test', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\modules\processing.py", line 632, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\modules\processing.py", line 832, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 349, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 225, in launch_sampling
    return func()
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 349, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\sampling.py", line 150, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 117, in forward
    x_out = self.inner_model(x_in, sigma_in, cond={"c_crossattn": [cond_in], "c_concat": [image_cond_in]})
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 138, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1335, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 783, in forward
    h = module(h, emb, context)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 84, in forward
    x = layer(x, context)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 334, in forward
    x = block(x, context=context[i])
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 269, in forward
    return checkpoint(self._forward, (x, context), self.parameters(), self.checkpoint)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 114, in checkpoint
    return CheckpointFunction.apply(func, len(inputs), *args)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 129, in forward
    output_tensors = ctx.run_function(*ctx.input_tensors)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\attention.py", line 272, in _forward
    x = self.attn1(self.norm1(x), context=context if self.disable_self_attn else None) + x
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\modules\sd_hijack_optimizations.py", line 246, in split_cross_attention_forward_invokeAI
    r = einsum_op(q, k, v)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\modules\sd_hijack_optimizations.py", line 221, in einsum_op
    return einsum_op_dml(q, k, v)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\modules\sd_hijack_optimizations.py", line 209, in einsum_op_dml
    return einsum_op_tensor_mem(q, k, v, (mem_reserved - mem_active) if mem_reserved > mem_active else 1)
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\modules\sd_hijack_optimizations.py", line 194, in einsum_op_tensor_mem
    return einsum_op_slice_1(q, k, v, max(q.shape[1] // div, 1))
  File "C:\stable-diffusion-webui-directml\stable-diffusion-webui-directml\modules\sd_hijack_optimizations.py", line 169, in einsum_op_slice_1
    r[:, i:end] = einsum_op_compvis(q[:, i:end], k, v)
RuntimeError: Could not allocate tensor with 4719616 bytes. There is not enough GPU video memory available!
```

### Additional information

Thank you for taking the effort to host this project! Seriously. We need more supporters like you! :)

**Comment by el-ef** [comment]
Issue fixed!

-> reinstalled the whole project (including Python)
-> reboot

Sorry for the ticket!

**Comment by sooxt98** [comment]
@el-ef Im getting this same error after fews batches are generated on my 6600 XT, i just freshly installed this project tho. Seems like the memory doesn't get free after single batch done, or maybe some sort of memory leaks?

**Comment by el-ef** [comment]
@sooxt98 No idea, tbh. I just realized that the Web UI runs much much more stable on Linux with the 6900 XT. Haven't had any memory issues since then. With the Windows install I can only do 512x512px. Everything else fails due to memory limitations. That is not the case on Linux.
I think that the DirectML attempt is simply not hardened enough, yet. I will stay on Linux for a while now since it is also much more superior in terms of rendering speed.

From fastest to slowest:
- Linux AUTOMATIC1111
- Linux nod.ai Shark
- Windows nod.ai Shark
- Windows AUTOMATIC1111 + DirectML

**Comment by lshqqytiger** [comment]
Being able to access ROCm is very important. So far, DirectML can't replace ROCm due to its poor memory optimization and slower speed.
