### ISSUE TITLE
[Bug]: Can not finish generating an image on my 6900xt

### ISSUE THREAD

**Issue by GitGudGandalf** [lshqqytiger/stable-diffusion-webui-directml#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

On my 6900xt after following the installation guide above, i cant seem to finish generating a 512x512 image.

even with the parameter -opt-split-attention-v1

I get to the final step then i receive the following error:

NotImplementedError: No operator found for memory_efficient_attention_forward with inputs:
query : shape=(1, 4096, 1, 512) (torch.float16)
key : shape=(1, 4096, 1, 512) (torch.float16)
value : shape=(1, 4096, 1, 512) (torch.float16)
attn_bias : <class 'NoneType'>
p : 0.0
cutlassF is not supported because:
device=privateuseone (supported: {'cuda'})
flshattF is not supported because:
device=privateuseone (supported: {'cuda'})
max(query.shape[-1] != value.shape[-1]) > 128
tritonflashattF is not supported because:
device=privateuseone (supported: {'cuda'})
max(query.shape[-1] != value.shape[-1]) > 128
triton is not available
smallkF is not supported because:
device=privateuseone (supported: {'cuda', 'cpu'})
dtype=torch.float16 (supported: {torch.float32})
max(query.shape[-1] != value.shape[-1]) > 32
unsupported embed per head: 512

the folder outputs does not even get created. it just fails there.

The image generation process is working tho, as I can see the previews of the steps running in the interface.

### Steps to reproduce the problem

1. Go to [stable-diffusion-webui-directml](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs)
2. follow instructions to install on AMD machines
3. Run webui-user.bat
4. Open the browser interface, write any prompt and hit generate.
At step 20/20 the error comes out.

### What should have happened?

The image should have finished generating, an outputs folder should have been created and the image sxhould have been saved there.

### Commit where the problem happens

Commit hash: 3e8555242836192c9e3e79c91962418e1f51d5d6

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--xformers --opt-split-attention-v1

call webui.bat
```

### List of extensions

no

### Console logs

```Shell
venv "C:\Users\xxxxx\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 3e8555242836192c9e3e79c91962418e1f51d5d6
Installing requirements for Web UI
Launching Web UI with arguments: --xformers --opt-split-attention-v1
Interrogations are fallen back to cpu. This doesn't affect on image generation. But if you want to use interrogate (CLIP or DeepBooru), check out this issue: https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/10
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 1.13.1+cu117 with CUDA 1107 (you have 1.13.1+cpu)
    Python  3.10.9 (you have 3.10.6)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Loading weights [c35782bad8] from C:\Users\xxxxx\stable-diffusion-webui-directml\models\Stable-diffusion\realisticVisionV13_v13.safetensors
Creating model from config: C:\Users\xxxxx\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying v1 cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 4.0s (load weights from disk: 0.2s, create model: 0.5s, apply weights to model: 1.6s, apply half(): 0.7s, move model to device: 1.0s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:08<00:00,  2.43it/s]
Error completing request███████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.40it/s]
Arguments: ('task(ywze92bbldj89a2)', 'cute cat', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "C:\Users\xxxxx\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\xxxxx\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\xxxxx\stable-diffusion-webui-directml\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "C:\Users\xxxxx\stable-diffusion-webui-directml\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "C:\Users\xxxxx\stable-diffusion-webui-directml\modules\processing.py", line 634, in process_images_inner
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "C:\Users\xxxxx\stable-diffusion-webui-directml\modules\processing.py", line 634, in <listcomp>
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "C:\Users\xxxxx\stable-diffusion-webui-directml\modules\processing.py", line 423, in decode_first_stage
    x = model.decode_first_stage(x)
  File "C:\Users\xxxxx\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\Users\xxxxx\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "C:\Users\xxxxx\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\xxxxx\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 826, in decode_first_stage
    return self.first_stage_model.decode(z)
  File "C:\Users\xxxxx\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 90, in decode
    dec = self.decoder(z)
  File "C:\Users\xxxxx\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\xxxxx\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 631, in forward
    h = self.mid.attn_1(h)
  File "C:\Users\xxxxx\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\xxxxx\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 258, in forward
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None, op=self.attention_op)
  File "C:\Users\xxxxx\stable-diffusion-webui-directml\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 197, in memory_efficient_attention
    return _memory_efficient_attention(
  File "C:\Users\xxxxx\stable-diffusion-webui-directml\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 293, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "C:\Users\xxxxx\stable-diffusion-webui-directml\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 309, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp)
  File "C:\Users\xxxxx\stable-diffusion-webui-directml\venv\lib\site-packages\xformers\ops\fmha\dispatch.py", line 95, in _dispatch_fw
    return _run_priority_list(
  File "C:\Users\xxxxx\stable-diffusion-webui-directml\venv\lib\site-packages\xformers\ops\fmha\dispatch.py", line 70, in _run_priority_list
    raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 4096, 1, 512) (torch.float16)
     key         : shape=(1, 4096, 1, 512) (torch.float16)
     value       : shape=(1, 4096, 1, 512) (torch.float16)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`cutlassF` is not supported because:
    device=privateuseone (supported: {'cuda'})
`flshattF` is not supported because:
    device=privateuseone (supported: {'cuda'})
    max(query.shape[-1] != value.shape[-1]) > 128
`tritonflashattF` is not supported because:
    device=privateuseone (supported: {'cuda'})
    max(query.shape[-1] != value.shape[-1]) > 128
    triton is not available
`smallkF` is not supported because:
    device=privateuseone (supported: {'cuda', 'cpu'})
    dtype=torch.float16 (supported: {torch.float32})
    max(query.shape[-1] != value.shape[-1]) > 32
    unsupported embed per head: 512
```

**Comment by Miraihi** [comment]
You can't use xformers on an AMD card.

**Comment by GitGudGandalf** [comment]
Thank you!
