### ISSUE TITLE
[Bug]: Deforum 3D mode not working on AMD card

### ISSUE THREAD

**Issue by RBR8man** [lshqqytiger/stable-diffusion-webui-directml#29]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Tried to use the 3D animation mode in the latest Deforum release and Stable Diffusion returns this error
![image](https://user-images.githubusercontent.com/126144408/222979895-d389b383-b26c-45e3-8580-7c50156c7417.png)

### Steps to reproduce the problem

1. go to the Deforum tab
2. select the 3D option
3. enter all your prompts and such
4. click generate

### What should have happened?

Generation should have continued as normal

### Commit where the problem happens

https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/ff558348682fea569785dcfae1f1282cfbefda6b

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--autolaunch --opt-split-attention
```

### List of extensions

Deforum
Controlnet
Openposeeditor

### Console logs

```Shell
Deforum extension for auto1111 webui, v2.2b
Saving animation frames to:
J:\SDAMD\new\stable-diffusion-webui-directml\outputs/img2img-images\Deforum
Loading base model ()...Done.
Removing last two layers (global_pool & classifier).
Building Encoder-Decoder model..Done.
Animation frame: 0/10
Seed: 3151898744
Prompt: apple
Not using an init image (doing pure txt2img)
╭─────┬───┬───────┬────┬────┬────┬────┬────┬────╮
│Steps│CFG│Denoise│Tr X│Tr Y│Tr Z│Ro X│Ro Y│Ro Z│
├─────┼───┼───────┼────┼────┼────┼────┼────┼────┤
│ 25  │7.0│ None  │ 0  │ 0  │1.75│ 0  │ 0  │ 0  │
╰─────┴───┴───────┴────┴────┴────┴────┴────┴────╯
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [00:08<00:00,  3.06it/s]
Animation frame: 2/10  ██████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                                                          | 25/61 [00:07<00:11,  3.07it/s]
 Creating in-between frame: 0; tween:0.50;
Deforum progress:  41%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▉                                                                                                                                                          | 25/61 [00:09<00:13,  2.74it/s]
Error completing request
Arguments: ('task(erf15n4lnf2pha9)', None, False, '', '3D', 10, 'replicate', '0:(0)', '0:(1.0025+0.002*sin(1.25*3.14*t/30))', '0:(0)', '0:(0)', '0:(1.75)', '0:(0.5)', '0:(0.5)', '0:(0)', '0:(0)', '0:(0)', False, '0:(0)', '0:(0)', '0:(0)', '0:(53)', '0: (0.065)', '0: (0.65)', '0: (1.0)', '0: (7)', '0:(1.5)', False, '0:(1)', '0:(0)', False, '0: (25)', '0: (70)', '0: (1)', '0: (200)', '0: (10000)', '0:(5), 1:(-1), 219:(-1), 220:(5)', False, '0: ("Euler a")', '0: ("!({everywhere}^({init_mask}|{video_mask}) ) ")', False, '0: ("!({everywhere}^({init_mask}|{video_mask}) ) ")', False, '0: ("model1.ckpt"), 100: ("model2.ckpt")', False, '0: (2)', '0: (5)', '0: (1.0)', '0: (0.35)', '0: (0.0)', 'Match Frame 0 LAB', 1.0, False, '2', 'perlin', 8, 8, 4, 0.5, True, 0.2, 'border', 'bicubic', False, 'https://github.com/hithereai/d/releases/download/m/vid.mp4', 1, 0, -1, False, False, '/content/video_in.mp4', False, '20230129210106', '{\n    "0": "apple",\n \n    "60": "orange"\n}\n    ', '', '', 512, 512, False, False, -1, 'Euler a', False, 0, 0, 25, 0.0, 1, True, True, False, False, False, 'Deforum', '{timestring}_{index}_{prompt}.png', 'iter', 1, False, False, True, 0, 'https://github.com/hithereai/d/releases/download/m/kaba.png', False, False, False, True, 'https://github.com/hithereai/d/releases/download/m/mask.jpg', 1.0, 1.0, 4, 1, True, 4, 'reroll', False, 15, False, 'FFMPEG mp4', 'J:\\SDAMD\\new\\stable-diffusion-webui-directml\\venv\\lib\\site-packages\\imageio_ffmpeg\\binaries\\ffmpeg-win64-v4.2.2.exe', '17', 'slow', 'None', 'https://freetestdata.com/wp-content/uploads/2021/09/Free_Test_Data_1MB_MP3.mp3', False, 'realesr-animevideov3', 'x2', True, False, 'x0_pred', 'C:/SD/20230124234916_%05d.png', 'testvidmanualsettings.mp4', False, 'None', 2, False, 2, False, '', True, False, 'None', True, 'None', False, 'Farneback', False, 'None', False, 'None', False, False, '0:(1)', '0:(0.5)', '0:(1)', '0:(100)', '0:(0)', False, '{\n    "0": "https://user-images.githubusercontent.com/121192995/215279228-1673df8a-f919-4380-b04c-19379b2041ff.png",\n    "50": "https://user-images.githubusercontent.com/121192995/215279281-7989fd6f-4b9b-4d90-9887-b7960edd59f8.png",\n    "100": "https://user-images.githubusercontent.com/121192995/215279284-afc14543-d220-4142-bbf4-503776ca2b8b.png",\n    "150": "https://user-images.githubusercontent.com/121192995/215279286-23378635-85b3-4457-b248-23e62c048049.jpg",\n    "200": "https://user-images.githubusercontent.com/121192995/215279228-1673df8a-f919-4380-b04c-19379b2041ff.png"\n}', '0:(0.75)', '0:(0.35)', '0:(0.25)', '0:(20)', '0:(0.075)', None, None, False, False, False, False, 'none', 'None', 1, 1, 64, 64, 64, 'Scale to Fit (Inner Fit)') {}
Traceback (most recent call last):
  File "J:\SDAMD\new\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "J:\SDAMD\new\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "J:\SDAMD\new\stable-diffusion-webui-directml\extensions\deforum-for-automatic1111-webui\scripts\deforum.py", line 79, in run_deforum
    render_animation(args, anim_args, video_args, parseq_args, loop_args, controlnet_args, root.animation_prompts, root)
  File "J:\SDAMD\new\stable-diffusion-webui-directml/extensions/deforum-for-automatic1111-webui/scripts\deforum_helpers\render.py", line 234, in render_animation
    depth = depth_model.predict(turbo_next_image, anim_args.midas_weight, root.half_precision)
  File "J:\SDAMD\new\stable-diffusion-webui-directml/extensions/deforum-for-automatic1111-webui/scripts\deforum_helpers\depth.py", line 122, in predict
    midas_depth = torch.nn.functional.interpolate(
  File "J:\SDAMD\new\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\functional.py", line 3958, in interpolate
    return torch._C._nn.upsample_bicubic2d(input, output_size, align_corners, scale_factors)
RuntimeError: "compute_indices_weights_cubic" not implemented for 'Half'
```

### Additional information

my GPU is an AMD 6800 XT with the latest driver
could this perhaps be a physical limitation due to my card being AMD?
Previously asked on the main release but was told to here aswell

**Comment by lshqqytiger** [comment]
Try adding `--no-half` to commandline arguments.

**Comment by Comm0ner** [comment]
when using no half it seems to work but then after the first image its not working anymore, every 2nd image is either black or grey or some other color, some images contain parts of the prompt but are too dark and misformed to recognise. (im using latest version and updated deforum on a clean install without any settings changed) im also using an amd 6800XT .
![image_2023-05-25_182350248](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/130130912/3163e2a2-c6a8-4576-b710-875ed94a0005)

**Comment by mercurius08** [comment]
could you solve it? I have the same problem. I have a Ryzen 5950x CPU and 6800xt GPU

**Comment by mercurius08** [comment]
> 
could you solve it? I have the same problem. I have a Ryzen 5950x CPU and 6800xt GPU

**Comment by wowjustmike** [comment]
Was this ever solved? I'm on a 6700XT and have super short and simple prompts working, but as soon as I add more than 4 things in my prompt it gives me the same results as -

> (only talking about 3d mode) When using no half it seems to work but then after the first image its not working anymore, every 2nd image is either black or grey or some other color, some images contain parts of the prompt but are too dark and misformed to recognise. (im using latest version and updated deforum on a clean install without any settings changed) im also using an amd 6800XT . ![image_2023-05-25_182350248](https://user-images.githubusercontent.com/130130912/240975995-3163e2a2-c6a8-4576-b710-875ed94a0005.png)

**Comment by mercurius08** [comment]
I still haven't found a solution... I have the RX6800XT and the exact same thing happens to me

**Comment by mercurius08** [comment]
> (only talking about 3d mode) When using no half it seems to work but then after the first image its not working anymore, every 2nd image is either black or grey or some other color, some images contain parts of the prompt but are too dark and misformed to recognise. (im using latest version and updated deforum on a clean install without any settings changed) im also using an amd 6800XT . ![image_2023-05-25_182350248](https://user-images.githubusercontent.com/130130912/240975995-3163e2a2-c6a8-4576-b710-875ed94a0005.png)

I have the same error

**Comment by TheDamnedKirai** [comment]
I am actually having the exact same problem. Running 6750XT DirectML on Windows
