### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'tqdm.auto'

### ISSUE THREAD

**Issue by popsoda27** [lshqqytiger/stable-diffusion-webui-directml#293]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

UI not starting up when running webui-user.bat
Installed TemporalKit extension prior to error. Tried deleting extension and relaunching webui-user.bat.
Tried deleting venv folder and relaunching webui-user.bat.
Same error persists.

### Steps to reproduce the problem

Access ML folder.
Run webui-user.bat

### What should have happened?

UI launches as per normal.

### Sysinfo

E:\Downloads\stable-diffusion-webui-directml>webui.bat --dump-sysinfo
venv "E:\Downloads\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Traceback (most recent call last):
File "E:\Downloads\stable-diffusion-webui-directml\launch.py", line 48, in
main()
File "E:\Downloads\stable-diffusion-webui-directml\launch.py", line 29, in main
filename = launch_utils.dump_sysinfo()
File "E:\Downloads\stable-diffusion-webui-directml\modules\launch_utils.py", line 688, in dump_sysinfo
from modules import sysinfo
File "E:\Downloads\stable-diffusion-webui-directml\modules\sysinfo.py", line 13, in
from modules import paths_internal, timer, shared, extensions, errors, devices
File "E:\Downloads\stable-diffusion-webui-directml\modules\shared.py", line 3, in
import gradio as gr
File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\gradio_init_.py", line 3, in
import gradio.components as components
File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\components_init_.py", line 1, in
from gradio.components.annotated_image import AnnotatedImage
File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\components\annotated_image.py", line 8, in
from gradio_client.documentation import document, set_documentation_group
File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\gradio_client_init_.py", line 1, in
from gradio_client.client import Client
File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\gradio_client\client.py", line 24, in
from huggingface_hub import CommitOperationAdd, SpaceHardware, SpaceStage
File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub_init_.py", line 332, in getattr
submod = importlib.import_module(submod_path)
File "C:\Users\popso\AppData\Local\Programs\Python\Python310\lib\importlib_init_.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\hf_api.py", line 49, in
from tqdm.auto import tqdm as base_tqdm
ModuleNotFoundError: No module named 'tqdm.auto'
Press any key to continue . . .

### What browsers do you use to access the UI ?

Google Chrome

### Console logs

```Shell
venv "E:\Downloads\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.6.0
Commit hash: 44f1acaae3ef6868a4767eb3c89b8265664aada5
Launching Web UI with arguments: --opt-split-attention --precision full --always-batch-cond-uncond --disable-nan-check --api --medvram --no-half --no-half-vae --sub-quad-q-chunk-size 1024 --sub-quad-kv-chunk-size 256 --sub-quad-chunk-threshold 75 --use-cpu interrogate clip --no-hashing
Traceback (most recent call last):
  File "E:\Downloads\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "E:\Downloads\stable-diffusion-webui-directml\launch.py", line 44, in main
    start()
  File "E:\Downloads\stable-diffusion-webui-directml\modules\launch_utils.py", line 679, in start
    import webui
  File "E:\Downloads\stable-diffusion-webui-directml\webui.py", line 13, in <module>
    initialize.imports()
  File "E:\Downloads\stable-diffusion-webui-directml\modules\initialize.py", line 21, in imports
    import gradio  # noqa: F401
  File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\components\annotated_image.py", line 8, in <module>
    from gradio_client.documentation import document, set_documentation_group
  File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\gradio_client\__init__.py", line 1, in <module>
    from gradio_client.client import Client
  File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\gradio_client\client.py", line 24, in <module>
    from huggingface_hub import CommitOperationAdd, SpaceHardware, SpaceStage
  File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\__init__.py", line 332, in __getattr__
    submod = importlib.import_module(submod_path)
  File "C:\Users\popso\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\huggingface_hub\hf_api.py", line 49, in <module>
    from tqdm.auto import tqdm as base_tqdm
ModuleNotFoundError: No module named 'tqdm.auto'
Press any key to continue . . .
```

**Comment by popsoda27** [comment]
I tried to research further into the issue and caught some info on reddit on the same. Apparently it has to do with the Temporalkit extension needing a certain version of the tqdm module. So this is never the UI's issue so consider this closed.

I couldn't get any satisfactory resolution from reddit either, so I simply reinstalled afresh except without Temporalkit.
