### ISSUE TITLE
[Bug]: AttributeError: module 'modules.dml' has no attribute 'initialize'

### ISSUE THREAD

**Issue by OperationTwelve** [lshqqytiger/stable-diffusion-webui-directml#296]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Saw the update to try and fix the tuple error and after update I get this when trying to start. AttributeError: module 'modules.dml' has no attribute 'initialize'

### Steps to reproduce the problem

1. Update
2. Try to start

### What should have happened?

Should start and have magic rainbows and pudding everywhere. But it doesn't start lol, Whoever is reading this, I appreciate you.

### Sysinfo

--dump-info didnt work so I am using the same one from about an hour ago
[sysinfo-2023-10-07-16-27.txt](https://github.com/lshqqytiger/stable-diffusion-webui-directml/files/12838440/sysinfo-2023-10-07-16-27.txt)

### Console logs

```Shell
venv "F:\SD\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.6.0
Commit hash: 61dcd857e04b831fd8b43cf85ceeb23b29860001
Launching Web UI with arguments: --api --lowvram --no-half --skip-torch-cuda-test --upcast-sampling --autolaunch
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Traceback (most recent call last):
  File "F:\SD\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "F:\SD\stable-diffusion-webui-directml\launch.py", line 44, in main
    start()
  File "F:\SD\stable-diffusion-webui-directml\modules\launch_utils.py", line 679, in start
    import webui
  File "F:\SD\stable-diffusion-webui-directml\webui.py", line 13, in <module>
    initialize.imports()
  File "F:\SD\stable-diffusion-webui-directml\modules\initialize.py", line 34, in imports
    shared_init.initialize()
  File "F:\SD\stable-diffusion-webui-directml\modules\shared_init.py", line 25, in initialize
    dml.initialize()
AttributeError: module 'modules.dml' has no attribute 'initialize'
Press any key to continue . . .
```

### Additional information

You got this!

**Comment by bluefalconeer** [comment]
Same issue. Was working fine this morning, I was trying to do some inpainting and the mask stayed blurred. Googled for fixes and saw some set COMMANDLINE_ARGS= argument suggestions for AMD GPUs, put them in webui-user.bat file and restarted SD. Proceeded to get following error even after removing them.
``` 
C:\Users\laval\OneDrive\Desktop\Stable Diffusion\stable-diffusion-webui-directml>webui-user.bat
Already up to date.
venv "C:\Users\laval\OneDrive\Desktop\Stable Diffusion\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: 1.6.0
Commit hash: 61dcd857e04b831fd8b43cf85ceeb23b29860001
Launching Web UI with arguments: --no-half --precision full --no-half-vae --opt-split-attention
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Traceback (most recent call last):
  File "C:\Users\laval\OneDrive\Desktop\Stable Diffusion\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "C:\Users\laval\OneDrive\Desktop\Stable Diffusion\stable-diffusion-webui-directml\launch.py", line 44, in main
    start()
  File "C:\Users\laval\OneDrive\Desktop\Stable Diffusion\stable-diffusion-webui-directml\modules\launch_utils.py", line 679, in start
    import webui
  File "C:\Users\laval\OneDrive\Desktop\Stable Diffusion\stable-diffusion-webui-directml\webui.py", line 13, in <module>    initialize.imports()
  File "C:\Users\laval\OneDrive\Desktop\Stable Diffusion\stable-diffusion-webui-directml\modules\initialize.py", line 34, in imports
    shared_init.initialize()
  File "C:\Users\laval\OneDrive\Desktop\Stable Diffusion\stable-diffusion-webui-directml\modules\shared_init.py", line 25, in initialize
    dml.initialize()
AttributeError: module 'modules.dml' has no attribute 'initialize'
Press any key to continue . . .
```

**Comment by ride5k** [comment]
this is from the latest commit which was to fix a different issue.  as it typically goes! ;)

**Comment by Owlchemist** [comment]
+1, same problem here. Also an AMD user, fwiw.

**Comment by rexorp** [comment]
yeah, same here. AMD RX580...

**Comment by patientx** [comment]
same, and amd also was working a few hours ago before the update

**Comment by ehpanzer** [comment]
Same issue

**Comment by petereglintine** [comment]
Sames

**Comment by kamenkadze** [comment]
+ XD

**Comment by vle99** [comment]
The last commit introduced the error. You can resolve it by checking out the penultimate commit.

**Comment by MonoGitsune** [comment]
> The last commit introduced the error. You can resolve it by checking out the penultimate commit.

how does one do that exactly?... sorry, i am very very beginner at coding

**Comment by vle99** [comment]
git checkout f9356881

**Comment by bluefalconeer** [comment]
@MonoGitsune 
Go to folder containing SD. Right click on folder and "Open Git Bash here" it will open a console.
Type in "git checkout f935688"

If you have Git Pull line in your webui-user.bat file you will get "you are not currently on branch" line but it will still run SD, or you can remove the line for now to not check for updates since you are off main branch now.

When the issue is fixed you can open up Git Bash again and type in "git checkout master" and it will resync you back on to main branch with all commits.

**Comment by pnotisdev** [comment]
Has this been fixed?

**Comment by OperationTwelve** [comment]
> Has this been fixed?

Yes it has :)

**Comment by Eqlipse** [comment]
> > Has this been fixed?
> 
> Yes it has :)

Nope. Running into the same error now, on a fresh install of Manjaro (Arch Linux), and using conda to run a python3.10.13 environment:

```python

(sd) eqlipse@eqlipse-linux:~/CreativeWorks/Art/AI_Generated/engines/stable-diffusion-webui-directml$ ./webui.sh

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye)
################################################################

################################################################
Running on eqlipse user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Using TCMalloc: libtcmalloc_minimal.so.4
fatal: No names found, cannot describe anything.
Python 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
Version: 1.6.0
Commit hash: 64e6b0687e182d5f17216755561c9c143d69c220
Launching Web UI with arguments: 
/opt/amdgpu/share/libdrm/amdgpu.ids: No such file or directory
/opt/amdgpu/share/libdrm/amdgpu.ids: No such file or directory
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Traceback (most recent call last):
  File "/home/eqlipse/CreativeWorks/Art/AI_Generated/engines/stable-diffusion-webui-directml/launch.py", line 48, in <module>
    main()
  File "/home/eqlipse/CreativeWorks/Art/AI_Generated/engines/stable-diffusion-webui-directml/launch.py", line 44, in main
    start()
  File "/home/eqlipse/CreativeWorks/Art/AI_Generated/engines/stable-diffusion-webui-directml/modules/launch_utils.py", line 676, in start
    import webui
  File "/home/eqlipse/CreativeWorks/Art/AI_Generated/engines/stable-diffusion-webui-directml/webui.py", line 13, in <module>
    initialize.imports()
  File "/home/eqlipse/CreativeWorks/Art/AI_Generated/engines/stable-diffusion-webui-directml/modules/initialize.py", line 34, in imports
    shared_init.initialize()
  File "/home/eqlipse/CreativeWorks/Art/AI_Generated/engines/stable-diffusion-webui-directml/modules/shared_init.py", line 26, in initialize
    dml.do_hijack()
  File "/home/eqlipse/CreativeWorks/Art/AI_Generated/engines/stable-diffusion-webui-directml/modules/dml/__init__.py", line 74, in do_hijack
    if not torch.dml.has_float64_support(device):
AttributeError: module 'torch' has no attribute 'dml'
```

Part of the problem might simply be that the script is looking in the wrong place. For Manjaro, the install path for `amdgpu.ids` is `/usr/share/libdrm/`, *not* `/opt/amdgpu/share/libdrm/`.

However, I don't know enough about coding to know how to fix this on my end.
