### ISSUE TITLE
[Bug]: After Update Cant Generate Image because AttributeError: 'LatentDiffusion' object has no attribute 'is_onnx'

### ISSUE THREAD

**Issue by Reizer88** [lshqqytiger/stable-diffusion-webui-directml#308]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Help please
After update today i can't generate image because i got this message AttributeError: 'LatentDiffusion' object has no attribute 'is_onnx'
Before update it work perfectly

### Steps to reproduce the problem

remove arguments and try some arguments but still dont work

### What should have happened?

Hope its running well again like before update

### Sysinfo

[sysinfo-2023-10-20-17-29.txt](https://github.com/lshqqytiger/stable-diffusion-webui-directml/files/13056840/sysinfo-2023-10-20-17-29.txt)

### What browsers do you use to access the UI ?

Google Chrome

### Console logs

```Shell
To create a public link, set `share=True` in `launch()`.
Startup time: 22.2s (prepare environment: 0.8s, import torch: 8.4s, import gradio: 2.4s, setup paths: 2.0s, initialize shared: 2.2s, other imports: 1.0s, setup codeformer: 0.4s, load scripts: 2.6s, initialize extra networks: 0.1s, create ui: 1.1s, gradio launch: 1.2s).
Applying attention optimization: sub-quadratic... done.
Model loaded in 10.2s (load weights from disk: 1.5s, create model: 1.1s, apply weights to model: 4.4s, apply float(): 2.0s, calculate empty prompt: 1.0s).
*** Error completing request
*** Arguments: ('task(rk8wtioyv6k18l7)', 'chaotic but orderly magnificent', '', [], 20, 'DPM++ 2M Karras', 1, 1, 7, 800, 512, False, 0.7, 1, 'None', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x00000259402BF8E0>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "D:\StableDiffusion\stable-diffusion-webui-directml\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\StableDiffusion\stable-diffusion-webui-directml\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\StableDiffusion\stable-diffusion-webui-directml\modules\txt2img.py", line 64, in txt2img
        processed = processing.process_images(p)
      File "D:\StableDiffusion\stable-diffusion-webui-directml\modules\processing.py", line 733, in process_images
        res = process_images_inner(p)
      File "D:\StableDiffusion\stable-diffusion-webui-directml\modules\processing.py", line 793, in process_images_inner        if p.sd_model.is_onnx:
      File "D:\StableDiffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
        raise AttributeError("'{}' object has no attribute '{}'".format(
    AttributeError: 'LatentDiffusion' object has no attribute 'is_onnx'

---
*** Error completing request
*** Arguments: ('task(4d1hko3vif39278)', 'chaotic but orderly magnificent', '', [], 20, 'DPM++ 2M Karras', 1, 1, 7, 800, 512, False, 0.7, 1, 'None', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], <gradio.routes.Request object at 0x00000259403BD690>, 0, False, '', 0.8, -1, False, -1, 0, 0, 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "D:\StableDiffusion\stable-diffusion-webui-directml\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "D:\StableDiffusion\stable-diffusion-webui-directml\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "D:\StableDiffusion\stable-diffusion-webui-directml\modules\txt2img.py", line 64, in txt2img
        processed = processing.process_images(p)
      File "D:\StableDiffusion\stable-diffusion-webui-directml\modules\processing.py", line 733, in process_images
        res = process_images_inner(p)
      File "D:\StableDiffusion\stable-diffusion-webui-directml\modules\processing.py", line 793, in process_images_inner
        if p.sd_model.is_onnx:
      File "D:\StableDiffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1614, in __getattr__
        raise AttributeError("'{}' object has no attribute '{}'".format(
    AttributeError: 'LatentDiffusion' object has no attribute 'is_onnx'
```

### Additional information

Windows 10
RX 6600 8 GB
RAM 32 GB

**Comment by Mechmind2** [comment]
Yeah, we're waiting for a fix.

**Comment by Reizer88** [comment]
> Yeah, we're waiting for a fix.

Temporary fixed, up and running again after i change and edited modules back to the last commit before update
Edit modules :
processing.py
sd_onnx.py
shared_options.py
After editing module i remove "git pull" from webui-user.bat

**Comment by SunGreen777** [comment]
I also have an error after updating
I added it to the config and rolled back
`git checkout 6197993f573b91f8b06889fcd09efd5353dc2cb9`

To use git pull in the future
Delete `git checkout 6197993f573b91f8b06889fcd09efd5353dc2cb9`
add this to the `git checkout master config`
 And after launch, delete it too.

I don't delete but do this REM git checkout master config

**Comment by pw405** [comment]
> I also have an error after updating Win11 32ram 570 8gb I added it to the config and rolled back `git checkout 6197993f573b91f8b06889fcd09efd5353dc2cb9`
> 
> To use git pull in the future Delete `git checkout 6197993f573b91f8b06889fcd09efd5353dc2cb9` add this to the `git checkout master config` And after launch, delete it too.
> 
> I don't delete but do this REM git checkout master config

Oh nice, I did this previously manually and didn't know you could just put in the webui-user.bat

**Comment by Jezzr** [comment]
fixed? can i enable updates again
