### ISSUE TITLE
[Bug]: File not found, its not loading some of my models

### ISSUE THREAD

**Issue by GentlemanMC** [lshqqytiger/stable-diffusion-webui-directml#311]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

i did git pull to update my local repo to follow this guide: https://community.amd.com/t5/ai/updated-how-to-running-optimized-automatic1111-stable-diffusion/ba-p/630252

then i waited for olive and onnx stuff to be downloaded then when the webui launched it was only loading one model out of the 4 i have

### Steps to reproduce the problem

1. install onnx??
2. lanuch the webui
3. some of the models would not appear (failed to load)

### What should have happened?

it should load the models :/

### Sysinfo

{
    "Platform": "Windows-10-10.0.22621-SP0",
    "Python": "3.10.11",
    "Version": "1.6.0",
    "Commit": "64e6b0687e182d5f17216755561c9c143d69c220",
    "Script path": "C:\\Users\\Gentleman\\Code projects\\stable-diffusion-webui-directml",
    "Data path": "C:\\Users\\Gentleman\\Code projects\\stable-diffusion-webui-directml",
    "Extensions dir": "C:\\Users\\Gentleman\\Code projects\\stable-diffusion-webui-directml\\extensions",
    "Checksum": "cc4ccde6c1699126197d2a60cfda82f45d00d1dcc7cf6a569dfc2f66fba6123e",
    "Commandline": [
        "launch.py",
        "--onnx",
        "--no-half",
        "--precision",
        "full",
        "--no-half-vae",
        "--opt-sub-quad-attention",
        "--opt-split-attention-v1",
        "--autolaunch"
    ],
    "Torch env info": "'NoneType' object has no attribute 'splitlines'",
    "Exceptions": [
        {
            "exception": "No checkpoints found. When searching for checkpoints, looked at:\n - file C:\\Users\\Gentleman\\Code projects\\stable-diffusion-webui-directml\\model.ckpt\n - directory C:\\Users\\Gentleman\\Code projects\\stable-diffusion-webui-directml\\models\\Stable-diffusionCan't run without a checkpoint. Find and place a .ckpt or .safetensors file into any of those locations.",
            "traceback": [
                [
                    "C:\\Users\\Gentleman\\Code projects\\stable-diffusion-webui-directml\\modules\\sd_models.py, line 544, get_sd_model",
                    "load_model()"
                ],
                [
                    "C:\\Users\\Gentleman\\Code projects\\stable-diffusion-webui-directml\\modules\\sd_models.py, line 631, load_model",
                    "checkpoint_info = checkpoint_info or select_checkpoint()"
                ],
                [
                    "C:\\Users\\Gentleman\\Code projects\\stable-diffusion-webui-directml\\modules\\sd_models.py, line 265, select_checkpoint",
                    "raise FileNotFoundError(error_message)"
                ]
            ]
        },
        {
            "exception": "No checkpoints found. When searching for checkpoints, looked at:\n - file C:\\Users\\Gentleman\\Code projects\\stable-diffusion-webui-directml\\model.ckpt\n - directory C:\\Users\\Gentleman\\Code projects\\stable-diffusion-webui-directml\\models\\Stable-diffusionCan't run without a checkpoint. Find and place a .ckpt or .safetensors file into any of those locations.",
            "traceback": [
                [
                    "C:\\Users\\Gentleman\\Code projects\\stable-diffusion-webui-directml\\modules\\sd_models.py, line 544, get_sd_model",
                    "load_model()"
                ],
                [
                    "C:\\Users\\Gentleman\\Code projects\\stable-diffusion-webui-directml\\modules\\sd_models.py, line 631, load_model",
                    "checkpoint_info = checkpoint_info or select_checkpoint()"
                ],
                [
                    "C:\\Users\\Gentleman\\Code projects\\stable-diffusion-webui-directml\\modules\\sd_models.py, line 265, select_checkpoint",
                    "raise FileNotFoundError(error_message)"
                ]
            ]
        }
    ],
    "CPU": {
        "model": "AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD",
        "count logical": 16,
        "count physical": 8
    },
    "RAM": {
        "total": "32GB",
        "used": "10GB",
        "free": "22GB"
    },
    "GPU": {
        "model": "AMD Radeon RX 6700",
        "total_memory": 3506176
    },
    "Extensions": [
        {
            "name": "sd-webui-controlnet",
            "path": "C:\\Users\\Gentleman\\Code projects\\stable-diffusion-webui-directml\\extensions\\sd-webui-controlnet",
            "version": "a43e5742",
            "branch": "main",
            "remote": "https://github.com/Mikubill/sd-webui-controlnet"
        }
    ],
    "Inactive extensions": [],
    "Environment": {
        "COMMANDLINE_ARGS": " --onnx --no-half --precision full --no-half-vae --opt-sub-quad-attention --opt-split-attention-v1 --autolaunch",
        "GRADIO_ANALYTICS_ENABLED": "False"
    },
    "Config": {
        "samples_save": true,
        "samples_format": "png",
        "samples_filename_pattern": "",
        "save_images_add_number": true,
        "grid_save": true,
        "grid_format": "png",
        "grid_extended_filename": false,
        "grid_only_if_multiple": true,
        "grid_prevent_empty_spots": false,
        "grid_zip_filename_pattern": "",
        "n_rows": -1,
        "font": "",
        "grid_text_active_color": "#000000",
        "grid_text_inactive_color": "#999999",
        "grid_background_color": "#ffffff",
        "enable_pnginfo": true,
        "save_txt": false,
        "save_images_before_face_restoration": false,
        "save_images_before_highres_fix": false,
        "save_images_before_color_correction": false,
        "save_mask": false,
        "save_mask_composite": false,
        "jpeg_quality": 80,
        "webp_lossless": false,
        "export_for_4chan": true,
        "img_downscale_threshold": 4.0,
        "target_side_length": 4000,
        "img_max_size_mp": 200,
        "use_original_name_batch": true,
        "use_upscaler_name_as_suffix": false,
        "save_selected_only": true,
        "save_init_img": false,
        "temp_dir": "",
        "clean_temp_dir_at_start": false,
        "outdir_samples": "",
        "outdir_txt2img_samples": "outputs/txt2img-images",
        "outdir_img2img_samples": "outputs/img2img-images",
        "outdir_extras_samples": "outputs/extras-images",
        "outdir_grids": "",
        "outdir_txt2img_grids": "outputs/txt2img-grids",
        "outdir_img2img_grids": "outputs/img2img-grids",
        "outdir_save": "log/images",
        "outdir_init_images": "outputs/init-images",
        "save_to_dirs": true,
        "grid_save_to_dirs": true,
        "use_save_to_dirs_for_ui": false,
        "directories_filename_pattern": "[date]",
        "directories_max_prompt_words": 8,
        "ESRGAN_tile": 192,
        "ESRGAN_tile_overlap": 8,
        "realesrgan_enabled_models": [
            "R-ESRGAN 4x+",
            "R-ESRGAN 4x+ Anime6B"
        ],
        "upscaler_for_img2img": null,
        "face_restoration_model": "CodeFormer",
        "code_former_weight": 0.5,
        "face_restoration_unload": false,
        "show_warnings": false,
        "memmon_poll_rate": 8,
        "samples_log_stdout": false,
        "multiple_tqdm": true,
        "print_hypernet_extra": false,
        "list_hidden_files": true,
        "disable_mmap_load_safetensors": false,
        "unload_models_when_training": false,
        "pin_memory": false,
        "save_optimizer_state": false,
        "save_training_settings_to_txt": true,
        "dataset_filename_word_regex": "",
        "dataset_filename_join_string": " ",
        "training_image_repeats_per_epoch": 1,
        "training_write_csv_every": 500,
        "training_xattention_optimizations": false,
        "training_enable_tensorboard": false,
        "training_tensorboard_save_images": false,
        "training_tensorboard_flush_every": 120,
        "sd_model_checkpoint": "f222.ckpt [9e2c6ceff3]",
        "sd_checkpoint_cache": 0,
        "sd_vae_checkpoint_cache": 0,
        "sd_vae": "Automatic",
        "sd_vae_as_default": true,
        "sd_unet": "Automatic",
        "inpainting_mask_weight": 1.0,
        "initial_noise_multiplier": 1.0,
        "img2img_color_correction": false,
        "img2img_fix_steps": false,
        "img2img_background_color": "#ffffff",
        "enable_quantization": false,
        "enable_emphasis": true,
        "enable_batch_seeds": true,
        "comma_padding_backtrack": 20,
        "CLIP_stop_at_last_layers": 1,
        "upcast_attn": false,
        "auto_vae_precision": true,
        "randn_source": "GPU",
        "sdxl_crop_top": 0,
        "sdxl_crop_left": 0,
        "sdxl_refiner_low_aesthetic_score": 2.5,
        "sdxl_refiner_high_aesthetic_score": 6.0,
        "enable_mem_pattern": true,
        "enable_mem_reuse": true,
        "reload_model_before_each_generation": false,
        "offload_state_dict": false,
        "cross_attention_optimization": "Automatic",
        "s_min_uncond": 0.0,
        "token_merging_ratio": 0.0,
        "token_merging_ratio_img2img": 0.0,
        "token_merging_ratio_hr": 0.0,
        "pad_cond_uncond": false,
        "experimental_persistent_cond_cache": false,
        "directml_memory_provider": "Performance Counter",
        "use_old_emphasis_implementation": false,
        "use_old_karras_scheduler_sigmas": false,
        "no_dpmpp_sde_batch_determinism": false,
        "use_old_hires_fix_width_height": false,
        "dont_fix_second_order_samplers_schedule": false,
        "hires_fix_use_firstpass_conds": false,
        "interrogate_keep_models_in_memory": false,
        "interrogate_return_ranks": false,
        "interrogate_clip_num_beams": 1,
        "interrogate_clip_min_length": 24,
        "interrogate_clip_max_length": 48,
        "interrogate_clip_dict_limit": 1500,
        "interrogate_clip_skip_categories": [],
        "interrogate_deepbooru_score_threshold": 0.5,
        "deepbooru_sort_alpha": true,
        "deepbooru_use_spaces": true,
        "deepbooru_escape": true,
        "deepbooru_filter_tags": "",
        "extra_networks_show_hidden_directories": true,
        "extra_networks_hidden_models": "When searched",
        "extra_networks_default_multiplier": 1.0,
        "extra_networks_card_width": 0,
        "extra_networks_card_height": 0,
        "extra_networks_card_text_scale": 1.0,
        "extra_networks_card_show_desc": true,
        "extra_networks_add_text_separator": " ",
        "ui_extra_networks_tab_reorder": "",
        "textual_inversion_print_at_load": false,
        "textual_inversion_add_hashes_to_infotext": true,
        "sd_hypernetwork": "None",
        "localization": "None",
        "gradio_theme": "Default",
        "img2img_editor_height": 720,
        "return_grid": true,
        "return_mask": false,
        "return_mask_composite": false,
        "do_not_show_images": false,
        "send_seed": true,
        "send_size": true,
        "js_modal_lightbox": true,
        "js_modal_lightbox_initially_zoomed": true,
        "js_modal_lightbox_gamepad": false,
        "js_modal_lightbox_gamepad_repeat": 250,
        "show_progress_in_title": true,
        "samplers_in_dropdown": true,
        "dimensions_and_batch_together": true,
        "keyedit_precision_attention": 0.1,
        "keyedit_precision_extra": 0.05,
        "keyedit_delimiters": ".,\\/!?%^*;:{}=`~()",
        "keyedit_move": true,
        "quicksettings_list": [
            "sd_model_checkpoint"
        ],
        "ui_tab_order": [],
        "hidden_tabs": [],
        "ui_reorder_list": [],
        "hires_fix_show_sampler": false,
        "hires_fix_show_prompts": false,
        "disable_token_counters": false,
        "add_model_hash_to_info": true,
        "add_model_name_to_info": true,
        "add_user_name_to_info": false,
        "add_version_to_infotext": true,
        "disable_weights_auto_swap": true,
        "infotext_styles": "Apply if any",
        "show_progressbar": true,
        "live_previews_enable": true,
        "live_previews_image_format": "png",
        "show_progress_grid": true,
        "show_progress_every_n_steps": 10,
        "show_progress_type": "Approx cheap",
        "live_preview_content": "Prompt",
        "live_preview_refresh_period": 1000,
        "hide_samplers": [],
        "eta_ddim": 0.0,
        "eta_ancestral": 1.0,
        "ddim_discretize": "uniform",
        "s_churn": 0.0,
        "s_tmin": 0.0,
        "s_noise": 1.0,
        "k_sched_type": "Automatic",
        "sigma_min": 0.0,
        "sigma_max": 0.0,
        "rho": 0.0,
        "eta_noise_seed_delta": 0,
        "always_discard_next_to_last_sigma": false,
        "uni_pc_variant": "bh1",
        "uni_pc_skip_type": "time_uniform",
        "uni_pc_order": 3,
        "uni_pc_lower_order_final": true,
        "postprocessing_enable_in_main_ui": [],
        "postprocessing_operation_order": [],
        "upscaling_max_images_in_cache": 5,
        "disabled_extensions": [],
        "disable_all_extensions": "none",
        "restore_config_state_file": "",
        "sd_checkpoint_hash": "9e2c6ceff3f6d6f65c6fb0e10d8e69d772871813be647fd2ea5d06e00db33c1f",
        "sd_vae_overrides_per_model_preferences": false
    },
    "Startup": {
        "total": 8.121742486953735,
        "records": {
            "initial startup": 0.0015034675598144531,
            "prepare environment/checks": 0.01551675796508789,
            "prepare environment/git version info": 0.03547239303588867,
            "prepare environment/clone repositores": 0.12665224075317383,
            "prepare environment/run extensions installers/sd-webui-controlnet": 0.2867305278778076,
            "prepare environment/run extensions installers": 0.2867305278778076,
            "prepare environment": 3.9284069538116455,
            "launcher": 0.001504659652709961,
            "import torch": 2.043121814727783,
            "import gradio": 1.1101477146148682,
            "setup paths": 1.2187585830688477,
            "import ldm": 0.00500178337097168,
            "import sgm": 0.0,
            "initialize shared": 1.0269191265106201,
            "other imports": 0.18410587310791016,
            "opts onchange": 0.0,
            "setup SD model": 0.0009989738464355469,
            "setup codeformer": 0.017028093338012695,
            "setup gfpgan": 0.016627073287963867,
            "set samplers": 0.0,
            "list extensions": 0.00099945068359375,
            "restore config state file": 0.0,
            "list SD models": 0.0,
            "list localizations": 0.0,
            "load scripts/custom_code.py": 0.0020008087158203125,
            "load scripts/img2imgalt.py": 0.0009992122650146484,
            "load scripts/loopback.py": 0.0,
            "load scripts/outpainting_mk_2.py": 0.001001119613647461,
            "load scripts/poor_mans_outpainting.py": 0.0,
            "load scripts/postprocessing_codeformer.py": 0.0,
            "load scripts/postprocessing_gfpgan.py": 0.0,
            "load scripts/postprocessing_upscale.py": 0.0009996891021728516,
            "load scripts/prompt_matrix.py": 0.0,
            "load scripts/prompts_from_file.py": 0.0,
            "load scripts/refiner.py": 0.0,
            "load scripts/sd_upscale.py": 0.0,
            "load scripts/seed.py": 0.0015039443969726562,
            "load scripts/xyz_grid.py": 0.001005411148071289,
            "load scripts/adapter.py": 0.0,
            "load scripts/api.py": 0.8847715854644775,
            "load scripts/batch_hijack.py": 0.0010008811950683594,
            "load scripts/cldm.py": 0.0009989738464355469,
            "load scripts/controlmodel_ipadapter.py": 0.0,
            "load scripts/controlnet.py": 0.1049661636352539,
            "load scripts/controlnet_diffusers.py": 0.0009958744049072266,
            "load scripts/controlnet_lllite.py": 0.0,
            "load scripts/controlnet_lora.py": 0.00099945068359375,
            "load scripts/controlnet_model_guess.py": 0.0,
            "load scripts/controlnet_version.py": 0.0,
            "load scripts/external_code.py": 0.0009999275207519531,
            "load scripts/global_state.py": 0.0,
            "load scripts/hook.py": 0.0010001659393310547,
            "load scripts/infotext.py": 0.0,
            "load scripts/logging.py": 0.0009996891021728516,
            "load scripts/lvminthin.py": 0.0,
            "load scripts/movie2movie.py": 0.001001596450805664,
            "load scripts/processor.py": 0.0,
            "load scripts/utils.py": 0.0,
            "load scripts/xyz_grid_support.py": 0.0009980201721191406,
            "load scripts/ldsr_model.py": 0.026204347610473633,
            "load scripts/lora_script.py": 0.13596844673156738,
            "load scripts/scunet_model.py": 0.021019697189331055,
            "load scripts/swinir_model.py": 0.019018173217773438,
            "load scripts/hotkey_config.py": 0.0010037422180175781,
            "load scripts/extra_options_section.py": 0.0,
            "load scripts": 1.2094569206237793,
            "load upscalers": 0.0019979476928710938,
            "refresh VAE": 0.0019996166229248047,
            "refresh textual inversion templates": 0.0,
            "scripts list_optimizers": 0.0,
            "scripts list_unets": 0.0,
            "reload hypernetworks": 0.0010001659393310547,
            "initialize extra networks": 0.003071308135986328,
            "scripts before_ui_callback": 0.0,
            "create ui": 0.647697925567627,
            "gradio launch": 0.1579148769378662,
            "add APIs": 0.006514787673950195,
            "app_started_callback/api.py": 0.0010004043579101562,
            "app_started_callback/lora_script.py": 0.0,
            "app_started_callback": 0.0010004043579101562
        }
    },
    "Packages": [
        "absl-py==1.4.0",
        "accelerate==0.21.0",
        "addict==2.4.0",
        "aenum==3.1.15",
        "aiofiles==23.2.1",
        "aiohttp==3.8.5",
        "aiosignal==1.3.1",
        "alembic==1.12.1",
        "altair==5.0.1",
        "antlr4-python3-runtime==4.9.3",
        "anyio==3.7.1",
        "async-timeout==4.0.3",
        "attrs==23.1.0",
        "basicsr==1.4.2",
        "beautifulsoup4==4.12.2",
        "blendmodes==2022",
        "boltons==23.0.0",
        "cachetools==5.3.1",
        "certifi==2023.7.22",
        "cffi==1.16.0",
        "charset-normalizer==3.2.0",
        "clean-fid==0.1.35",
        "click==8.1.7",
        "clip==1.0",
        "colorama==0.4.6",
        "coloredlogs==15.0.1",
        "colorlog==6.7.0",
        "contourpy==1.1.0",
        "cssselect2==0.7.0",
        "cycler==0.11.0",
        "datasets==2.14.6",
        "deprecation==2.1.0",
        "diffusers==0.20.0",
        "dill==0.3.7",
        "einops==0.4.1",
        "exceptiongroup==1.1.3",
        "facexlib==0.3.0",
        "fastapi==0.94.0",
        "ffmpy==0.3.1",
        "filelock==3.12.2",
        "filterpy==1.4.5",
        "flatbuffers==23.5.26",
        "fonttools==4.42.1",
        "frozenlist==1.4.0",
        "fsspec==2023.6.0",
        "ftfy==6.1.1",
        "future==0.18.3",
        "fvcore==0.1.5.post20221221",
        "gdown==4.7.1",
        "gfpgan==1.3.8",
        "gitdb==4.0.10",
        "gitpython==3.1.32",
        "google-auth-oauthlib==1.0.0",
        "google-auth==2.22.0",
        "gradio-client==0.5.0",
        "gradio==3.41.2",
        "greenlet==3.0.1",
        "grpcio==1.57.0",
        "h11==0.12.0",
        "httpcore==0.15.0",
        "httpx==0.24.1",
        "huggingface-hub==0.16.4",
        "humanfriendly==10.0",
        "idna==3.4",
        "imageio==2.31.2",
        "importlib-metadata==6.8.0",
        "importlib-resources==6.1.0",
        "inflection==0.5.1",
        "invisible-watermark==0.2.0",
        "iopath==0.1.9",
        "jinja2==3.1.2",
        "jsonmerge==1.8.0",
        "jsonschema-specifications==2023.7.1",
        "jsonschema==4.19.0",
        "kiwisolver==1.4.5",
        "kornia==0.6.7",
        "lark==1.1.2",
        "lazy-loader==0.3",
        "lightning-utilities==0.9.0",
        "linkify-it-py==2.0.2",
        "llvmlite==0.40.1",
        "lmdb==1.4.1",
        "lpips==0.1.4",
        "lxml==4.9.3",
        "mako==1.2.4",
        "markdown-it-py==2.2.0",
        "markdown==3.4.4",
        "markupsafe==2.1.3",
        "matplotlib==3.7.2",
        "mdit-py-plugins==0.3.3",
        "mdurl==0.1.2",
        "mediapipe==0.10.7",
        "mpmath==1.3.0",
        "multidict==6.0.4",
        "multiprocess==0.70.15",
        "networkx==3.1",
        "numba==0.57.1",
        "numpy==1.23.5",
        "oauthlib==3.2.2",
        "olive-ai==0.3.3",
        "omegaconf==2.2.3",
        "onnx==1.15.0",
        "onnxruntime-directml==1.16.1",
        "onnxruntime==1.16.1",
        "open-clip-torch==2.20.0",
        "opencv-contrib-python==4.8.1.78",
        "opencv-python==4.8.0.76",
        "optimum==1.13.1",
        "optuna==3.4.0",
        "orjson==3.9.5",
        "packaging==23.1",
        "pandas==2.0.3",
        "piexif==1.1.3",
        "pillow==9.5.0",
        "pip==22.2.1",
        "platformdirs==3.10.0",
        "portalocker==2.8.2",
        "protobuf==3.20.3",
        "psutil==5.9.5",
        "pyarrow==14.0.0",
        "pyasn1-modules==0.3.0",
        "pyasn1==0.5.0",
        "pycparser==2.21",
        "pydantic==1.10.12",
        "pydub==0.25.1",
        "pygments==2.16.1",
        "pyparsing==3.0.9",
        "pyreadline3==3.4.1",
        "pysocks==1.7.1",
        "python-dateutil==2.8.2",
        "python-multipart==0.0.6",
        "pytorch-lightning==1.9.4",
        "pytz==2023.3",
        "pywavelets==1.4.1",
        "pywin32==306",
        "pyyaml==6.0.1",
        "realesrgan==0.3.0",
        "referencing==0.30.2",
        "regex==2023.8.8",
        "reportlab==4.0.6",
        "requests-oauthlib==1.3.1",
        "requests==2.31.0",
        "resize-right==0.0.2",
        "rpds-py==0.9.2",
        "rsa==4.9",
        "safetensors==0.3.1",
        "scikit-image==0.21.0",
        "scipy==1.11.2",
        "semantic-version==2.10.0",
        "sentencepiece==0.1.99",
        "setuptools==63.2.0",
        "six==1.16.0",
        "smmap==5.0.0",
        "sniffio==1.3.0",
        "sounddevice==0.4.6",
        "soupsieve==2.4.1",
        "sqlalchemy==2.0.22",
        "starlette==0.26.1",
        "svglib==1.5.1",
        "sympy==1.12",
        "tabulate==0.9.0",
        "tb-nightly==2.15.0a20230826",
        "tensorboard-data-server==0.7.1",
        "termcolor==2.3.0",
        "tifffile==2023.8.25",
        "timm==0.9.2",
        "tinycss2==1.2.1",
        "tokenizers==0.13.3",
        "tomesd==0.1.3",
        "tomli==2.0.1",
        "toolz==0.12.0",
        "torch-directml==0.1.13.1.dev230413",
        "torch==1.13.1",
        "torchdiffeq==0.2.3",
        "torchmetrics==0.10.3",
        "torchsde==0.2.5",
        "torchvision==0.14.1",
        "tqdm==4.66.1",
        "trampoline==0.1.2",
        "transformers==4.32.1",
        "typing-extensions==4.7.1",
        "tzdata==2023.3",
        "uc-micro-py==1.0.2",
        "urllib3==1.26.16",
        "uvicorn==0.23.2",
        "wcwidth==0.2.6",
        "webencodings==0.5.1",
        "websockets==11.0.3",
        "werkzeug==2.3.7",
        "wheel==0.41.2",
        "xxhash==3.4.1",
        "yacs==0.1.8",
        "yapf==0.40.1",
        "yarl==1.9.2",
        "zipp==3.16.2"
    ]
}

### What browsers do you use to access the UI ?

Brave

### Console logs

```Shell
venv "C:\Users\Gentleman\Code projects\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: 1.6.0
Commit hash: 64e6b0687e182d5f17216755561c9c143d69c220
Installing onnxruntime
Installing onnxruntime-directml
Installing Olive
Launching Web UI with arguments: --onnx --no-half --precision full --no-half-vae --opt-sub-quad-attention --opt-split-attention-v1 --autolaunch
no module 'xformers'. Processing without...
No SDP backend available, likely because you are running in pytorch versions < 2.0. In fact, you are using PyTorch 1.13.1+cpu. You might want to consider upgrading.
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
==============================================================================
You are running torch 1.13.1+cpu.
The program is tested to work with torch 2.0.0.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
2023-11-02 14:40:36,678 - ControlNet - INFO - ControlNet v1.1.411
ControlNet preprocessor location: C:\Users\Gentleman\Code projects\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\downloads
2023-11-02 14:40:36,783 - ControlNet - INFO - ControlNet v1.1.411
loading stable diffusion model: FileNotFoundError
Traceback (most recent call last):
  File "C:\Users\Gentleman\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\Gentleman\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Gentleman\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Gentleman\Code projects\stable-diffusion-webui-directml\modules\initialize.py", line 147, in load_model
    shared.sd_model  # noqa: B018
  File "C:\Users\Gentleman\Code projects\stable-diffusion-webui-directml\modules\shared_items.py", line 110, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "C:\Users\Gentleman\Code projects\stable-diffusion-webui-directml\modules\sd_models.py", line 544, in get_sd_model
    load_model()
  File "C:\Users\Gentleman\Code projects\stable-diffusion-webui-directml\modules\sd_models.py", line 631, in load_model
    checkpoint_info = checkpoint_info or select_checkpoint()
  File "C:\Users\Gentleman\Code projects\stable-diffusion-webui-directml\modules\sd_models.py", line 265, in select_checkpoint
    raise FileNotFoundError(error_message)
FileNotFoundError: No checkpoints found. When searching for checkpoints, looked at:
 - file C:\Users\Gentleman\Code projects\stable-diffusion-webui-directml\model.ckpt
 - directory C:\Users\Gentleman\Code projects\stable-diffusion-webui-directml\models\Stable-diffusionCan't run without a checkpoint. Find and place a .ckpt or .safetensors file into any of those locations.


Stable diffusion model failed to load
Applying attention optimization: sub-quadratic... done.
C:\Users\Gentleman\Code projects\stable-diffusion-webui-directml\modules\ui.py:1665: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
C:\Users\Gentleman\Code projects\stable-diffusion-webui-directml\modules\ui.py:1787: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 8.1s (prepare environment: 3.9s, import torch: 2.0s, import gradio: 1.1s, setup paths: 1.2s, initialize shared: 1.0s, other imports: 0.2s, load scripts: 1.2s, create ui: 0.6s, gradio launch: 0.2s).
loading stable diffusion model: FileNotFoundError
Traceback (most recent call last):
  File "C:\Users\Gentleman\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\Gentleman\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Gentleman\Code projects\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Gentleman\Code projects\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\Gentleman\Code projects\stable-diffusion-webui-directml\modules\ui.py", line 2975, in <lambda>
    visible=shared.sd_model and shared.sd_model.cond_stage_key == "edit"
  File "C:\Users\Gentleman\Code projects\stable-diffusion-webui-directml\modules\shared_items.py", line 110, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "C:\Users\Gentleman\Code projects\stable-diffusion-webui-directml\modules\sd_models.py", line 544, in get_sd_model
    load_model()
  File "C:\Users\Gentleman\Code projects\stable-diffusion-webui-directml\modules\sd_models.py", line 631, in load_model
    checkpoint_info = checkpoint_info or select_checkpoint()
  File "C:\Users\Gentleman\Code projects\stable-diffusion-webui-directml\modules\sd_models.py", line 265, in select_checkpoint
    raise FileNotFoundError(error_message)
FileNotFoundError: No checkpoints found. When searching for checkpoints, looked at:
 - file C:\Users\Gentleman\Code projects\stable-diffusion-webui-directml\model.ckpt
 - directory C:\Users\Gentleman\Code projects\stable-diffusion-webui-directml\models\Stable-diffusionCan't run without a checkpoint. Find and place a .ckpt or .safetensors file into any of those locations.


Stable diffusion model failed to load
```

**Comment by GentlemanMC** [comment]
actually nvm it isnt loading any model
xd
