### ISSUE TITLE
[Bug]: install clip failed

### ISSUE THREAD

**Issue by ASTRB** [lshqqytiger/stable-diffusion-webui-directml#33]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

![image](https://user-images.githubusercontent.com/126944019/223651904-9c453565-7123-4fa7-895b-49f40de98d96.png)
i dont know how to install clip and whats wrong

### Steps to reproduce the problem

![image](https://user-images.githubusercontent.com/126944019/223652344-6edb6773-b7f2-4a02-bcf8-d82c650d3c6a.png)
just follow this
and upgrade pip version

### What should have happened?

WeUI should have been launched

### Commit where the problem happens

git fetch -q https://github.com/openai/CLIP.git d50d76daa670286dd6cacf3bcd80b5e4823fc8e1 did not run successfully.

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
no
```

### List of extensions

no

### Console logs

```Shell
venv "D:\Project\StableDiffusionWebui\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: ff558348682fea569785dcfae1f1282cfbefda6b
Installing clip
Traceback (most recent call last):
  File "D:\Project\StableDiffusionWebui\stable-diffusion-webui-directml\launch.py", line 356, in <module>
    prepare_environment()
  File "D:\Project\StableDiffusionWebui\stable-diffusion-webui-directml\launch.py", line 276, in prepare_environment
    run_pip(f"install {clip_package}", "clip")
  File "D:\Project\StableDiffusionWebui\stable-diffusion-webui-directml\launch.py", line 137, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "D:\Project\StableDiffusionWebui\stable-diffusion-webui-directml\launch.py", line 105, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install clip.
Command: "D:\Project\StableDiffusionWebui\stable-diffusion-webui-directml\venv\Scripts\python.exe" -m pip install git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1 --prefer-binary
Error code: 1
stdout: Collecting git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
  Cloning https://github.com/openai/CLIP.git (to revision d50d76daa670286dd6cacf3bcd80b5e4823fc8e1) to c:\users\zxy\appdata\local\temp\pip-req-build-rx2qalf3

stderr:   Running command git clone --filter=blob:none --quiet https://github.com/openai/CLIP.git 'C:\Users\ZXY\AppData\Local\Temp\pip-req-build-rx2qalf3'
  Running command git rev-parse -q --verify 'sha^d50d76daa670286dd6cacf3bcd80b5e4823fc8e1'
  Running command git fetch -q https://github.com/openai/CLIP.git d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
  fatal: unable to access 'https://github.com/openai/CLIP.git/': Recv failure: Connection was reset
  error: subprocess-exited-with-error

  git fetch -q https://github.com/openai/CLIP.git d50d76daa670286dd6cacf3bcd80b5e4823fc8e1 did not run successfully.
  exit code: 128

  See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

git fetch -q https://github.com/openai/CLIP.git d50d76daa670286dd6cacf3bcd80b5e4823fc8e1 did not run successfully.
exit code: 128

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### Additional information

No response

**Comment by no-42** [comment]
check you proxy  confirm you can connect github.
see git set http_proxy
