### ISSUE TITLE
[Bug]: "Couldn't install Torch"

### ISSUE THREAD

**Issue by ActualVoidDiver** [lshqqytiger/stable-diffusion-webui-directml#336]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Installing SD. After cloning the repository and running `webui-user.bat`, I've ran into the error provided. 

### Steps to reproduce the problem

Brand new install of SD. 

### What should have happened?

...It should've installed.

### Sysinfo

skip

### Console logs

```Shell
Creating venv in directory C:\AI\SD\stable-diffusion-webui-directml\venv using python "C:\Users\user\AppData\Local\Programs\Python\Python310\python.exe"
venv "C:\AI\SD\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.7.0
Commit hash: a675a0a5107f39292709a78a2802425f67e4c6c4
Traceback (most recent call last):
  File "C:\AI\SD\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "C:\AI\SD\stable-diffusion-webui-directml\launch.py", line 39, in main
    prepare_environment()
  File "C:\AI\SD\stable-diffusion-webui-directml\modules\launch_utils.py", line 552, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
UnboundLocalError: local variable 'torch_command' referenced before assignment
Press any key to continue . . .
```

### Additional information

Occurred after the update.

**Comment by ActualVoidDiver** [comment]
Although a little stupid doing exactly the same thing expecting a different result, it works now - I did exactly everything as before several times, and now for some reason it did work. Thanks anyways! <3
