### ISSUE TITLE
[Bug]: Webui fails to launch after update, --use-directml arg attached.

### ISSUE THREAD

**Issue by Jyoumon** [lshqqytiger/stable-diffusion-webui-directml#337]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

`AttributeError: module 'torch' has no attribute 'dml'`
Reported after attempted start of webui.

### Steps to reproduce the problem

1. Launch webui-user.bat
2. webui starts to load pertinent files.
3. webui-user displays error and 'any key to continue' which closes program.

### What should have happened?

start properly.

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

Can not get a dump file to generate currently.

### Console logs

```Shell
venv "C:\SDAMD\WebUI\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.7.0
Commit hash: 25205c9e114a3773f2ce38379f85d18304c34988
is_installed check for tensorflow-cpu failed as 'spec is None'
Installing requirements for easyphoto-webui
Installing requirements for tensorflow
*** Error running install.py for extension C:\SDAMD\WebUI\stable-diffusion-webui-directml\extensions\sd-webui-roop.
*** Command: "C:\SDAMD\WebUI\stable-diffusion-webui-directml\venv\Scripts\python.exe" "C:\SDAMD\WebUI\stable-diffusion-webui-directml\extensions\sd-webui-roop\install.py"
*** Error code: 1
*** stdout: Collecting insightface==0.7.3
***   Using cached insightface-0.7.3.tar.gz (439 kB)
***   Installing build dependencies: started
***   Installing build dependencies: finished with status 'done'
***   Getting requirements to build wheel: started
***   Getting requirements to build wheel: finished with status 'done'
***   Installing backend dependencies: started
***   Installing backend dependencies: finished with status 'done'
***   Preparing metadata (pyproject.toml): started
***   Preparing metadata (pyproject.toml): finished with status 'done'
*** Collecting onnx==1.14.0
***   Using cached onnx-1.14.0-cp310-cp310-win_amd64.whl (13.3 MB)
*** Collecting onnxruntime==1.15.0
***   Using cached onnxruntime-1.15.0-cp310-cp310-win_amd64.whl (6.7 MB)
*** Collecting opencv-python==4.7.0.72
***   Using cached opencv_python-4.7.0.72-cp37-abi3-win_amd64.whl (38.2 MB)
*** Collecting ifnude
***   Using cached ifnude-0.0.3-py2.py3-none-any.whl (7.1 kB)
*** Collecting cython
***   Using cached Cython-3.0.7-cp310-cp310-win_amd64.whl (2.8 MB)
*** Collecting scikit-image
***   Using cached scikit_image-0.22.0-cp310-cp310-win_amd64.whl (24.5 MB)
*** Collecting prettytable
***   Using cached prettytable-3.9.0-py3-none-any.whl (27 kB)
*** Collecting Pillow
***   Using cached Pillow-10.1.0-cp310-cp310-win_amd64.whl (2.6 MB)
*** Collecting matplotlib
***   Using cached matplotlib-3.8.2-cp310-cp310-win_amd64.whl (7.6 MB)
*** Collecting easydict
***   Using cached easydict-1.11.tar.gz (6.6 kB)
***   Preparing metadata (setup.py): started
***   Preparing metadata (setup.py): finished with status 'done'
*** Collecting albumentations
***   Using cached albumentations-1.3.1-py3-none-any.whl (125 kB)
*** Collecting requests
***   Using cached requests-2.31.0-py3-none-any.whl (62 kB)
*** Collecting tqdm
***   Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
*** Collecting scipy
***   Using cached scipy-1.11.4-cp310-cp310-win_amd64.whl (44.1 MB)
*** Requirement already satisfied: numpy in c:\users\feder\appdata\local\programs\python\python310\lib\site-packages (from insightface==0.7.3->-r C:\SDAMD\WebUI\stable-diffusion-webui-directml\extensions\sd-webui-roop\requirements.txt (line 1)) (1.26.2)
*** Collecting scikit-learn
***   Using cached scikit_learn-1.3.2-cp310-cp310-win_amd64.whl (9.3 MB)
*** Collecting protobuf>=3.20.2
***   Using cached protobuf-4.25.1-cp310-abi3-win_amd64.whl (413 kB)
*** Collecting typing-extensions>=3.6.2.1
***   Using cached typing_extensions-4.9.0-py3-none-any.whl (32 kB)
*** Collecting packaging
***   Using cached packaging-23.2-py3-none-any.whl (53 kB)
*** Collecting coloredlogs
***   Using cached coloredlogs-15.0.1-py2.py3-none-any.whl (46 kB)
*** Collecting flatbuffers
***   Using cached flatbuffers-23.5.26-py2.py3-none-any.whl (26 kB)
*** Collecting sympy
***   Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
*** Collecting opencv-python-headless>=4.5.1.48
***   Using cached opencv_python_headless-4.8.1.78-cp37-abi3-win_amd64.whl (38.0 MB)
*** Collecting PyYAML
***   Using cached PyYAML-6.0.1-cp310-cp310-win_amd64.whl (145 kB)
*** Collecting qudida>=0.0.4
***   Using cached qudida-0.0.4-py3-none-any.whl (3.5 kB)
*** Collecting networkx>=2.8
***   Using cached networkx-3.2.1-py3-none-any.whl (1.6 MB)
*** Collecting imageio>=2.27
***   Using cached imageio-2.33.1-py3-none-any.whl (313 kB)
*** Collecting lazy_loader>=0.3
***   Using cached lazy_loader-0.3-py3-none-any.whl (9.1 kB)
*** Collecting tifffile>=2022.8.12
***   Using cached tifffile-2023.12.9-py3-none-any.whl (223 kB)
*** Collecting humanfriendly>=9.1
***   Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)
*** Collecting cycler>=0.10
***   Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
*** Collecting fonttools>=4.22.0
***   Using cached fonttools-4.47.0-cp310-cp310-win_amd64.whl (2.2 MB)
*** Collecting contourpy>=1.0.1
***   Using cached contourpy-1.2.0-cp310-cp310-win_amd64.whl (186 kB)
*** Collecting python-dateutil>=2.7
***   Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
*** Collecting kiwisolver>=1.3.1
***   Using cached kiwisolver-1.4.5-cp310-cp310-win_amd64.whl (56 kB)
*** Collecting pyparsing>=2.3.1
***   Using cached pyparsing-3.1.1-py3-none-any.whl (103 kB)
*** Collecting wcwidth
***   Using cached wcwidth-0.2.12-py2.py3-none-any.whl (34 kB)
*** Collecting certifi>=2017.4.17
***   Using cached certifi-2023.11.17-py3-none-any.whl (162 kB)
*** Collecting urllib3<3,>=1.21.1
***   Using cached urllib3-2.1.0-py3-none-any.whl (104 kB)
*** Collecting idna<4,>=2.5
***   Using cached idna-3.6-py3-none-any.whl (61 kB)
*** Collecting charset-normalizer<4,>=2
***   Using cached charset_normalizer-3.3.2-cp310-cp310-win_amd64.whl (100 kB)
*** Collecting joblib>=1.1.1
***   Using cached joblib-1.3.2-py3-none-any.whl (302 kB)
*** Collecting threadpoolctl>=2.0.0
***   Using cached threadpoolctl-3.2.0-py3-none-any.whl (15 kB)
*** Collecting mpmath>=0.19
***   Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
*** Collecting colorama
***   Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
*** Collecting pyreadline3
***   Using cached pyreadline3-3.4.1-py3-none-any.whl (95 kB)
*** Collecting six>=1.5
***   Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
*** Using legacy 'setup.py install' for easydict, since package 'wheel' is not installed.
*** Building wheels for collected packages: insightface
***   Building wheel for insightface (pyproject.toml): started
***   Building wheel for insightface (pyproject.toml): finished with status 'error'
*** Failed to build insightface
***
*** stderr:   error: subprocess-exited-with-error
***
***   Building wheel for insightface (pyproject.toml) did not run successfully.
***   exit code: 1
***
***   [215 lines of output]
***   WARNING: pandoc not enabled
***   running bdist_wheel
***   running build
***   running build_py
***   creating build
***   creating build\lib.win-amd64-cpython-310
***   creating build\lib.win-amd64-cpython-310\insightface
***   copying insightface\__init__.py -> build\lib.win-amd64-cpython-310\insightface
***   creating build\lib.win-amd64-cpython-310\insightface\app
***   copying insightface\app\common.py -> build\lib.win-amd64-cpython-310\insightface\app
***   copying insightface\app\face_analysis.py -> build\lib.win-amd64-cpython-310\insightface\app
***   copying insightface\app\mask_renderer.py -> build\lib.win-amd64-cpython-310\insightface\app
***   copying insightface\app\__init__.py -> build\lib.win-amd64-cpython-310\insightface\app
***   creating build\lib.win-amd64-cpython-310\insightface\commands
***   copying insightface\commands\insightface_cli.py -> build\lib.win-amd64-cpython-310\insightface\commands
***   copying insightface\commands\model_download.py -> build\lib.win-amd64-cpython-310\insightface\commands
***   copying insightface\commands\rec_add_mask_param.py -> build\lib.win-amd64-cpython-310\insightface\commands
***   copying insightface\commands\__init__.py -> build\lib.win-amd64-cpython-310\insightface\commands
***   creating build\lib.win-amd64-cpython-310\insightface\data
***   copying insightface\data\image.py -> build\lib.win-amd64-cpython-310\insightface\data
***   copying insightface\data\pickle_object.py -> build\lib.win-amd64-cpython-310\insightface\data
***   copying insightface\data\rec_builder.py -> build\lib.win-amd64-cpython-310\insightface\data
***   copying insightface\data\__init__.py -> build\lib.win-amd64-cpython-310\insightface\data
***   creating build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\arcface_onnx.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\attribute.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\inswapper.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\landmark.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\model_store.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\model_zoo.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\retinaface.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\scrfd.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   copying insightface\model_zoo\__init__.py -> build\lib.win-amd64-cpython-310\insightface\model_zoo
***   creating build\lib.win-amd64-cpython-310\insightface\thirdparty
***   copying insightface\thirdparty\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty
***   creating build\lib.win-amd64-cpython-310\insightface\utils
***   copying insightface\utils\constant.py -> build\lib.win-amd64-cpython-310\insightface\utils
***   copying insightface\utils\download.py -> build\lib.win-amd64-cpython-310\insightface\utils
***   copying insightface\utils\face_align.py -> build\lib.win-amd64-cpython-310\insightface\utils
***   copying insightface\utils\filesystem.py -> build\lib.win-amd64-cpython-310\insightface\utils
***   copying insightface\utils\storage.py -> build\lib.win-amd64-cpython-310\insightface\utils
***   copying insightface\utils\transform.py -> build\lib.win-amd64-cpython-310\insightface\utils
***   copying insightface\utils\__init__.py -> build\lib.win-amd64-cpython-310\insightface\utils
***   creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d
***   copying insightface\thirdparty\face3d\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d
***   creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
***   copying insightface\thirdparty\face3d\mesh\io.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
***   copying insightface\thirdparty\face3d\mesh\light.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
***   copying insightface\thirdparty\face3d\mesh\render.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
***   copying insightface\thirdparty\face3d\mesh\transform.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
***   copying insightface\thirdparty\face3d\mesh\vis.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
***   copying insightface\thirdparty\face3d\mesh\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh
***   creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
***   copying insightface\thirdparty\face3d\mesh_numpy\io.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
***   copying insightface\thirdparty\face3d\mesh_numpy\light.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
***   copying insightface\thirdparty\face3d\mesh_numpy\render.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
***   copying insightface\thirdparty\face3d\mesh_numpy\transform.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
***   copying insightface\thirdparty\face3d\mesh_numpy\vis.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
***   copying insightface\thirdparty\face3d\mesh_numpy\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh_numpy
***   creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model
***   copying insightface\thirdparty\face3d\morphable_model\fit.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model
***   copying insightface\thirdparty\face3d\morphable_model\load.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model
***   copying insightface\thirdparty\face3d\morphable_model\morphabel_model.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model
***   copying insightface\thirdparty\face3d\morphable_model\__init__.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\morphable_model
***   running egg_info
***   writing insightface.egg-info\PKG-INFO
***   writing dependency_links to insightface.egg-info\dependency_links.txt
***   writing entry points to insightface.egg-info\entry_points.txt
***   writing requirements to insightface.egg-info\requires.txt
***   writing top-level names to insightface.egg-info\top_level.txt
***   reading manifest file 'insightface.egg-info\SOURCES.txt'
***   writing manifest file 'insightface.egg-info\SOURCES.txt'
***   C:\Users\feder\AppData\Local\Temp\pip-build-env-tt9j3_kd\overlay\Lib\site-packages\setuptools\command\build_py.py:207: _Warning: Package 'insightface.thirdparty.face3d.mesh.cython' is absent from the `packages` configuration.
***   !!
***
***           ********************************************************************************
***           ############################
***           # Package would be ignored #
***           ############################
***           Python recognizes 'insightface.thirdparty.face3d.mesh.cython' as an importable package[^1],
***           but it is absent from setuptools' `packages` configuration.
***
***           This leads to an ambiguous overall configuration. If you want to distribute this
***           package, please make sure that 'insightface.thirdparty.face3d.mesh.cython' is explicitly added
***           to the `packages` configuration field.
***
***           Alternatively, you can also rely on setuptools' discovery methods
***           (for example by using `find_namespace_packages(...)`/`find_namespace:`
***           instead of `find_packages(...)`/`find:`).
***
***           You can read more about "package discovery" on setuptools documentation page:
***
***           - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
***
***           If you don't want 'insightface.thirdparty.face3d.mesh.cython' to be distributed and are
***           already explicitly excluding 'insightface.thirdparty.face3d.mesh.cython' via
***           `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
***           you can try to use `exclude_package_data`, or `include-package-data=False` in
***           combination with a more fine grained `package-data` configuration.
***
***           You can read more about "package data files" on setuptools documentation page:
***
***           - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
***
***
***           [^1]: For Python, any directory (with suitable naming) can be imported,
***                 even if it does not contain any `.py` files.
***                 On the other hand, currently there is no concept of package data
***                 directory, all directories are treated like packages.
***           ********************************************************************************
***
***   !!
***     check.warn(importable)
***   C:\Users\feder\AppData\Local\Temp\pip-build-env-tt9j3_kd\overlay\Lib\site-packages\setuptools\command\build_py.py:207: _Warning: Package 'insightface.data.images' is absent from the `packages` configuration.
***   !!
***
***           ********************************************************************************
***           ############################
***           # Package would be ignored #
***           ############################
***           Python recognizes 'insightface.data.images' as an importable package[^1],
***           but it is absent from setuptools' `packages` configuration.
***
***           This leads to an ambiguous overall configuration. If you want to distribute this
***           package, please make sure that 'insightface.data.images' is explicitly added
***           to the `packages` configuration field.
***
***           Alternatively, you can also rely on setuptools' discovery methods
***           (for example by using `find_namespace_packages(...)`/`find_namespace:`
***           instead of `find_packages(...)`/`find:`).
***
***           You can read more about "package discovery" on setuptools documentation page:
***
***           - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
***
***           If you don't want 'insightface.data.images' to be distributed and are
***           already explicitly excluding 'insightface.data.images' via
***           `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
***           you can try to use `exclude_package_data`, or `include-package-data=False` in
***           combination with a more fine grained `package-data` configuration.
***
***           You can read more about "package data files" on setuptools documentation page:
***
***           - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
***
***
***           [^1]: For Python, any directory (with suitable naming) can be imported,
***                 even if it does not contain any `.py` files.
***                 On the other hand, currently there is no concept of package data
***                 directory, all directories are treated like packages.
***           ********************************************************************************
***
***   !!
***     check.warn(importable)
***   C:\Users\feder\AppData\Local\Temp\pip-build-env-tt9j3_kd\overlay\Lib\site-packages\setuptools\command\build_py.py:207: _Warning: Package 'insightface.data.objects' is absent from the `packages` configuration.
***   !!
***
***           ********************************************************************************
***           ############################
***           # Package would be ignored #
***           ############################
***           Python recognizes 'insightface.data.objects' as an importable package[^1],
***           but it is absent from setuptools' `packages` configuration.
***
***           This leads to an ambiguous overall configuration. If you want to distribute this
***           package, please make sure that 'insightface.data.objects' is explicitly added
***           to the `packages` configuration field.
***
***           Alternatively, you can also rely on setuptools' discovery methods
***           (for example by using `find_namespace_packages(...)`/`find_namespace:`
***           instead of `find_packages(...)`/`find:`).
***
***           You can read more about "package discovery" on setuptools documentation page:
***
***           - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
***
***           If you don't want 'insightface.data.objects' to be distributed and are
***           already explicitly excluding 'insightface.data.objects' via
***           `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
***           you can try to use `exclude_package_data`, or `include-package-data=False` in
***           combination with a more fine grained `package-data` configuration.
***
***           You can read more about "package data files" on setuptools documentation page:
***
***           - https://setuptools.pypa.io/en/latest/userguide/datafiles.html
***
***
***           [^1]: For Python, any directory (with suitable naming) can be imported,
***                 even if it does not contain any `.py` files.
***                 On the other hand, currently there is no concept of package data
***                 directory, all directories are treated like packages.
***           ********************************************************************************
***
***   !!
***     check.warn(importable)
***   creating build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
***   copying insightface\thirdparty\face3d\mesh\cython\mesh_core.cpp -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
***   copying insightface\thirdparty\face3d\mesh\cython\mesh_core.h -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
***   copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.cpp -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
***   creating build\lib.win-amd64-cpython-310\insightface\data\images
***   copying insightface\data\images\Tom_Hanks_54745.png -> build\lib.win-amd64-cpython-310\insightface\data\images
***   copying insightface\data\images\mask_black.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
***   copying insightface\data\images\mask_blue.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
***   copying insightface\data\images\mask_green.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
***   copying insightface\data\images\mask_white.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
***   copying insightface\data\images\t1.jpg -> build\lib.win-amd64-cpython-310\insightface\data\images
***   creating build\lib.win-amd64-cpython-310\insightface\data\objects
***   copying insightface\data\objects\meanshape_68.pkl -> build\lib.win-amd64-cpython-310\insightface\data\objects
***   copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.c -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
***   copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.cpp -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
***   copying insightface\thirdparty\face3d\mesh\cython\mesh_core_cython.pyx -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
***   copying insightface\thirdparty\face3d\mesh\cython\setup.py -> build\lib.win-amd64-cpython-310\insightface\thirdparty\face3d\mesh\cython
***   running build_ext
***   building 'insightface.thirdparty.face3d.mesh.cython.mesh_core_cython' extension
***   error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
***   [end of output]
***
***   note: This error originates from a subprocess, and is likely not a problem with pip.
***   ERROR: Failed building wheel for insightface
*** ERROR: Could not build wheels for insightface, which is required to install pyproject.toml-based projects
***
*** [notice] A new release of pip available: 22.2.1 -> 23.3.2
*** [notice] To update, run: python.exe -m pip install --upgrade pip
*** Traceback (most recent call last):
***   File "C:\SDAMD\WebUI\stable-diffusion-webui-directml\extensions\sd-webui-roop\install.py", line 27, in <module>
***     subprocess.run(["pip", "install", "-r", req_file], check=True)
***   File "C:\Users\feder\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 524, in run
***     raise CalledProcessError(retcode, process.args,
*** subprocess.CalledProcessError: Command '['pip', 'install', '-r', 'C:\\SDAMD\\WebUI\\stable-diffusion-webui-directml\\extensions\\sd-webui-roop\\requirements.txt']' returned non-zero exit status 1.
***
*** During handling of the above exception, another exception occurred:
***
*** Traceback (most recent call last):
***   File "C:\SDAMD\WebUI\stable-diffusion-webui-directml\extensions\sd-webui-roop\install.py", line 29, in <module>
***     print(f"Failed to install requirements: {e.stderr.decode('utf-8')}")
*** AttributeError: 'NoneType' object has no attribute 'decode'
Launching Web UI with arguments: --use-directml --opt-sub-quad-attention --medvram --sub-quad-q-chunk-size=512 --sub-quad-kv-chunk-size=512 --sub-quad-chunk-threshold=90 --upcast-sampling --opt-channelslast
2023-12-24 07:44:11.589121: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING:tensorflow:From C:\SDAMD\WebUI\stable-diffusion-webui-directml\venv\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Traceback (most recent call last):
  File "C:\SDAMD\WebUI\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "C:\SDAMD\WebUI\stable-diffusion-webui-directml\launch.py", line 44, in main
    start()
  File "C:\SDAMD\WebUI\stable-diffusion-webui-directml\modules\launch_utils.py", line 688, in start
    import webui
  File "C:\SDAMD\WebUI\stable-diffusion-webui-directml\webui.py", line 13, in <module>
    initialize.imports()
  File "C:\SDAMD\WebUI\stable-diffusion-webui-directml\modules\initialize.py", line 34, in imports
    shared_init.initialize()
  File "C:\SDAMD\WebUI\stable-diffusion-webui-directml\modules\shared_init.py", line 26, in initialize
    dml.do_hijack()
  File "C:\SDAMD\WebUI\stable-diffusion-webui-directml\modules\dml\__init__.py", line 74, in do_hijack
    if not torch.dml.has_float64_support(device):
AttributeError: module 'torch' has no attribute 'dml'
Press any key to continue . . .
```

**Comment by patientx** [comment]
This is different from not using "--use-directml" , this happens even if I use it to start the webui.

**Comment by Jyoumon** [comment]
I'm not sure exactly How i fixed it....but After the 3rd clean install....it suddenly works fine...i wish i had an answer now but ...im good i guess?

**Comment by patientx** [comment]
As I said above your post reinstalling torch-directml fixed it.
