### ISSUE TITLE
[Bug]:  mat1 and mat2 must have the same dtype

### ISSUE THREAD

**Issue by imamqaum1** [lshqqytiger/stable-diffusion-webui-directml#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

i'm just install with the following steps but appear this RuntimeError: mat1 and mat2 must have the same dtype, help me for solve the problem

### Steps to reproduce the problem

1. Go to stable-diffusion-webui-directml
2. Open webui-user.bat
4. And wait until RuntimeError: mat1 and mat2 must have the same dtype appear

### What should have happened?

The RuntimeError: mat1 and mat2 must have the same dtype not appear, and stable diffusion can launch

### Commit where the problem happens

 return F.linear(input, self.weight, self.bias) RuntimeError: mat1 and mat2 must have the same dtype

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
ya, i modified webui-user with --medvram
```

### List of extensions

no

### Console logs

```Shell
venv "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: ff558348682fea569785dcfae1f1282cfbefda6b
Installing requirements for Web UI
Launching Web UI with arguments: --medvram
Warning: experimental graphic memory optimization is disabled due to gpu vendor. Currently this optimization is only available for AMDGPUs.
Disabled experimental graphic memory optimizations.
Interrogations are fallen back to cpu. This doesn't affect on image generation. But if you want to use interrogate (CLIP or DeepBooru), check out this issue: https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/10
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
Loading weights [bfcaf07557] from D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\models\Stable-diffusion\768-v-ema.ckpt
loading stable diffusion model: RuntimeError
Traceback (most recent call last):
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\webui.py", line 111, in initialize
    modules.sd_models.load_model()
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\modules\sd_models.py", line 385, in load_model
    checkpoint_config = sd_models_config.find_checkpoint_config(state_dict, checkpoint_info)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\modules\sd_models_config.py", line 100, in find_checkpoint_config
    return guess_model_config_from_state_dict(state_dict, info.filename)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\modules\sd_models_config.py", line 75, in guess_model_config_from_state_dict
    elif is_using_v_parameterization_for_sd2(sd):
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\modules\sd_models_config.py", line 60, in is_using_v_parameterization_for_sd2
    out = (unet(x_test, torch.asarray([999], device=device), context=test_cond) - x_test).mean().item()
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 770, in forward
    emb = self.time_embed(t_emb)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\extensions-builtin\Lora\lora.py", line 178, in lora_Linear_forward
    return lora_forward(self, input, torch.nn.Linear_forward_before_lora(self, input))
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\modules\devices.py", line 229, in forward
    return super().forward(x)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 must have the same dtype


Stable diffusion model failed to load, exiting
Press any key to continue . . .
```

**Comment by lshqqytiger** [comment]
Try adding `--no-half` to commandline arguments.
I already met a similar/same issue occurred on Lora and fixed a few weeks ago.
But it can re-occur due to merged commits of parent repo after fix.
I'll check it again.

**Comment by OpenWrtClub** [comment]
I encountered the same problem, added `--no-half` or reported an error

**Comment by DylwinTFTW** [comment]
Same error as well

**Comment by DylwinTFTW** [comment]
I have the same error, but it only happens when both:
a) Stable Diffusion 2 and 2.1 are selected
b) --no-half isn't selected
