### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'pytorch_lightning'

### ISSUE THREAD

**Issue by shott92** [lshqqytiger/stable-diffusion-webui-directml#349]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

after running webui.sh to install on a clean install of linux Ubuntu 22.04.3 LTS  - Kernel version: 6.2.0-39-generic
With ROCm installed and pre-requisites followed using python 3.10.12 I have an error running the webui.sh script.
Original error was:
`> ModuleNotFoundError: No module named 'pytorch_lightning'`
This was resolved by adding:
`pytorch_lightning==2.1.0` 
to requirements_versions.txt.
And
`pytorch_lightning` 
to requirements.txt.

next error gave
`ModuleNotFoundError: No module named 'pytorch_lightning.utilities.distributed'`

I assume therefore I am using the wrong version of Pytorch_Lightning, I would appreciate knowing the appropriate version, it would also be useful if this could be fixed in the txt files / script for next bug fix release

Thanks

### Steps to reproduce the problem

install clean ubuntu 22.04.03 linux, update and upgrade.
Run:
`sudo apt install wget git python3 python3-venv libgl1 libglib2.0-0'
'sudo apt install python3-pip`
Then
`wget -q https://raw.githubusercontent.com/AUTOMATIC1111/stable-diffusion-webui/master/webui.sh`
Set  WebUI to execute as a programme, then run
`sudo ./Webui.sh`

### What should have happened?

WebUi should have installed and run correctly

### Sysinfo

--dump-sysinfo doesn't run

### Console logs

```Shell
user@ubuntu:~/Programming/stable-diffusion-webui$ ./webui.sh

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye), Fedora 34+ and openSUSE Leap 15.4 or newer.
################################################################

################################################################
Running on user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
Create and activate python venv
################################################################

################################################################
Launching launch.py...
################################################################
Cannot locate TCMalloc (improves CPU memory usage)
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Installing requirements
Launching Web UI with arguments: 
/home/user/Programming/stable-diffusion-webui/venv/lib/python3.10/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/home/user/Programming/stable-diffusion-webui/venv/lib/python3.10/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
Traceback (most recent call last):
  File "/home/user/Programming/stable-diffusion-webui/launch.py", line 48, in <module>
    main()
  File "/home/user/Programming/stable-diffusion-webui/launch.py", line 44, in main
    start()
  File "/home/user/Programming/stable-diffusion-webui/modules/launch_utils.py", line 460, in start
    import webui
  File "/home/user/Programming/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/home/user/Programming/stable-diffusion-webui/modules/initialize.py", line 33, in imports
    from modules import shared_init
  File "/home/user/Programming/stable-diffusion-webui/modules/shared_init.py", line 5, in <module>
    from modules import shared
  File "/home/user/Programming/stable-diffusion-webui/modules/shared.py", line 5, in <module>
    from modules import shared_cmd_options, shared_gradio_themes, options, shared_items, sd_models_types
  File "/home/user/Programming/stable-diffusion-webui/modules/sd_models_types.py", line 1, in <module>
    from ldm.models.diffusion.ddpm import LatentDiffusion
  File "/home/user/Programming/stable-diffusion-webui/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py", line 20, in <module>
    from pytorch_lightning.utilities.distributed import rank_zero_only
ModuleNotFoundError: No module named 'pytorch_lightning.utilities.distributed'
```

**Comment by lshqqytiger** [comment]
This is not an issue of stable-diffusion-webui**-directml**. Please refer to AUTOMATIC1111/stable-diffusion-webui.
