### ISSUE TITLE
[Bug]: Stable Diffusion running on CPU not GPU 

### ISSUE THREAD

**Issue by imamqaum1** [lshqqytiger/stable-diffusion-webui-directml#35]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

![Screenshot 2023-03-09 211944](https://user-images.githubusercontent.com/68838035/224053166-0c546a6e-225c-4eee-8242-e55325ce0e2d.png)

### Steps to reproduce the problem

1. Go to 
3. Running webui-user.bat
4. Go to Img2Img
5. Add your Image

### What should have happened?

Stable Diffusion running on GPU

### Commit where the problem happens

 Could not allocate tensor with 1048576 bytes. There is not enough GPU video memory available!

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
Yes, i modified webui-user.bat with --medvram and --no-half
```

### List of extensions

no

### Console logs

```Shell
venv "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: ff558348682fea569785dcfae1f1282cfbefda6b
Installing requirements for Web UI
Launching Web UI with arguments: --medvram --no-half
Warning: experimental graphic memory optimization is disabled due to gpu vendor. Currently this optimization is only available for AMDGPUs.
Disabled experimental graphic memory optimizations.
Interrogations are fallen back to cpu. This doesn't affect on image generation. But if you want to use interrogate (CLIP or DeepBooru), check out this issue: https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/10
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
Loading weights [bfcaf07557] from D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\models\Stable-diffusion\768-v-ema.ckpt
Creating model from config: D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\configs\stable-diffusion\v2-inference-v.yaml
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Applying cross attention optimization (InvokeAI).
Textual inversion embeddings loaded(0):
Model loaded in 219.0s (load weights from disk: 133.0s, find config: 38.5s, load config: 0.3s, create model: 3.4s, apply weights to model: 38.3s, apply dtype to VAE: 0.3s, load VAE: 2.8s, move model to device: 2.0s, load textual inversion embeddings: 0.3s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Downloading: "https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_caption_capfilt_large.pth" to D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\models\BLIP\model_base_caption_capfilt_large.pth

 10%|███████▌                                                                      | 82.3M/855M [00:36<06:36, 2.04MB/s]Downloading: "https://github.com/AUTOMATIC1111/TorchDeepDanbooru/releases/download/v1/model-resnet_custom_v3.pt" to D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\models\torch_deepdanbooru\model-resnet_custom_v3.pt

  0%|                                                                                           | 0/16 [00:08<?, ?it/s]
Error completing request                                                            | 42.1M/614M [06:18<31:22, 319kB/s]
Arguments: ('task(5bhm9n9sz8w7tot)', 0, '', '', [], <PIL.Image.Image image mode=RGBA size=4000x6000 at 0x264321C5D50>, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 9, 1.5, 0.75, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, 0, 32, 0, '', '', '', [], 0, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 1, 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0) {}
 97%|████████████████████████████████████████████████████████████████████████████▉  | 833M/855M [06:57<00:09, 2.36MB/s]Traceback (most recent call last):                                                 | 42.1M/614M [06:19<1:17:50, 128kB/s]
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\modules\img2img.py", line 171, in img2img
    processed = process_images(p)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\modules\processing.py", line 632, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\modules\processing.py", line 1048, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 322, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 225, in launch_sampling
    return func()
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 322, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\sampling.py", line 150, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 123, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond={"c_crossattn": [cond_in[a:b]], "c_concat": [image_cond_in[a:b]]})
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 167, in forward
    return self.get_v(input * c_in, self.sigma_to_t(sigma), **kwargs) * c_out + input * c_skip
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 177, in get_v
    return self.inner_model.apply_model(x, t, cond)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 858, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1201, in _call_impl
    result = hook(self, input)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\modules\lowvram.py", line 35, in send_me_to_gpu
    module.to(devices.device)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\core\mixins\device_dtype_mixin.py", line 113, in to
    return super().to(*args, **kwargs)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 989, in to
    return self._apply(convert)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  [Previous line repeated 3 more times]
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 664, in _apply
    param_applied = fn(param)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: Could not allocate tensor with 117964800 bytes. There is not enough GPU video memory available!

100%|███████████████████████████████████████████████████████████████████████████████| 855M/855M [07:07<00:00, 2.10MB/s]
  7%|█████▎                                                                      | 43.1M/614M [06:29<1:40:29, 99.3kB/s]load checkpoint from D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\models\BLIP\model_base_caption_capfilt_large.pth
                                                                                                                       Downloading CLIP categories...                                                       | 166M/614M [07:34<03:19, 2.36MB/s]
100%|██████████████████████████████████████████████████████████████████████████████| 80.5k/80.5k [00:00<00:00, 778kB/s]
100%|█████████████████████████████████████████████████████████████████████████████| 1.72M/1.72M [00:01<00:00, 1.55MB/s]
100%|█████████████████████████████████████████████████████████████████████████████| 1.57k/1.57k [00:00<00:00, 1.61MB/s]
100%|█████████████████████████████████████████████████████████████████████████████| 2.62k/2.62k [00:00<00:00, 1.34MB/s]
100%|████████████████████████████████████████████████████████████████████████████████| 614M/614M [11:01<00:00, 974kB/s]
Traceback (most recent call last):█████████████████████████████████████████████████▉| 614M/614M [11:01<00:00, 3.93MB/s]
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\modules\ui.py", line 915, in <lambda>
    fn=lambda *args: process_interrogate(interrogate_deepbooru, *args),
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\modules\ui.py", line 150, in process_interrogate
    return [interrogation_function(ii_singles[mode]), None]
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\modules\ui.py", line 177, in interrogate_deepbooru
    prompt = deepbooru.model.tag(image)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\modules\deepbooru.py", line 44, in tag
    self.start()
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\modules\deepbooru.py", line 36, in start
    self.model.to(devices.device)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 989, in to
    return self._apply(convert)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 664, in _apply
    param_applied = fn(param)
  File "D:\Data Imam\Imam File\web-ui\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 987, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: Could not allocate tensor with 1048576 bytes. There is not enough GPU video memory available!
```

 RX 570 4GB 
AMD Ryzen 5 3500
RAM 8GB

                  
_No response_

**Comment by lshqqytiger** [comment]
Make sure that DirectX Runtime, GPU driver from AMD.com and `torch-directml` are installed.

**Comment by imamqaum1** [comment]
> Make sure that DirectX Runtime, GPU driver from AMD.com and `torch-directml` are installed.

how to make sure that?

**Comment by Yangkro** [comment]
I'm getting the same error, how did you fix it

**Comment by madtunebk** [comment]
RX 570 4GB  <<< it's way better to run on cpu on that video card ,  have 5700 xt 8gb and have better result on CPU ... that gpu ... AMD sucks on AI think
