### ISSUE TITLE
[Bug]: Launch fail importing cv2

### ISSUE THREAD

**Issue by corpsecouch** [lshqqytiger/stable-diffusion-webui-directml#363]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Error when launching webui-user.bat. Console says it can't find cv2.

### Steps to reproduce the problem

1. Double-click on webui-user.bat

### What should have happened?

The webui should load.

### Sysinfo

None. WebUI doesn't even load.

### Console logs

```Shell
venv "C:\Users\Jason\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.7.0
Commit hash: d500e58a65d99bfaa9c7bb0da6c3eb5704fadf25
Launching Web UI with arguments: --use-directml --upcast-sampling
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Traceback (most recent call last):
  File "C:\Users\Jason\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "C:\Users\Jason\stable-diffusion-webui-directml\launch.py", line 44, in main
    start()
  File "C:\Users\Jason\stable-diffusion-webui-directml\modules\launch_utils.py", line 687, in start
    import webui
  File "C:\Users\Jason\stable-diffusion-webui-directml\webui.py", line 13, in <module>
    initialize.imports()
  File "C:\Users\Jason\stable-diffusion-webui-directml\modules\initialize.py", line 34, in imports
    shared_init.initialize()
  File "C:\Users\Jason\stable-diffusion-webui-directml\modules\shared_init.py", line 26, in initialize
    dml.do_hijack()
  File "C:\Users\Jason\stable-diffusion-webui-directml\modules\dml\__init__.py", line 67, in do_hijack
    import modules.dml.hijack # pylint: disable=unused-import
  File "C:\Users\Jason\stable-diffusion-webui-directml\modules\dml\hijack\__init__.py", line 4, in <module>
    import modules.dml.hijack.realesrgan_model
  File "C:\Users\Jason\stable-diffusion-webui-directml\modules\dml\hijack\realesrgan_model.py", line 3, in <module>
    from realesrgan import RealESRGANer
  File "C:\Users\Jason\stable-diffusion-webui-directml\venv\lib\site-packages\realesrgan\__init__.py", line 2, in <module>
    from .archs import *
  File "C:\Users\Jason\stable-diffusion-webui-directml\venv\lib\site-packages\realesrgan\archs\__init__.py", line 2, in <module>
    from basicsr.utils import scandir
  File "C:\Users\Jason\stable-diffusion-webui-directml\venv\lib\site-packages\basicsr\__init__.py", line 3, in <module>
    from .archs import *
  File "C:\Users\Jason\stable-diffusion-webui-directml\venv\lib\site-packages\basicsr\archs\__init__.py", line 5, in <module>
    from basicsr.utils import get_root_logger, scandir
  File "C:\Users\Jason\stable-diffusion-webui-directml\venv\lib\site-packages\basicsr\utils\__init__.py", line 4, in <module>
    from .img_process_util import USMSharp, usm_sharp
  File "C:\Users\Jason\stable-diffusion-webui-directml\venv\lib\site-packages\basicsr\utils\img_process_util.py", line 1, in <module>
    import cv2
  File "C:\Users\Jason\stable-diffusion-webui-directml\venv\lib\site-packages\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\Jason\stable-diffusion-webui-directml\venv\lib\site-packages\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "C:\Users\Jason\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing cv2: The specified module could not be found.
Press any key to continue . . .
```

### Additional information

Trying to install opencv-python says that numpy>=1.21.2 already satisfies the requirement.

This is a new system with an Intel CPU and a 7800xt.

**Comment by lshqqytiger** [comment]
https://github.com/opencv/opencv-python/issues/856#issuecomment-1713214860

**Comment by corpsecouch** [comment]
Thanks! A couple callouts from that thread specific to Win 11 Home N:
- The 2015 C++ Redistributable isn't installable
- Installing the media pack is found in a different place

Here are the steps to get the media pack and solve this issue on Win 11 Home N:
1. Right-click "Start" icon
2. Click on "System"
3. Scroll to find "Optional Features"
4. Click on "Optional Features"
5. Click "View Features"
6. Search or scroll for "Media Feature Pack"
7. Click the check box
8. Click "Next"
9. Click "Install"
10. Wait for it to install
11. Restart your system if it says to
12. Now you're good to go
