### ISSUE TITLE
[Bug]: ONNX tab is missing

### ISSUE THREAD

**Issue by k0zer0g** [lshqqytiger/stable-diffusion-webui-directml#372]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I don't understand how to optimize the models. There was an ONNX tab where I optimized them, but now this tab is missing.
![Снимок экрана 2024-02-08 002405](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/77258647/7dccf8a9-7926-4865-9380-7ad40d2ff2bd)

### Steps to reproduce the problem

1. Open the webui

### What should have happened?

I want to understand how to optimize models now

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

[sysinfo-2024-02-07-19-32.json](https://github.com/lshqqytiger/stable-diffusion-webui-directml/files/14200674/sysinfo-2024-02-07-19-32.json)

### Console logs

```Shell
(venv) C:\StableDiffuionWebUI\stable-diffusion-webui-directml>webui-user
venv "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.7.0
Commit hash: adaea46e1c19d9a7091f89b0a7c6e66dfa732528
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --use-directml --medvram --opt-sub-quad-attention --opt-split-attention-v1
ONNX: selected=CPUExecutionProvider, available=['AzureExecutionProvider', 'CPUExecutionProvider']
ControlNet preprocessor location: C:\StableDiffuionWebUI\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\downloads
2024-02-08 00:19:33,571 - ControlNet - INFO - ControlNet v1.1.440
2024-02-08 00:19:33,778 - ControlNet - INFO - ControlNet v1.1.440
2024-02-08 00:19:34,356 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 7.7s (prepare environment: 11.1s, initialize shared: 3.1s, load scripts: 2.3s, create ui: 0.9s, gradio launch: 0.4s).
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\encoders.py", line 152, in jsonable_encoder
    data = dict(obj)
TypeError: '_abc._abc_data' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\encoders.py", line 157, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 404, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\starlette\middleware\cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\starlette\middleware\cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\routing.py", line 255, in app
    content = await serialize_response(
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\routing.py", line 152, in serialize_response
    return jsonable_encoder(response_content)
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\encoders.py", line 131, in jsonable_encoder
    jsonable_encoder(
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\encoders.py", line 161, in jsonable_encoder
    return jsonable_encoder(
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\encoders.py", line 117, in jsonable_encoder
    encoded_value = jsonable_encoder(
  File "C:\StableDiffuionWebUI\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\encoders.py", line 160, in jsonable_encoder
    raise ValueError(errors) from e
ValueError: [TypeError("'_abc._abc_data' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
You have disabled the safety checker for <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> by passing `safety_checker=None`. Ensure that you abide to the conditions of the Stable Diffusion license and do not expose unfiltered results in services or applications open to the public. Both the diffusers team and Hugging Face strongly recommend to keep the safety filter enabled in all public facing circumstances, disabling it only for use-cases that involve analyzing network behavior or auditing its results. For more information, please have a look at https://github.com/huggingface/diffusers/pull/254 .
Applying attention optimization: sub-quadratic... done.
```

### Additional information

rx580 8gb, 16gb ram

**Comment by Ziedelth** [comment]
Same issue as this ticket https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/370

**Comment by shanold** [comment]
I cant even launch it with --onnx in command line args. get "launch.py: error: unrecognized arguments: --onnx"

**Comment by Omen090909** [comment]
same issue, also, those errors over gui all around, anyone found solution?

**Comment by Ziedelth** [comment]
The best solution would be to return to a previous state of the project.

To do this, simply issue the command
`git checkout d500e58a65d99bfaa9c7bb0da6c3eb5704fadf25`

This command will remove the latest changes that are causing problems.
And if you want to go back to the latest version of the project, simply issue the command 
`git switch - && git pull`

**Comment by lshqqytiger** [comment]
You don't need to optimize the models manually. It will automatically optimize it when you try to generate an image with a new model that hasn't been optimized. You can find converted/optimized models under `./models/ONNX/cache`.
https://github.com/lshqqytiger/stable-diffusion-webui-directml/discussions/149#discussioncomment-8392257

**Comment by k0zer0g** [comment]
I ran into another problem.
I can't optimize any model.
Please help me in this situation.

ONNX: Failed to convert model: model='cleanlinearmix_final.safetensors', error=Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 14 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues.

**Comment by lshqqytiger** [comment]
https://github.com/lshqqytiger/stable-diffusion-webui-directml/discussions/149#discussioncomment-8392257
You should follow `Extra instruction for DirectML users.`.
PyTorch 2.0.0 is not compatible with Olive, but there's no release of torch-directml built with PyTorch 2.2.0. So we have to use PyTorch built with CPU.

**Comment by k0zer0g** [comment]
Thank you very much!
I've already entered these commands, but for some reason they didn't work the first time. Now I have re-entered the commands, and everything has become great.
