### ISSUE TITLE
[Bug]: AttributeError: module 'diffusers.schedulers' has no attribute 'scheduling_lcm'. Did you mean: 'scheduling_ddim'?

### ISSUE THREAD

**Issue by brknsoul** [lshqqytiger/stable-diffusion-webui-directml#374]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

```
fatal: No names found, cannot describe anything.
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: 1.7.0
Commit hash: 9e8f9bcf14f68099bb3562488361bd1a8393b2a5
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
E:\SM\Data\Packages\A1111-DirectML\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
E:\SM\Data\Packages\A1111-DirectML\extensions\sd-webui-controlnet\install.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Launching Web UI with arguments: --use-directml --medvram --api --no-half --theme dark
Traceback (most recent call last):
  File "E:\SM\Data\Packages\A1111-DirectML\launch.py", line 48, in <module>
    main()
  File "E:\SM\Data\Packages\A1111-DirectML\launch.py", line 44, in main
    start()
  File "E:\SM\Data\Packages\A1111-DirectML\modules\launch_utils.py", line 676, in start
    import webui
  File "E:\SM\Data\Packages\A1111-DirectML\webui.py", line 13, in <module>
    initialize.imports()
  File "E:\SM\Data\Packages\A1111-DirectML\modules\initialize.py", line 34, in imports
    shared_init.initialize()
  File "E:\SM\Data\Packages\A1111-DirectML\modules\shared_init.py", line 28, in initialize
    directml_do_hijack()
  File "E:\SM\Data\Packages\A1111-DirectML\modules\dml\__init__.py", line 69, in directml_do_hijack
    import modules.dml.hijack # pylint: disable=unused-import
  File "E:\SM\Data\Packages\A1111-DirectML\modules\dml\hijack\__init__.py", line 5, in <module>
    import modules.dml.hijack.diffusers
  File "E:\SM\Data\Packages\A1111-DirectML\modules\dml\hijack\diffusers.py", line 172, in <module>
    ) -> Union[diffusers.schedulers.scheduling_lcm.LCMSchedulerOutput, Tuple]:
AttributeError: module 'diffusers.schedulers' has no attribute 'scheduling_lcm'. Did you mean: 'scheduling_ddim'?

Process finished with exit code 1
```

### Steps to reproduce the problem

Launch a1111-directml

### What should have happened?

.

### Sysinfo

Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: 1.7.0

### Console logs

```Shell
fatal: No names found, cannot describe anything.
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: 1.7.0
Commit hash: 9e8f9bcf14f68099bb3562488361bd1a8393b2a5
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
E:\SM\Data\Packages\A1111-DirectML\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
E:\SM\Data\Packages\A1111-DirectML\extensions\sd-webui-controlnet\install.py:2: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Launching Web UI with arguments: --use-directml --medvram --api --no-half --theme dark
Traceback (most recent call last):
  File "E:\SM\Data\Packages\A1111-DirectML\launch.py", line 48, in <module>
    main()
  File "E:\SM\Data\Packages\A1111-DirectML\launch.py", line 44, in main
    start()
  File "E:\SM\Data\Packages\A1111-DirectML\modules\launch_utils.py", line 676, in start
    import webui
  File "E:\SM\Data\Packages\A1111-DirectML\webui.py", line 13, in <module>
    initialize.imports()
  File "E:\SM\Data\Packages\A1111-DirectML\modules\initialize.py", line 34, in imports
    shared_init.initialize()
  File "E:\SM\Data\Packages\A1111-DirectML\modules\shared_init.py", line 28, in initialize
    directml_do_hijack()
  File "E:\SM\Data\Packages\A1111-DirectML\modules\dml\__init__.py", line 69, in directml_do_hijack
    import modules.dml.hijack # pylint: disable=unused-import
  File "E:\SM\Data\Packages\A1111-DirectML\modules\dml\hijack\__init__.py", line 5, in <module>
    import modules.dml.hijack.diffusers
  File "E:\SM\Data\Packages\A1111-DirectML\modules\dml\hijack\diffusers.py", line 172, in <module>
    ) -> Union[diffusers.schedulers.scheduling_lcm.LCMSchedulerOutput, Tuple]:
AttributeError: module 'diffusers.schedulers' has no attribute 'scheduling_lcm'. Did you mean: 'scheduling_ddim'?

Process finished with exit code 1
```

**Comment by lshqqytiger** [comment]
Run these commands.
```
.\venv\Scripts\activate
pip install diffusers --upgrade
```
And try again.

**Comment by brknsoul** [comment]
Fixed it by deleting venv and reinstalling it. :-P

**Comment by 18331166003i** [comment]
咋解决的哥们

**Comment by 18331166003i** [comment]
我也是这个AttributeError: module 'diffusers.schedulers' has no attribute 'scheduling_lcm'. Did you mean: 'scheduling_ddim'?

**Comment by lshqqytiger** [comment]
Upgrade `diffusers` to the latest version.

**Comment by 18331166003i** [comment]
> 升级到最新版本。`diffusers`

我里面显示已经是最新版本了

**Comment by lshqqytiger** [comment]
`diffusers==0.27.2` has `.schedulers.scheduling_lcm`. Which version are you using?
![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/39524005/a1203e96-5fe8-4bc3-b8ca-25df21a18eae)
