### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'optimum'

### ISSUE THREAD

**Issue by 0bluman0** [lshqqytiger/stable-diffusion-webui-directml#379]
### Checklist

- [ ] The issue exists after disabling all extensions
- [x] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

when I start stablediffusion I get the error I mentioned in the subject, I don't know how to solve it, I have an amd 6800xt card.

### Steps to reproduce the problem

----

### What should have happened?

It worked until yesterday

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

----

### Console logs

```Shell
Requirement already satisfied: certifi>=2017.4.17 in d:\stable-diffusion-webui-directml\venv\lib\site-packages (from requests->torchvision==0.15.1) (2024.2.2)
Requirement already satisfied: idna<4,>=2.5 in d:\stable-diffusion-webui-directml\venv\lib\site-packages (from requests->torchvision==0.15.1) (3.6)
Requirement already satisfied: mpmath>=0.19 in d:\stable-diffusion-webui-directml\venv\lib\site-packages (from sympy->torch==2.0.0) (1.3.0)

[notice] A new release of pip available: 22.2.1 -> 24.0
[notice] To update, run: D:\stable-diffusion-webui-directml\venv\Scripts\python.exe -m pip install --upgrade pip
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
D:\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "D:\stable-diffusion-webui-directml\launch.py", line 39, in main
    prepare_environment()
  File "D:\stable-diffusion-webui-directml\modules\launch_utils.py", line 641, in prepare_environment
    from modules.onnx_impl import initialize_olive
  File "D:\stable-diffusion-webui-directml\modules\onnx_impl\__init__.py", line 7, in <module>
    import optimum.onnxruntime
ModuleNotFoundError: No module named 'optimum'
Premere un tasto per continuare . . .
```

### Additional information

----

**Comment by lshqqytiger** [comment]
Remove `venv` folder and try again.

**Comment by SunGreen777** [comment]
Thanks It works! And if briefly, what's new?

**Comment by 0bluman0** [comment]
Thanks It works!
