### ISSUE TITLE
[Bug]: Embeddings not showing up in the UI when using ONNX

### ISSUE THREAD

**Issue by waylaa** [lshqqytiger/stable-diffusion-webui-directml#388]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I am unable to select any embedding due to them not showing up in the UI.
![image](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/66755323/25d4727a-1437-419b-b910-cf41af76f1ad)

### Steps to reproduce the problem

1. Place any embedding file in the 'embeddings' folder.
2. Open webui-user.bat/.sh and click the 'Textual Inversion' tab

### What should have happened?

Embeddings should have been shown so I can put them on the prompt.

### What browsers do you use to access the UI ?

Mozilla Firefox

### Sysinfo

I am unable to post syninfo because of this error:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\venv\lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 412, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\venv\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\venv\lib\site-packages\starlette\applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\venv\lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
    raise exc
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\venv\lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\venv\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\venv\lib\site-packages\starlette\middleware\gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\venv\lib\site-packages\starlette\middleware\gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\venv\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\venv\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\venv\lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\venv\lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\venv\lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\routing.py", line 237, in app
    raw_response = await run_endpoint_function(
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\routing.py", line 165, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\venv\lib\site-packages\starlette\concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\modules\ui.py", line 1892, in download_sysinfo
    text = sysinfo.get()
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\modules\sysinfo.py", line 49, in get
    res = get_dict()
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\modules\sysinfo.py", line 75, in get_dict
    gpu = DeviceProperties(devices.device)
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\modules\dml\device_properties.py", line 13, in __init__
    self.name = torch.dml.get_device_name(device)
  File "D:\AI\Applications\Stable Diffusion (ONNX)\stable-diffusion-webui-directml\venv\lib\site-packages\torch\__init__.py", line 1932, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'torch' has no attribute 'dml'
```

### Console logs

No error is shown.

### Additional information

Adrenaline driver version: 24.1.1
HIP SDK is also installed under C:\Program Files\AMD\ROCm\5.7 because of #385

**Comment by lshqqytiger** [comment]
You should merge embeddings into the model.
