### ISSUE TITLE
[Bug]: No module named 'keras.__internal__'

### ISSUE THREAD

**Issue by maildovillas** [lshqqytiger/stable-diffusion-webui-directml#390]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I'm fairly new to Automatic1111 and I've been using this branch for a while, but ever since doing a clean install today, I keep getting the error "No module named 'keras.__internal__'". I'm on a Windows running with an AMD GPU.

Just to be sure, I tried using

`pip install tensorflow`

and also tried reinstalling Python completely, but it didn't work.

### Steps to reproduce the problem

Opening up webui-user.bat results in the problem.

### What should have happened?

It should've opened Automatic1111.

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

I can't get it, it says: 

```
venv "C:\Users\leona\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
2024-02-15 23:23:53.944362: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-02-15 23:23:54.687879: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
C:\Users\leona\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Traceback (most recent call last):
  File "C:\Users\leona\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "C:\Users\leona\stable-diffusion-webui-directml\launch.py", line 29, in main
    filename = launch_utils.dump_sysinfo()
  File "C:\Users\leona\stable-diffusion-webui-directml\modules\launch_utils.py", line 689, in dump_sysinfo
    text = sysinfo.get()
  File "C:\Users\leona\stable-diffusion-webui-directml\modules\sysinfo.py", line 49, in get
    res = get_dict()
  File "C:\Users\leona\stable-diffusion-webui-directml\modules\sysinfo.py", line 75, in get_dict
    gpu = DeviceProperties(devices.device)
  File "C:\Users\leona\stable-diffusion-webui-directml\modules\dml\device_properties.py", line 13, in __init__
    self.name = torch.dml.get_device_name(device)
AttributeError: module 'torch' has no attribute 'dml'
```

### Console logs

```Shell
venv "C:\Users\leona\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.7.0
Commit hash: 7ed2ff1c35955af6a0ff37d0f8299fea82dc11d9
2024-02-15 23:13:59.186471: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-02-15 23:14:00.161741: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
C:\Users\leona\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Olive: Failed to load olive-ai: Failed to import transformers.models.gpt2.modeling_tf_gpt2 because of the following error (look up to see its traceback):
No module named 'keras.__internal__'
Launching Web UI with arguments: --skip-torch-cuda-test --use-directml
Style database not found: C:\Users\leona\stable-diffusion-webui-directml\styles.csv
Traceback (most recent call last):
  File "C:\Users\leona\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\utils\import_utils.py", line 1086, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Program Files\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\leona\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\modeling_tf_utils.py", line 76, in <module>
    from keras.__internal__ import KerasTensor
ModuleNotFoundError: No module named 'keras.__internal__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\leona\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\utils\import_utils.py", line 1086, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Program Files\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\leona\stable-diffusion-webui-directml\venv\lib\site-packages\optimum\onnxruntime\modeling_diffusion.py", line 41, in <module>
    from ..exporters.onnx import main_export
  File "C:\Users\leona\stable-diffusion-webui-directml\venv\lib\site-packages\optimum\exporters\__init__.py", line 16, in <module>
    from .tasks import TasksManager  # noqa
  File "C:\Users\leona\stable-diffusion-webui-directml\venv\lib\site-packages\optimum\exporters\tasks.py", line 52, in <module>
    from transformers import TFPreTrainedModel
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "C:\Users\leona\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\utils\import_utils.py", line 1076, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\leona\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\utils\import_utils.py", line 1088, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
No module named 'keras.__internal__'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\leona\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "C:\Users\leona\stable-diffusion-webui-directml\launch.py", line 44, in main
    start()
  File "C:\Users\leona\stable-diffusion-webui-directml\modules\launch_utils.py", line 677, in start
    import webui
  File "C:\Users\leona\stable-diffusion-webui-directml\webui.py", line 13, in <module>
    initialize.imports()
  File "C:\Users\leona\stable-diffusion-webui-directml\modules\initialize.py", line 34, in imports
    shared_init.initialize()
  File "C:\Users\leona\stable-diffusion-webui-directml\modules\shared_init.py", line 58, in initialize
    initialize_onnx()
  File "C:\Users\leona\stable-diffusion-webui-directml\modules\onnx_impl\__init__.py", line 236, in initialize
    from .pipelines.onnx_stable_diffusion_xl_pipeline import OnnxStableDiffusionXLPipeline
  File "C:\Users\leona\stable-diffusion-webui-directml\modules\onnx_impl\pipelines\onnx_stable_diffusion_xl_pipeline.py", line 8, in <module>
    class OnnxStableDiffusionXLPipeline(CallablePipelineBase, optimum.onnxruntime.ORTStableDiffusionXLPipeline):
  File "C:\Users\leona\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\utils\import_utils.py", line 1076, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\leona\stable-diffusion-webui-directml\venv\lib\site-packages\transformers\utils\import_utils.py", line 1088, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import optimum.onnxruntime.modeling_diffusion because of the following error (look up to see its traceback):
Failed to import transformers.modeling_tf_utils because of the following error (look up to see its traceback):
No module named 'keras.__internal__'
```

**Comment by ChiIIerr** [comment]
Getting the same thing here.

**Comment by ChiIIerr** [comment]
Not even kidding, found a youtube comment with a solution

conda activate Automatic1111_olive

cd sd-test

cd stable-diffusion-webui-directml

venv\Scripts\activate



pip install onnxruntime-directml

pip install torch-directml
pip install keras

pip install tensorflow

**Comment by lumiamilk** [comment]
same question

**Comment by EygenCat** [comment]
The same problem, I installed a new version from scratch.
[16022024.txt](https://github.com/lshqqytiger/stable-diffusion-webui-directml/files/14309395/16022024.txt)

**Comment by f1am3d** [comment]
same

**Comment by notloged** [comment]
same

**Comment by notloged** [comment]
just a git pull to get the fix? because I always get the same error

**Comment by lshqqytiger** [comment]
Can't reproduce with fresh install.
Remove `venv` folder then the problem will be solved.
