### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'realesrgan' on clean install

### ISSUE THREAD

**Issue by Bercraft** [lshqqytiger/stable-diffusion-webui-directml#403]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Fails to start after clean installation with --use-directml

### Steps to reproduce the problem

git clone url
start  with --use-directml

### What should have happened?

normally open

### Sysinfo

[sysinfo-2024-03-02-14-45.json](https://github.com/lshqqytiger/stable-diffusion-webui-directml/files/14469762/sysinfo-2024-03-02-14-45.json)

### Console logs

```Shell
venv "G:\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.8.0-RC
Commit hash: 828f558cc428683f3d807db538e064281903d067
Installing onnxruntime-directml
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
G:\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --skip-torch-cuda-test --use-directml
DirectML initialization failed: No module named 'torch_directml'
Traceback (most recent call last):
  File "G:\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "G:\stable-diffusion-webui-directml\launch.py", line 44, in main
    start()
  File "G:\stable-diffusion-webui-directml\modules\launch_utils.py", line 663, in start
    import webui
  File "G:\stable-diffusion-webui-directml\webui.py", line 13, in <module>
    initialize.imports()
  File "G:\stable-diffusion-webui-directml\modules\initialize.py", line 36, in imports
    shared_init.initialize()
  File "G:\stable-diffusion-webui-directml\modules\shared_init.py", line 31, in initialize
    directml_do_hijack()
  File "G:\stable-diffusion-webui-directml\modules\dml\__init__.py", line 69, in directml_do_hijack
    import modules.dml.hijack # pylint: disable=unused-import
  File "G:\stable-diffusion-webui-directml\modules\dml\hijack\__init__.py", line 4, in <module>
    import modules.dml.hijack.realesrgan_model
  File "G:\stable-diffusion-webui-directml\modules\dml\hijack\realesrgan_model.py", line 3, in <module>
    from realesrgan import RealESRGANer
ModuleNotFoundError: No module named 'realesrgan'
Premere un tasto per continuare . . .
```

**Comment by Bercraft** [comment]
Inside requirements.txt realesrgan is missing but adding caused other problems

**Comment by Bercraft** [comment]
Its solved in latest commit thank you.
