### ISSUE TITLE
[Bug]: RuntimeError: Found no NVIDIA driver

### ISSUE THREAD

**Issue by max6186** [lshqqytiger/stable-diffusion-webui-directml#411]
### Checklist

- [ ] The issue exists after disabling all extensions
- [ ] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

this is my first time I install this and I have Radeon RX 580, and for some reasons it keep showing this message.

### Steps to reproduce the problem

1. I start the software 2. I try to generate image.

### What should have happened?

I just want generate images.

### What browsers do you use to access the UI ?

Microsoft Edge.

### Sysinfo

[sysinfo-2024-03-05-15-05.json](https://github.com/lshqqytiger/stable-diffusion-webui-directml/files/14497274/sysinfo-2024-03-05-15-05.json)

### Console logs

```Shell
venv "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.8.0-RC
Commit hash: 25a3b6cbeea8a07afd5e4594afc2f1c79f41ac1a
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --skip-torch-cuda-test
Warning: caught exception 'Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx', memory monitor disabled
F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\venv\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
ONNX: selected=CUDAExecutionProvider, available=['AzureExecutionProvider', 'CPUExecutionProvider']
Loading weights [6ce0161689] from F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\configs\v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 5.5s (prepare environment: 10.8s, initialize shared: 1.8s, other imports: 0.2s, load scripts: 1.3s, create ui: 0.7s, gradio launch: 0.7s).
Applying attention optimization: InvokeAI... done.
loading stable diffusion model: RuntimeError
Traceback (most recent call last):
  File "C:\Users\One.Epic.Gamer\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\One.Epic.Gamer\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\One.Epic.Gamer\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\modules\initialize.py", line 148, in load_model
    shared.sd_model  # noqa: B018
  File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\modules\shared_items.py", line 148, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\modules\sd_models.py", line 627, in get_sd_model
    load_model()
  File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\modules\sd_models.py", line 788, in load_model
    with devices.autocast(), torch.no_grad():
  File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\modules\devices.py", line 234, in autocast
    if has_xpu() or has_mps() or cuda_no_autocast():
  File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\modules\devices.py", line 28, in cuda_no_autocast
    device_id = get_cuda_device_id()
  File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\modules\devices.py", line 40, in get_cuda_device_id
    ) or torch.cuda.current_device()
  File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\venv\lib\site-packages\torch\cuda\__init__.py", line 787, in current_device
    _lazy_init()
  File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\venv\lib\site-packages\torch\cuda\__init__.py", line 302, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx


Stable diffusion model failed to load
Using already loaded model v1-5-pruned-emaonly.safetensors [6ce0161689]: done in 0.0s
*** Error completing request
*** Arguments: ('task(err0y222bc5r5za)', <gradio.routes.Request object at 0x0000017359554760>, 'sword', '', [], 20, 'DPM++ 2M Karras', 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], 0, False, '', 0.8, -1, False, -1, 0, 0, 0, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\modules\txt2img.py", line 110, in txt2img
        processed = processing.process_images(p)
      File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\modules\processing.py", line 787, in process_images
        res = process_images_inner(p)
      File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\modules\processing.py", line 948, in process_images_inner
        with devices.autocast():
      File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\modules\devices.py", line 234, in autocast
        if has_xpu() or has_mps() or cuda_no_autocast():
      File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\modules\devices.py", line 28, in cuda_no_autocast
        device_id = get_cuda_device_id()
      File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\modules\devices.py", line 40, in get_cuda_device_id
        ) or torch.cuda.current_device()
      File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\venv\lib\site-packages\torch\cuda\__init__.py", line 787, in current_device
        _lazy_init()
      File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\venv\lib\site-packages\torch\cuda\__init__.py", line 302, in _lazy_init
        torch._C._cuda_init()
    RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

---
```

**Comment by lshqqytiger** [comment]
You need `--use-directml` or `--use-zluda` instead of `--skip-torch-cuda-test` if you are not using NVIDIA cards.

**Comment by max6186** [comment]
using `--use-directml` result to this:

`
venv "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.8.0-RC
Commit hash: 25a3b6cbeea8a07afd5e4594afc2f1c79f41ac1a
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --use-directml
DirectML initialization failed: No module named 'torch_directml'
F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\venv\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Traceback (most recent call last):
  File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\launch.py", line 44, in main
    start()
  File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\modules\launch_utils.py", line 663, in start
    import webui
  File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\webui.py", line 13, in <module>
    initialize.imports()
  File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\modules\initialize.py", line 36, in imports
    shared_init.initialize()
  File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\modules\shared_init.py", line 31, in initialize
    directml_do_hijack()
  File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\modules\dml\__init__.py", line 76, in directml_do_hijack
    if not torch.dml.has_float64_support(device):
  File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\venv\lib\site-packages\torch\__init__.py", line 1932, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'torch' has no attribute 'dml'
Press any key to continue . . .
`

and using `--use-zluda` result this error:

`
venv "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
WARNING: ZLUDA works best with SD.Next. Please consider migrating to SD.Next.
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.8.0-RC
Commit hash: 25a3b6cbeea8a07afd5e4594afc2f1c79f41ac1a
Traceback (most recent call last):
  File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\launch.py", line 39, in main
    prepare_environment()
  File "F:\SteamGames\steamapps\common\Skyrim Special Edition\MO2\Tools\gg\ROAMod\ROAMod\verCon\WFP\dd\we\stable-diffusion-webui-directml\modules\launch_utils.py", line 568, in prepare_environment
    raise RuntimeError(
RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check
Press any key to continue . . .
`

**Comment by lshqqytiger** [comment]
`--use-directml`: remove `venv` folder and try again.
`--use-zluda`: you need to follow extra steps.

**Comment by max6186** [comment]
it worked thanks

**Comment by pduggi-cf** [comment]
@max6186 was it the `zluda` or `directml` that worked for you?

**Comment by lshqqytiger** [comment]
Both should work if your card is compatible.

**Comment by Flashwalker** [comment]
I run linux in hybrid graphics mode.
script fails to start.

```
export __NV_PRIME_RENDER_OFFLOAD=1
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0
export __VK_LAYER_NV_optimus=NVIDIA_only
export LIBVA_DRIVER_NAME=nvidia

export LANG=en_US.UTF-8
export LANGUAGE=en_US
export LC_ALL=en_US.UTF-8

./webui.sh --skip-torch-cuda-test
```

<details>

```
...
################################################################
Launching launch.py...
################################################################
glibc version is 2.35
Cannot locate TCMalloc. Do you have tcmalloc or google-perftool installed on your system? (improves CPU memory usage)
fatal: No names found, cannot describe anything.
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Version: 1.8.0-RC
Commit hash: bef51aed032c0aaa5cfd80445bc4cf0d85b408b5
Traceback (most recent call last):
  File "/home/user/stable-diffusion-webui/launch.py", line 48, in <module>
    main()
  File "/home/user/stable-diffusion-webui/launch.py", line 39, in main
    prepare_environment()
  File "/home/user/stable-diffusion-webui/modules/launch_utils.py", line 421, in prepare_environment
    if not requirements_met(requirements_file):
  File "/home/user/stable-diffusion-webui/modules/launch_utils.py", line 311, in requirements_met
    if packaging.version.parse(version_required) != packaging.version.parse(version_installed):
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/packaging/version.py", line 52, in parse
    return Version(version)
  File "/home/user/stable-diffusion-webui/venv/lib/python3.10/site-packages/packaging/version.py", line 196, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object

```
</details>

**Comment by Flashwalker** [comment]
$ ./webui.sh --skip-torch-cuda-test

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye), Fedora 34+ and openSUSE Leap 15.4 or newer.
################################################################

################################################################
Running on user user
################################################################

################################################################
Clone stable-diffusion-webui
################################################################
Cloning into 'stable-diffusion-webui'...
remote: Enumerating objects: 32422, done.
remote: Counting objects: 100% (369/369), done.
remote: Compressing objects: 100% (209/209), done.
error: RPC failed; curl 92 HTTP/2 stream 0 was not closed cleanly: CANCEL (err 8)
error: 3467 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
./webui.sh: line 196: cd: stable-diffusion-webui/: No such file or directory
ERROR: Can't cd to /home/user/automatic/stable-diffusion-webui/, aborting...

**Comment by Gooferball69** [comment]
> Both should work if your card is compatible.


> `--use-directml`: remove `venv` folder and try again.

try again with what?

**Comment by nick-demidenko** [comment]
> depends on your gpu. For GCN cards (~Radeon VII), `--use-directml` For other newer cards, `--use-zluda` that is recommended or `--use-directml` that also works.

Hello Seunghoon Lee! 

Thank you for your replies. 
But what if I want to use CPU? 

The "--use-directml" attribute is not recognized.  
I assume it is meant for Radeon cards. 

I will try "--use-zluda" but I am not sure if it will work if I only have an integrated card. 
I will update on results.

**Comment by Harbitos** [comment]
Hello! Help please. The above did not help me. Deleting the venv folder did not help. The RX580 graphics card gives these errors: 
![Screenshot_1](https://github.com/user-attachments/assets/e43c2710-aa5c-4183-b65f-8f8453019377)
![Screenshot_2](https://github.com/user-attachments/assets/9d3a4e9c-6207-429a-bbea-3e11d0ce305f)
![Screenshot_3](https://github.com/user-attachments/assets/e8f182b1-ca1c-4eec-9112-ce5ae5e0a31a)
![Screenshot_4](https://github.com/user-attachments/assets/f0e145dc-2dfc-45f8-80d2-4c8202516a27)

**Comment by cletuslamcf** [comment]
> depends on your gpu. For GCN cards (~Radeon VII), `--use-directml` For other newer cards, `--use-zluda` that is recommended or `--use-directml` that also works.

Hi, how to solve the error if I am using Intel (R) Iris(R) Xe Graphics. Encounter the same error "RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx"

**Comment by lshqqytiger** [comment]
For Intel Iris Xe, you can use `--use-directml` or OpenVINO ([SD.Next](https://github.com/vladmandic/automatic/wiki/OpenVINO))
