### ISSUE TITLE
[Bug]: Found no NVIDIA driver on your system

### ISSUE THREAD

**Issue by Pandora1993** [lshqqytiger/stable-diffusion-webui-directml#417]
### Checklist

- [ ] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

I just installed the web ui to use stable diffusion, I followed the instructions. When running the webui-user.bat I got an error that needed to fix this command set COMMANDLINE ARGS=--skip-torch-cuda-TEST and edit the file with notes, then I ran it again and started downloading the data without problem. Then automatically opened the browser with the stable diffusion version ready to use. I just put a pront and look to see the result, but it is not capable of making images, this error jumps out at me:

RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
Time taken: 0.0 sec.

I don't know what I'm doing wrong

### Steps to reproduce the problem

1.I follow the installation steps
2.I write the commands in the file, one of them needed for the installation to follow (--skip-torch-cuda-test)
set COMMANDLINE_ARGS=--skip-torch-cuda-test --opt-sub-quad-attention --lowvram --disable-nan-check --autolaunch
3.Everything seems to be going well until I hit the generate image button

### What should have happened?

WebUI should create the image

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

Nombre del SO	Microsoft Windows 11 Pro
Versión	10.0.22631 compilación 22631
Descripción adicional del SO 	No disponible
Fabricante del SO	Microsoft Corporation
Nombre del sistema	PANDORA
Fabricante del sistema	ASUS
Modelo del sistema	System Product Name
Tipo de sistema	PC basado en x64
SKU del sistema	SKU
Procesador	AMD Ryzen 7 5700X 8-Core Processor, 3401 Mhz, 8 procesadores principales, 16 procesadores lógicos
Versión y fecha de BIOS	American Megatrends Inc. 3404, 07/10/2023
Versión de SMBIOS	3.3
Versión de controladora integrada	255.255
Modo de BIOS	UEFI
Fabricante de la placa base	ASUSTeK COMPUTER INC.
Producto de placa base	TUF GAMING B550M-PLUS
Versión de la placa base	Rev X.0x
Rol de plataforma	Escritorio
Estado de arranque seguro	Desactivada
Configuración de PCR7	Se necesita elevación de privilegios para ver
Directorio de Windows	C:\Windows
Directorio del sistema	C:\Windows\system32
Dispositivo de arranque	\Device\HarddiskVolume1
Configuración regional	España
Capa de abstracción de hardware	Versión = "10.0.22621.2506"
Nombre de usuario	PANDORA\Usuario
Zona horaria	Hora estándar romance
Memoria física instalada (RAM)	32,0 GB
Memoria física total	31,9 GB
Memoria física disponible	17,1 GB
Memoria virtual total	36,7 GB
Memoria virtual disponible	14,5 GB
Espacio de archivo de paginación	4,75 GB
Archivo de paginación	C:\pagefile.sys
Protección de DMA de kernel	Desactivada
Seguridad basada en virtualización	No habilitado
Directiva de Control de aplicaciones de Windows Defender	Impuesta
Directiva de modo usuario de Control de aplicaciones de Windows Defender	Desactivada
Compatibilidad con cifrado de dispositivo	Se necesita elevación de privilegios para ver
Hyper-V - Extensiones de modo de monitor VM	Sí
Hyper-V - Extensiones de traducción de dirección de segundo nivel	Sí
Hyper-V - Virtualización habilitada en Firmware	No
Hyper-V -Protección de ejecución de datos	Sí

### Console logs

```Shell
venv "C:\Users\Usuario\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.8.0-RC
Commit hash: 25a3b6cbeea8a07afd5e4594afc2f1c79f41ac1a
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
C:\Users\Usuario\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --skip-torch-cuda-test --opt-sub-quad-attention --lowvram --disable-nan-check --autolaunch
Warning: caught exception 'Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx', memory monitor disabled
ONNX: selected=CUDAExecutionProvider, available=['AzureExecutionProvider', 'CPUExecutionProvider']
Loading weights [6ce0161689] from C:\Users\Usuario\stable-diffusion-webui-directml\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
Creating model from config: C:\Users\Usuario\stable-diffusion-webui-directml\configs\v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 2.5s (prepare environment: 6.8s, initialize shared: 1.3s, load scripts: 0.4s, create ui: 0.3s, gradio launch: 0.2s).
Applying attention optimization: sub-quadratic... done.
loading stable diffusion model: RuntimeError
Traceback (most recent call last):
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\initialize.py", line 148, in load_model
    shared.sd_model  # noqa: B018
  File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\shared_items.py", line 148, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\sd_models.py", line 627, in get_sd_model
    load_model()
  File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\sd_models.py", line 788, in load_model
    with devices.autocast(), torch.no_grad():
  File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\devices.py", line 234, in autocast
    if has_xpu() or has_mps() or cuda_no_autocast():
  File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\devices.py", line 28, in cuda_no_autocast
    device_id = get_cuda_device_id()
  File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\devices.py", line 40, in get_cuda_device_id
    ) or torch.cuda.current_device()
  File "C:\Users\Usuario\stable-diffusion-webui-directml\venv\lib\site-packages\torch\cuda\__init__.py", line 787, in current_device
    _lazy_init()
  File "C:\Users\Usuario\stable-diffusion-webui-directml\venv\lib\site-packages\torch\cuda\__init__.py", line 302, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx


Stable diffusion model failed to load
Using already loaded model v1-5-pruned-emaonly.safetensors [6ce0161689]: done in 0.0s
*** Error completing request
*** Arguments: ('task(so4svuibi0afz9n)', <gradio.routes.Request object at 0x000002A9BE860490>, 'Plump grapes in a vintage ceramic bowl, ad photography, promotional photography, colorful glowing backdrop, glowing neon lights, bokeh neon lights, glow textured backdrop, in dark studio background, dark and glow in background, cinematic lighting, minimal professional photography, soft lighting, fog and smoke around, spot light, studio lighting style, bright lighting, vibrant colors, 4k', '', [], 20, 'DPM++ 2M Karras', 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], 0, False, '', 0.8, -1, False, -1, 0, 0, 0, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\txt2img.py", line 110, in txt2img
        processed = processing.process_images(p)
      File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\processing.py", line 787, in process_images
        res = process_images_inner(p)
      File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\processing.py", line 948, in process_images_inner
        with devices.autocast():
      File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\devices.py", line 234, in autocast
        if has_xpu() or has_mps() or cuda_no_autocast():
      File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\devices.py", line 28, in cuda_no_autocast
        device_id = get_cuda_device_id()
      File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\devices.py", line 40, in get_cuda_device_id
        ) or torch.cuda.current_device()
      File "C:\Users\Usuario\stable-diffusion-webui-directml\venv\lib\site-packages\torch\cuda\__init__.py", line 787, in current_device
        _lazy_init()
      File "C:\Users\Usuario\stable-diffusion-webui-directml\venv\lib\site-packages\torch\cuda\__init__.py", line 302, in _lazy_init
        torch._C._cuda_init()
    RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

---
*** Error completing request
*** Arguments: ('task(emg7boyeh55lbwo)', <gradio.routes.Request object at 0x000002A9BE862BC0>, 'Plump grapes in a vintage ceramic bowl, ad photography, promotional photography, colorful glowing backdrop, glowing neon lights, bokeh neon lights, glow textured backdrop, in dark studio background, dark and glow in background, cinematic lighting, minimal professional photography, soft lighting, fog and smoke around, spot light, studio lighting style, bright lighting, vibrant colors, 4k', '', [], 20, 'DPM++ 2M Karras', 1, 1, 7, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, 'Use same checkpoint', 'Use same sampler', '', '', [], 0, False, '', 0.8, -1, False, -1, 0, 0, 0, False, False, 'positive', 'comma', 0, False, False, 'start', '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\txt2img.py", line 110, in txt2img
        processed = processing.process_images(p)
      File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\processing.py", line 787, in process_images
        res = process_images_inner(p)
      File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\processing.py", line 948, in process_images_inner
        with devices.autocast():
      File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\devices.py", line 234, in autocast
        if has_xpu() or has_mps() or cuda_no_autocast():
      File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\devices.py", line 28, in cuda_no_autocast
        device_id = get_cuda_device_id()
      File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\devices.py", line 40, in get_cuda_device_id
        ) or torch.cuda.current_device()
      File "C:\Users\Usuario\stable-diffusion-webui-directml\venv\lib\site-packages\torch\cuda\__init__.py", line 787, in current_device
        _lazy_init()
      File "C:\Users\Usuario\stable-diffusion-webui-directml\venv\lib\site-packages\torch\cuda\__init__.py", line 302, in _lazy_init
        torch._C._cuda_init()
    RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

---
*** Error completing request
*** Arguments: ('task(mla6fooli4tho4u)', 0, 'Plump grapes in a vintage ceramic bowl, ad photography, promotional photography, colorful glowing backdrop, glowing neon lights, bokeh neon lights, glow textured backdrop, in dark studio background, dark and glow in background, cinematic lighting, minimal professional photography, soft lighting, fog and smoke around, spot light, studio lighting style, bright lighting, vibrant colors, 4k', '', [], None, None, None, None, None, None, None, 20, 'DPM++ 2M Karras', 4, 0, 1, 1, 1, 7, 1.5, 0.75, 0.0, 512, 512, 1, 0, 0, 32, 0, '', '', '', [], False, [], '', <gradio.routes.Request object at 0x000002A9BE30DA80>, 0, False, 1, 0.5, 4, 0, 0.5, 2, False, '', 0.8, -1, False, -1, 0, 0, 0, '* `CFG Scale` should be 2 or lower.', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, 'start', '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, False, False, False, 0, False) {}
    Traceback (most recent call last):
      File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\call_queue.py", line 57, in f
        res = list(func(*args, **kwargs))
      File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\call_queue.py", line 36, in f
        res = func(*args, **kwargs)
      File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\img2img.py", line 235, in img2img
        processed = process_images(p)
      File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\processing.py", line 787, in process_images
        res = process_images_inner(p)
      File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\processing.py", line 948, in process_images_inner
        with devices.autocast():
      File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\devices.py", line 234, in autocast
        if has_xpu() or has_mps() or cuda_no_autocast():
      File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\devices.py", line 28, in cuda_no_autocast
        device_id = get_cuda_device_id()
      File "C:\Users\Usuario\stable-diffusion-webui-directml\modules\devices.py", line 40, in get_cuda_device_id
        ) or torch.cuda.current_device()
      File "C:\Users\Usuario\stable-diffusion-webui-directml\venv\lib\site-packages\torch\cuda\__init__.py", line 787, in current_device
        _lazy_init()
      File "C:\Users\Usuario\stable-diffusion-webui-directml\venv\lib\site-packages\torch\cuda\__init__.py", line 302, in _lazy_init
        torch._C._cuda_init()
    RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

### Additional information

Graphics AMD 
![Captura de pantalla 2024-03-17 015749](https://github.com/lshqqytiger/stable-diffusion-webui-directml/assets/163696184/82fd6a5d-74f2-4760-ac5f-ba2bcd2277ae)

**Comment by lshqqytiger** [comment]
If you don't add anything of `--use-*` argument, it won't detect non-NVIDIA gpus. Please check [README](https://github.com/lshqqytiger/stable-diffusion-webui-directml?tab=readme-ov-file#whats-different-from-upstream-repo).

**Comment by I2pRandom** [comment]
The argument's don't matter. it insists on using CUDA. I don't know what the maintainers did because this used to just work on AMD GPUs. This output is using ZLUDA, but it still wants the driver even with DirectML. Infact the DirectML is worse because it will output the library it is looking for does not exist. 

ZLUDA
```
C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml>webui-user.bat
venv "C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
WARNING: ZLUDA works best with SD.Next. Please consider migrating to SD.Next.
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.8.0-RC
Commit hash: 7071a4a7e42e7d5588f7c3eee44d411953419f8d
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --opt-sub-quad-attention --lowvram --disable-nan-check --skip-torch-cuda-test --use-zluda
Warning: caught exception 'Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx', memory monitor disabled
ONNX: selected=CUDAExecutionProvider, available=['DmlExecutionProvider', 'CPUExecutionProvider']
Loading weights [487fb59b03] from C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml\models\Stable-diffusion\breastinclassBetter.safetensors
Creating model from config: C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml\configs\v1-inference.yaml
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 2.6s (prepare environment: 6.6s, initialize shared: 1.1s, load scripts: 0.5s, create ui: 0.5s, gradio launch: 0.2s).
Applying attention optimization: sub-quadratic... done.
loading stable diffusion model: RuntimeError
Traceback (most recent call last):
  File "D:\ProgrammingLanguages\Python 3.10\lib\threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "D:\ProgrammingLanguages\Python 3.10\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\ProgrammingLanguages\Python 3.10\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml\modules\initialize.py", line 148, in load_model
    shared.sd_model  # noqa: B018
  File "C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml\modules\shared_items.py", line 148, in sd_model
    return modules.sd_models.model_data.get_sd_model()
  File "C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml\modules\sd_models.py", line 627, in get_sd_model
    load_model()
  File "C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml\modules\sd_models.py", line 788, in load_model
    with devices.autocast(), torch.no_grad():
  File "C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml\modules\devices.py", line 234, in autocast
    if has_xpu() or has_mps() or cuda_no_autocast():
  File "C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml\modules\devices.py", line 28, in cuda_no_autocast
    device_id = get_cuda_device_id()
  File "C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml\modules\devices.py", line 40, in get_cuda_device_id
    ) or torch.cuda.current_device()
  File "C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml\venv\lib\site-packages\torch\cuda\__init__.py", line 787, in current_device
    _lazy_init()
  File "C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml\venv\lib\site-packages\torch\cuda\__init__.py", line 302, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx


Stable diffusion model failed to load
``` 

DirectML
```C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml>webui-user.bat
venv "C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.8.0-RC
Commit hash: 7071a4a7e42e7d5588f7c3eee44d411953419f8d
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
Launching Web UI with arguments: --opt-sub-quad-attention --lowvram --disable-nan-check --skip-torch-cuda-test --use-directml
DirectML initialization failed: No module named 'torch_directml'
Traceback (most recent call last):
  File "C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml\launch.py", line 44, in main
    start()
  File "C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml\modules\launch_utils.py", line 672, in start
    import webui
  File "C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml\webui.py", line 13, in <module>
    initialize.imports()
  File "C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml\modules\initialize.py", line 36, in imports
    shared_init.initialize()
  File "C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml\modules\shared_init.py", line 30, in initialize
    directml_do_hijack()
  File "C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml\modules\dml\__init__.py", line 76, in directml_do_hijack
    if not torch.dml.has_float64_support(device):
  File "C:\Users\JasonPanic\Desktop\stable-diffusion-webui-directml\venv\lib\site-packages\torch\__init__.py", line 1932, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'torch' has no attribute 'dml'```


Is anyone actually testing this before pushing PRs? Because this is an immediate output when attempting to generate anything with the WebUI. These outputs did not occur about a year ago.

**Comment by lshqqytiger** [comment]
Try again after removing venv folder.

**Comment by Aelzaire** [comment]
Having the same issue, used to work like a charm, no longer does. Tried a clean install as well, even tried a fresh install following AMD's guide also: https://community.amd.com/t5/ai/updated-how-to-running-optimized-automatic1111-stable-diffusion/ba-p/630252
No dice. With AMD's guide it gave the same thing, included --skip-torch-cuda-test and it just errored saying --onnx --backend directml weren't recognized.

**Comment by M0UL** [comment]
i am having the same issue. any way around it?

**Comment by lshqqytiger** [comment]
If you have a problem even with `--use-zluda` or `--use-directml`, please search for other issues.
