### ISSUE TITLE
[Bug]: Runtime Error

### ISSUE THREAD

**Issue by HildaGoneril** [lshqqytiger/stable-diffusion-webui-directml#42]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Tried running webui-user.bat, but after everything has finished downloaded, it errors out and fails to launch.

### Steps to reproduce the problem

Followed these steps under Windows:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs

### What should have happened?

Program should have started after the set-up process.

### Commit where the problem happens

f64ad25

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--medvram 
--no-half
```

### List of extensions

No.

### Console logs

```Shell
loading stable diffusion model: RuntimeError
Traceback (most recent call last):
  File "C:\Users\danga\Desktop\AI Gen II\stable-diffusion-webui-directml\webui.py", line 136, in initialize
    modules.sd_models.load_model()
  File "C:\Users\danga\Desktop\AI Gen II\stable-diffusion-webui-directml\modules\sd_models.py", line 383, in load_model
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "C:\Users\danga\Desktop\AI Gen II\stable-diffusion-webui-directml\modules\sd_models.py", line 238, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "C:\Users\danga\Desktop\AI Gen II\stable-diffusion-webui-directml\modules\sd_models.py", line 217, in read_state_dict
    pl_sd = safetensors.torch.load_file(checkpoint_file, device=device)
  File "C:\Users\danga\Desktop\AI Gen II\stable-diffusion-webui-directml\venv\lib\site-packages\safetensors\torch.py", line 100, in load_file
    result[k] = f.get_tensor(k)
RuntimeError: self.size(-1) must be divisible by 4 to view Byte as Float (different element sizes), but got 7289158
```

### Additional information

Using a Radeon RX 580 series GPU. 

New to github. My apologies for being too vague/posting anything incorrect.

**Comment by lshqqytiger** [comment]
There may be a problem with the model you used. Does the same problem occur when you use a different checkpoint file?
