### ISSUE TITLE
[Bug]: Web UI link failed

### ISSUE THREAD

**Issue by deepnx** [lshqqytiger/stable-diffusion-webui-directml#43]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Im sorry to sound like a noob,
Followed the steps - Installed Python latest + Git 2.40
Ran the .bat file
First time some installations came up and then did not get Web UI link
got some kinda line error texts.
Ran it again to get the errors.. 
Have provided the console log for the second run.

### Steps to reproduce the problem

same as above

### What should have happened?

Should have got the WEB UI link?

### Commit where the problem happens

Always

### What platforms do you use to access the UI ?

Windows

### Command Line Arguments

```Shell
no
```

### List of extensions

no

### Console logs

```Shell
Creating venv in directory C:\Users\deepn\Downloads\Stable Diffusion Stuf\stable-diffusion-webui-directml-master\stable-diffusion-webui-directml-master\venv using python "C:\Users\deepn\AppData\Local\Programs\Python\Python310\python.exe"
venv "C:\Users\deepn\Downloads\Stable Diffusion Stuf\stable-diffusion-webui-directml-master\stable-diffusion-webui-directml-master\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: <none>
Installing torch and torchvision
Collecting torch==1.13.1
  Using cached torch-1.13.1-cp310-cp310-win_amd64.whl (162.6 MB)
Collecting torchvision==0.14.1
  Using cached torchvision-0.14.1-cp310-cp310-win_amd64.whl (1.1 MB)
Collecting torch-directml
  Using cached torch_directml-0.1.13.1.dev230301-cp310-cp310-win_amd64.whl (7.4 MB)
Collecting typing-extensions
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting numpy
  Using cached numpy-1.24.2-cp310-cp310-win_amd64.whl (14.8 MB)
Collecting requests
  Using cached requests-2.28.2-py3-none-any.whl (62 kB)
Collecting pillow!=8.3.*,>=5.3.0
  Using cached Pillow-9.4.0-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.1.0-cp310-cp310-win_amd64.whl (97 kB)
Installing collected packages: urllib3, typing-extensions, pillow, numpy, idna, charset-normalizer, certifi, torch, requests, torchvision, torch-directml
Successfully installed certifi-2022.12.7 charset-normalizer-3.1.0 idna-3.4 numpy-1.24.2 pillow-9.4.0 requests-2.28.2 torch-1.13.1 torch-directml-0.1.13.1.dev230301 torchvision-0.14.1 typing-extensions-4.5.0 urllib3-1.26.15

[notice] A new release of pip available: 22.2.1 -> 23.0.1
[notice] To update, run: C:\Users\deepn\Downloads\Stable Diffusion Stuf\stable-diffusion-webui-directml-master\stable-diffusion-webui-directml-master\venv\Scripts\python.exe -m pip install --upgrade pip
Installing gfpgan
Installing clip
Installing open_clip
Cloning Taming Transformers into C:\Users\deepn\Downloads\Stable Diffusion Stuf\stable-diffusion-webui-directml-master\stable-diffusion-webui-directml-master\repositories\taming-transformers...
Cloning CodeFormer into C:\Users\deepn\Downloads\Stable Diffusion Stuf\stable-diffusion-webui-directml-master\stable-diffusion-webui-directml-master\repositories\CodeFormer...
Cloning BLIP into C:\Users\deepn\Downloads\Stable Diffusion Stuf\stable-diffusion-webui-directml-master\stable-diffusion-webui-directml-master\repositories\BLIP...
Installing requirements for CodeFormer
Installing requirements for Web UI
Launching Web UI with arguments:
Traceback (most recent call last):
  File "C:\Users\deepn\Downloads\Stable Diffusion Stuf\stable-diffusion-webui-directml-master\stable-diffusion-webui-directml-master\launch.py", line 377, in <module>
    start()
  File "C:\Users\deepn\Downloads\Stable Diffusion Stuf\stable-diffusion-webui-directml-master\stable-diffusion-webui-directml-master\launch.py", line 368, in start
    import webui
  File "C:\Users\deepn\Downloads\Stable Diffusion Stuf\stable-diffusion-webui-directml-master\stable-diffusion-webui-directml-master\webui.py", line 15, in <module>
    from modules import paths, timer, import_hook, errors
  File "C:\Users\deepn\Downloads\Stable Diffusion Stuf\stable-diffusion-webui-directml-master\stable-diffusion-webui-directml-master\modules\paths.py", line 26, in <module>
    assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_sd_paths)
AssertionError: Couldn't find Stable Diffusion in any of: ['C:\\Users\\deepn\\Downloads\\Stable Diffusion Stuf\\stable-diffusion-webui-directml-master\\stable-diffusion-webui-directml-master\\repositories/stable-diffusion-stability-ai', '.', 'C:\\Users\\deepn\\Downloads\\Stable Diffusion Stuf\\stable-diffusion-webui-directml-master']
Press any key to continue . . .

----
```

**Comment by lshqqytiger** [comment]
Don't download .zip archive.
Clone this repo.
[Instruction](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs)

**Comment by deepnx** [comment]
> Don't download .zip archive. Clone this repo. [Instruction](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs)

Thanks for your reply sir, Actually I'm not a programmer ... just a media person ... with some technical knowledge ... so I don't know what you mean by clone this repo.
Please explain me if possible

Thanks a lot
