### ISSUE TITLE
[Bug]: Error "RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check", forced to use CPU

### ISSUE THREAD

**Issue by NotSoCommonSense** [lshqqytiger/stable-diffusion-webui-directml#432]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

Won't launch without --skip-torch-cuda-test in command line arguments. This forces me to use the CPU and thus makes generation times extremely long.

### Steps to reproduce the problem

Install fresh, try to start.

### What should have happened?

Webui should start and allow me to use my GPU, the whole point of this program.

### What browsers do you use to access the UI ?

Microsoft Edge

### Sysinfo

[sysinfo-2024-03-29-22-25.json](https://github.com/lshqqytiger/stable-diffusion-webui-directml/files/14808964/sysinfo-2024-03-29-22-25.json)

### Console logs

```Shell
venv "C:\Users\Damirko\Downloads\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.8.0-RC
Commit hash: ce3d044680100834e862bee6fefb413bfc835ece
Traceback (most recent call last):
  File "C:\Users\Damirko\Downloads\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "C:\Users\Damirko\Downloads\stable-diffusion-webui-directml\launch.py", line 39, in main
    prepare_environment()
  File "C:\Users\Damirko\Downloads\stable-diffusion-webui-directml\modules\launch_utils.py", line 571, in prepare_environment
    raise RuntimeError(
RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check
Press any key to continue . . .
```

**Comment by NotSoCommonSense** [comment]
Fixed using this: https://www.reddit.com/r/StableDiffusion/comments/18vmkon/comment/khpbnvo/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
