### ISSUE TITLE
[Bug]: WebUI unable to launch again after first time

### ISSUE THREAD

**Issue by popsoda27** [lshqqytiger/stable-diffusion-webui-directml#448]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [X] The issue exists in the current version of the webui
- [ ] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

WebUI is not launching again after first launch.

venv "E:\Downloads\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Traceback (most recent call last):
  File "E:\Downloads\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "E:\Downloads\stable-diffusion-webui-directml\launch.py", line 29, in main
    filename = launch_utils.dump_sysinfo()
  File "E:\Downloads\stable-diffusion-webui-directml\modules\launch_utils.py", line 705, in dump_sysinfo
    from modules import sysinfo
  File "E:\Downloads\stable-diffusion-webui-directml\modules\sysinfo.py", line 12, in <module>
    from modules import paths_internal, timer, shared, extensions, errors, devices
  File "E:\Downloads\stable-diffusion-webui-directml\modules\shared.py", line 4, in <module>
    import gradio as gr
  File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\components\annotated_image.py", line 13, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\components\base.py", line 20, in <module>
    from fastapi import UploadFile
  File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\applications.py", line 15, in <module>
    from fastapi import routing
  File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\routing.py", line 22, in <module>
    from fastapi import params
  File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\pydantic\fields.py)
Press any key to continue . . .

### Steps to reproduce the problem

1, Fresh install A1111
2. Append --use-zluda --autolaunch to cmd args in webui-user.bat
3. WebUI launches successfully first time.
4. Installed some extensions. Exit WebUI and console.
5. Relaunched webui-user.bat. Console presented error....press any key to continue. Console exits after keypress.
6. Removed installed extensions. Same error on launch.
7. Removed venv. Venv folder recreated on launch. Same error on launch.
8. Removed cmd args and added --dump-sysinfo. Same error on launch. Sysinfo dump not created.
9. Removed cmd args and added --use-directml. Same error on launch.

### What should have happened?

WebUI should launch successfully. Not extension issue as WebUI not launching even after extensions were removed.

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

Sysinfo not generated at all with --dump-sysinfo cmd arg

### Console logs

```Shell
venv "E:\Downloads\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Traceback (most recent call last):
  File "E:\Downloads\stable-diffusion-webui-directml\launch.py", line 48, in <module>
    main()
  File "E:\Downloads\stable-diffusion-webui-directml\launch.py", line 29, in main
    filename = launch_utils.dump_sysinfo()
  File "E:\Downloads\stable-diffusion-webui-directml\modules\launch_utils.py", line 705, in dump_sysinfo
    from modules import sysinfo
  File "E:\Downloads\stable-diffusion-webui-directml\modules\sysinfo.py", line 12, in <module>
    from modules import paths_internal, timer, shared, extensions, errors, devices
  File "E:\Downloads\stable-diffusion-webui-directml\modules\shared.py", line 4, in <module>
    import gradio as gr
  File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\components\annotated_image.py", line 13, in <module>
    from gradio.components.base import IOComponent, _Keywords
  File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\components\base.py", line 20, in <module>
    from fastapi import UploadFile
  File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\applications.py", line 15, in <module>
    from fastapi import routing
  File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\routing.py", line 22, in <module>
    from fastapi import params
  File "E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\fastapi\params.py", line 4, in <module>
    from pydantic.fields import FieldInfo, Undefined
ImportError: cannot import name 'Undefined' from 'pydantic.fields' (E:\Downloads\stable-diffusion-webui-directml\venv\lib\site-packages\pydantic\fields.py)
Press any key to continue . . .
```

### Additional information

AMD 7800X3D
Asrock 7900XTX Taichi OC
32GB RAM
Python 3.10.6
HIP SDK installed and PATH added

**Comment by Anders1974** [comment]
I have the same mistake.

**Comment by lshqqytiger** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/15564

**Comment by popsoda27** [comment]
> [AUTOMATIC1111#15564](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/15564)

Thank you @lshqqytiger I confirm this solves the issue on my machine.
