### ISSUE TITLE
[Bug]: AttributeError: function 'ADL2_Adapter_DedicatedVRAMUsage_Get' not found

### ISSUE THREAD

**Issue by Kuron88** [lshqqytiger/stable-diffusion-webui-directml#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Launching Web UI with arguments: --opt-sub-quad-attention --lowvram --no-half --precision full
Traceback (most recent call last):
  File "D:\sd.webui-amd\launch.py", line 377, in <module>
    start()
  File "D:\sd.webui-amd\launch.py", line 368, in start
    import webui
  File "D:\sd.webui-amd\webui.py", line 28, in <module>
    from modules import extra_networks, ui_extra_networks_checkpoints
  File "D:\sd.webui-amd\modules\ui_extra_networks_checkpoints.py", line 5, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "D:\sd.webui-amd\modules\shared.py", line 12, in <module>
    import modules.interrogate
  File "D:\sd.webui-amd\modules\interrogate.py", line 15, in <module>
    from modules import devices, paths, shared, lowvram, modelloader, errors
  File "D:\sd.webui-amd\modules\devices.py", line 101, in <module>
    from modules import atiadlxx
  File "D:\sd.webui-amd\modules\atiadlxx.py", line 2, in <module>
    from .atiadlxx_apis import *
  File "D:\sd.webui-amd\modules\atiadlxx_apis.py", line 41, in <module>
    ADL2_Adapter_DedicatedVRAMUsage_Get = atiadlxx.ADL2_Adapter_DedicatedVRAMUsage_Get
  File "C:\Users\28670\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\28670\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'ADL2_Adapter_DedicatedVRAMUsage_Get' not found

### Steps to reproduce the problem

重新安装了系统就出现了这个

### What should have happened?

进入webui

### Commit where the problem happens

启动的时候

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--opt-sub-quad-attention --lowvram --no-half --precision full
```

### List of extensions

无

### Console logs

```Shell
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: f64ad25386ad77d1e07986a204dac923b9a46894
Installing requirements for Web UI

Launching Web UI with arguments: --opt-sub-quad-attention --lowvram --no-half --precision full
Traceback (most recent call last):
  File "D:\sd.webui-amd\launch.py", line 377, in <module>
    start()
  File "D:\sd.webui-amd\launch.py", line 368, in start
    import webui
  File "D:\sd.webui-amd\webui.py", line 28, in <module>
    from modules import extra_networks, ui_extra_networks_checkpoints
  File "D:\sd.webui-amd\modules\ui_extra_networks_checkpoints.py", line 5, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "D:\sd.webui-amd\modules\shared.py", line 12, in <module>
    import modules.interrogate
  File "D:\sd.webui-amd\modules\interrogate.py", line 15, in <module>
    from modules import devices, paths, shared, lowvram, modelloader, errors
  File "D:\sd.webui-amd\modules\devices.py", line 101, in <module>
    from modules import atiadlxx
  File "D:\sd.webui-amd\modules\atiadlxx.py", line 2, in <module>
    from .atiadlxx_apis import *
  File "D:\sd.webui-amd\modules\atiadlxx_apis.py", line 41, in <module>
    ADL2_Adapter_DedicatedVRAMUsage_Get = atiadlxx.ADL2_Adapter_DedicatedVRAMUsage_Get
  File "C:\Users\28670\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\28670\AppData\Local\Programs\Python\Python310\lib\ctypes\__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'ADL2_Adapter_DedicatedVRAMUsage_Get' not found
```

**Comment by lshqqytiger** [comment]
What device (GPU) are you using?
Is the GPU driver updated to the latest one?

**Comment by carlchou00** [comment]
same error, any thoughts how to fix this?
GPU: AMD Radeon R9 390X

**Comment by lshqqytiger** [comment]
Add `--disable-experimental-memopt`.

**Comment by lshqqytiger** [comment]
Pull latest commit and try again. It will automatically disable experimental memory optimization if `ADL2_Adapter_DedicatedVRAMUsage_Get` is unavailable.

**Comment by amegaara** [comment]
> Add `--disable-experimental-memopt`.

i tried this and still get the same error "PDHError: Something went wrong."

**Comment by lshqqytiger** [comment]
That solution is not valid for now. (`--disable-experimental-memopt` is removed)
Change `DirectML memory stats provider` to `None`.

**Comment by amegaara** [comment]
sorry but where do i find this text to disable it?

**Comment by lshqqytiger** [comment]
If you can access Settings, you can find it at Settings > Optimizations.
