### ISSUE TITLE
[Bug]: NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:

### ISSUE THREAD

**Issue by fanisspr** [lshqqytiger/stable-diffusion-webui-directml#5]
### Is there an existing issue for this?

- [x] I have searched the existing issues and checked the recent builds/commits

### What happened?

I tried to generate my first prompt using stable diffusion v2.1 base and got the error mentioned.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

Image should have been generated

### Commit where the problem happens

https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a0f4cd6fdd2b7ef3e2b666694f1a1ca13ee17066

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
I use --xformers, but same happens if I don't.
```

### List of extensions

No

### Console logs

```Shell
venv "C:\Users\Fanis\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: a0f4cd6fdd2b7ef3e2b666694f1a1ca13ee17066
Installing requirements for Web UI
Launching Web UI with arguments: --xformers
Warning: experimental graphic memory optimizations are disabled due to gpu vendor.
Disabled experimental graphic memory optimizations.
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 1.13.1+cu117 with CUDA 1107 (you have 1.13.1+cpu)
    Python  3.10.9 (you have 3.10.6)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
Loading weights [88ecb78256] from C:\Users\Φάνης\stable-diffusion-webui-directml\models\Stable-diffusion\v2-1_512-ema-pruned.ckpt
Creating model from config: C:\Users\Φάνης\stable-diffusion-webui-directml\models\Stable-diffusion\v2-1_512-ema-pruned.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 865.91 M params.
Applying cross attention optimization (InvokeAI).
Textual inversion embeddings loaded(0):
Model loaded in 142.4s (load weights from disk: 26.4s, load config: 0.2s, create model: 6.8s, apply weights to model: 76.3s, apply half(): 28.4s, move model to device: 3.9s, hijack: 0.1s, load textual inversion embeddings: 0.2s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
100%|████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:08<00:00,  4.06s/it]
Error completing request█████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.11s/it]
Arguments: ('task(n53zcn2fd1sam6h)', 'a cat', '', [], 2, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "C:\Users\Φάνης\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Users\Φάνης\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Users\Φάνης\stable-diffusion-webui-directml\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "C:\Users\Φάνης\stable-diffusion-webui-directml\modules\processing.py", line 486, in process_images
    res = process_images_inner(p)
  File "C:\Users\Φάνης\stable-diffusion-webui-directml\modules\processing.py", line 630, in process_images_inner
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "C:\Users\Φάνης\stable-diffusion-webui-directml\modules\processing.py", line 630, in <listcomp>
    x_samples_ddim = [decode_first_stage(p.sd_model, samples_ddim[i:i+1].to(dtype=devices.dtype_vae))[0].cpu() for i in range(samples_ddim.size(0))]
  File "C:\Users\Φάνης\stable-diffusion-webui-directml\modules\processing.py", line 423, in decode_first_stage
    x = model.decode_first_stage(x)
  File "C:\Users\Fanis\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 17, in <lambda>
    setattr(resolved_obj, func_path[-1], lambda *args, **kwargs: self(*args, **kwargs))
  File "C:\Users\Fanis\stable-diffusion-webui-directml\modules\sd_hijack_utils.py", line 28, in __call__
    return self.__orig_func(*args, **kwargs)
  File "C:\Users\Fanis\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\Φάνης\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 826, in decode_first_stage
    return self.first_stage_model.decode(z)
  File "C:\Users\Φάνης\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\autoencoder.py", line 90, in decode
    dec = self.decoder(z)
  File "C:\Users\Fanis\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Φάνης\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 631, in forward
    h = self.mid.attn_1(h)
  File "C:\Users\Fanis\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\Φάνης\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\model.py", line 258, in forward
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=None, op=self.attention_op)
  File "C:\Users\Fanis\stable-diffusion-webui-directml\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 197, in memory_efficient_attention
    return _memory_efficient_attention(
  File "C:\Users\Fanis\stable-diffusion-webui-directml\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 293, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "C:\Users\Fanis\stable-diffusion-webui-directml\venv\lib\site-packages\xformers\ops\fmha\__init__.py", line 309, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp)
  File "C:\Users\Fanis\stable-diffusion-webui-directml\venv\lib\site-packages\xformers\ops\fmha\dispatch.py", line 95, in _dispatch_fw
    return _run_priority_list(
  File "C:\Users\Fanis\stable-diffusion-webui-directml\venv\lib\site-packages\xformers\ops\fmha\dispatch.py", line 70, in _run_priority_list
    raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 4096, 1, 512) (torch.float16)
     key         : shape=(1, 4096, 1, 512) (torch.float16)
     value       : shape=(1, 4096, 1, 512) (torch.float16)
     attn_bias   : <class 'NoneType'>
```

### Additional information

I try to run stable diffusion 2.1 with a RX 580 gpu card. Is it supposed to run only in a Nvidia card?

It says in installation guide for amd that it is currently in testing for windows. Does this mean that it only works with rocm in linux?

**Comment by ClashSAN** [comment]
--xformers is a cuda only option. 

>It says in installation guide for amd that it is currently in testing for windows. Does this mean that it only works with rocm in linux?

We don't know which gpus will work. It would be nice to share that info here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/7870

I didn't test 2.1

**Comment by fanisspr** [comment]
I tried running it again with no args but I got an error about NaNs in a tensor that prompted me (pun intended) to turn on _Upcast cross attention layer to float32_ in settings > Stable Diffusion or try the --no-half argument. 

The first didn't work and when I tried the second I had an error about not having enough memory.

So I solved it by adding both --no-half and --medvram.

Since I have 8gb of vram I expected that I could get away with --medvram but this is not the case obviously.

For the record I get 1.3-1.5s/it

**Comment by lshqqytiger** [comment]
xformers is NVIDIA-only option.
A `NansException` seems to be solved with `--no-half --precision full`.
If you met out of memory error, try `--opt-sub-quad-attention`.

**Comment by Natotela** [comment]
I'm getting:

```
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 4096, 8, 40) (torch.float32)
     key         : shape=(1, 4096, 8, 40) (torch.float32)
     value       : shape=(1, 4096, 8, 40) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`cutlassF` is not supported because:
    xFormers wasn't build with CUDA support
`flshattF` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
`tritonflashattF` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float32 (supported: {torch.bfloat16, torch.float16})
    triton is not available
    requires A100 GPU
`smallkF` is not supported because:
    xFormers wasn't build with CUDA support
    max(query.shape[-1] != value.shape[-1]) > 32
    unsupported embed per head: 40
```

**Comment by lshqqytiger** [comment]
xformers requires CUDA.
Remove `--xformers` from your commandline arguments.

**Comment by Natotela** [comment]
I have CUDA, doesn't strike me as a solution not to use xformers for it requires CUDA

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

**Comment by lshqqytiger** [comment]
If you have a NVIDIA GPU, you don't need to use `stable-diffusion-webui-directml`.
But if you still want, check whether installed xformers built with CUDA.
