### ISSUE TITLE
[Bug]: Can't load any model

### ISSUE THREAD

**Issue by yehonatan5f** [lshqqytiger/stable-diffusion-webui-directml#51]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I'm getting this error no matter what when I try to run webui-user.bat :

Installing requirements for Web UI
Launching Web UI with arguments:
Interrogations are fallen back to cpu. This doesn't affect on image generation. But if you want to use interrogate (CLIP or DeepBooru), check out this issue: https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/10
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
Calculating sha256 for F:\Stable diffusion\stable-diffusion-webui-directml\models\Stable-diffusion\model1.ckpt: b77d2fec5fba71b0f473cb1685a06221f1d36ab76cbe41b95e94aebb24145e17
Loading weights [b77d2fec5f] from F:\Stable diffusion\stable-diffusion-webui-directml\models\Stable-diffusion\model1.ckpt
loading stable diffusion model: RuntimeError
Traceback (most recent call last):
  File "F:\Stable diffusion\stable-diffusion-webui-directml\webui.py", line 136, in initialize
    modules.sd_models.load_model()
  File "F:\Stable diffusion\stable-diffusion-webui-directml\modules\sd_models.py", line 383, in load_model
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "F:\Stable diffusion\stable-diffusion-webui-directml\modules\sd_models.py", line 238, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "F:\Stable diffusion\stable-diffusion-webui-directml\modules\sd_models.py", line 219, in read_state_dict
    pl_sd = torch.load(checkpoint_file, map_location=map_location or shared.weight_load_location)
  File "F:\Stable diffusion\stable-diffusion-webui-directml\modules\safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "F:\Stable diffusion\stable-diffusion-webui-directml\modules\safe.py", line 151, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "F:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "F:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 1131, in _load
    result = unpickler.load()
  File "F:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 1101, in persistent_load
    load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
  File "F:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\serialization.py", line 1079, in load_tensor
    storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage).storage().untyped()
RuntimeError: PytorchStreamReader failed reading file data/95: invalid header or archive is corrupted

Stable diffusion model failed to load, exiting

Can anyone help me to fix it?
<img width="1671" alt="image" src="https://user-images.githubusercontent.com/123481656/227712663-1f60fbdf-56bd-4986-b838-eb7cdee885ef.png">

I have an AMD Radeon RX 6800XT

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

.

### Commit where the problem happens

.

### Command Line Arguments

```Shell
.
```

### List of extensions

.

### Console logs

```Shell
.
```

**Comment by lshqqytiger** [comment]
Which model did you use? It seems to be a problem on model file.

**Comment by megazaz80** [comment]
Browser totally broken cant send imgs anywhere because there are no buttons... How to revert to previus version?

> Which model did you use? It seems to be a problem on model file.

![Untitled](https://user-images.githubusercontent.com/70824762/227718804-d19ebd4e-7589-41ba-a77d-36ed34e88362.png)

**Comment by Cwieku666** [comment]
After today git pull I can't even generate images, when I click generate button just nothing happens and the console doesn't throw any errors.

**Comment by megazaz80** [comment]
> After today git pull I can't even generate images, when I click generate button just nothing happens and the console doesn't throw any errors.

yeah a lots of things are broken an webui looks ugly imo ))) i like older better

**Comment by UnrealSimulation** [comment]
I can confirm: impossible to load models and if you use the UI at a certain point the "Generate" button doesn't work anymore.

**Comment by yehonatan5f** [comment]
Well, it appears that model has been corrupted... I switched to sd v1.4 which worked but I guess it's quite outdated and no matter what, it won't work on any model above 1.4... by the way, clip doesn't work too... can't generate prompts based on images
