### ISSUE TITLE
[Bug]: Virtual machine 

### ISSUE THREAD

**Issue by moon47usaco** [lshqqytiger/stable-diffusion-webui-directml#54]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Trying to install this over a virtual machine VMware Fusion on my Intel MacBook Pro to try and use the AMD gpu.

I know this is probably a horrible idea but the local install of SD on a Mac can not use the GPU and CPU generation is like trying to download a movie over 56k internet speed. If you did not get that reference or never lived through that, it is gruelingly slow.

I need better than 2min generations... =[

### Steps to reproduce the problem

Fallowed std install instructions:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs

### What should have happened?

It does not seem to be detecting the GPU.

### Commit where the problem happens

Starting Web UI

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of extensions

No

### Console logs

```Shell
venv "C:\Users\VM_PC\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 41d5450a0a559469b354fd56cac0fe1ab3cf2f40
Installing requirements for Web UI
Launching Web UI with arguments:
Traceback (most recent call last):
  File "C:\Users\VM_PC\stable-diffusion-webui-directml\launch.py", line 349, in <module>
    start()
  File "C:\Users\VM_PC\stable-diffusion-webui-directml\launch.py", line 340, in start
    import webui
  File "C:\Users\VM_PC\stable-diffusion-webui-directml\webui.py", line 31, in <module>
    from modules import extra_networks, ui_extra_networks_checkpoints
  File "C:\Users\VM_PC\stable-diffusion-webui-directml\modules\ui_extra_networks_checkpoints.py", line 5, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "C:\Users\VM_PC\stable-diffusion-webui-directml\modules\shared.py", line 12, in <module>
    import modules.interrogate
  File "C:\Users\VM_PC\stable-diffusion-webui-directml\modules\interrogate.py", line 15, in <module>
    from modules import devices, paths, shared, lowvram, modelloader, errors
  File "C:\Users\VM_PC\stable-diffusion-webui-directml\modules\devices.py", line 99, in <module>
    dml = torch_directml.device(torch_directml.default_device())
  File "C:\Users\VM_PC\stable-diffusion-webui-directml\venv\lib\site-packages\torch_directml\device.py", line 38, in device
    raise Exception(f"Invalid device_id argument supplied {device_id}. device_id must be in range [0, {num_devices}).")
Exception: Invalid device_id argument supplied 0. device_id must be in range [0, 0).
Press any key to continue . . .
```

**Comment by lshqqytiger** [comment]
I think it is hard to find examples that run DirectML on VM, but we can try.
DirectML requires DirectX 12 Runtime. Make sure your VM has it.

**Comment by moon47usaco** [comment]
Thank you, the AMD is a dGPU not an eGPU. I have an Intel iGPU. I will look into the rest and report when I have time to test again.

**Comment by 2400YrsOldLallo** [comment]
Hey all,
Have anyone figured this out?
