### ISSUE TITLE
[Bug]: AssertionError: Couldn't find Stable Diffusion in any of: ['C:\\Users\\user\\Downloads\\stable-diffusion-webui-directml\\repositories/stable-diffusion-stability-ai', '.', 'C:\\Users\\user\\Downloads']

### ISSUE THREAD

**Issue by NotSoCommonSense** [lshqqytiger/stable-diffusion-webui-directml#63]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Webui will not launch when webui-user.bat is opened

### Steps to reproduce the problem

1. Go to webui-user.bat
2. Press webui-user.bat
3. error will occur

### What should have happened?

Webui should have launched

### Commit where the problem happens

ae337fa

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
No
```

### List of extensions

No

### Console logs

```Shell
venv "C:\Users\user\Downloads\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: ae337fa39b6d4598b377ff312c53b14c15142331
Installing requirements for Web UI
Launching Web UI with arguments:
Traceback (most recent call last):
  File "C:\Users\user\Downloads\stable-diffusion-webui-directml\launch.py", line 353, in <module>
    start()
  File "C:\Users\user\Downloads\stable-diffusion-webui-directml\launch.py", line 344, in start
    import webui
  File "C:\Users\user\Downloads\stable-diffusion-webui-directml\webui.py", line 16, in <module>
    from modules import paths, timer, import_hook, errors
  File "C:\Users\user\Downloads\stable-diffusion-webui-directml\modules\paths.py", line 19, in <module>
    assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_sd_paths)
AssertionError: Couldn't find Stable Diffusion in any of: ['C:\\Users\\user\\Downloads\\stable-diffusion-webui-directml\\repositories/stable-diffusion-stability-ai', '.', 'C:\\Users\\user\\Downloads']
Press any key to continue . . .
```

**Comment by lshqqytiger** [comment]
#4
