### ISSUE TITLE
[Bug]: Can't run it due to torch_directml_native problem

### ISSUE THREAD

**Issue by KAMG95** [lshqqytiger/stable-diffusion-webui-directml#65]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

when I run webui.bat I encountered error due to I don't have torch_directml, after I installed it now this message comes
Traceback (most recent call last):
  File "stable-diffusion-webui-directml\launch.py", line 353, in <module>
    start()
  File "stable-diffusion-webui-directml\launch.py", line 344, in start
    import webui
  File "stable-diffusion-webui-directml\webui.py", line 31, in <module>
    from modules import extra_networks, ui_extra_networks_checkpoints
  File "stable-diffusion-webui-directml\modules\ui_extra_networks_checkpoints.py", line 5, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "stable-diffusion-webui-directml\modules\shared.py", line 12, in <module>
    import modules.interrogate
  File "stable-diffusion-webui-directml\modules\interrogate.py", line 15, in <module>
    from modules import devices, paths, shared, lowvram, modelloader, errors
  File "D:\BACKUP11\App\stable-diffusion-webui-directml\modules\devices.py", line 4, in <module>
    import torch_directml
  File "stable-diffusion-webui-directml\venv\lib\site-packages\torch_directml\__init__.py", line 16, in <module>
    import torch_directml_native
ModuleNotFoundError: No module named 'torch_directml_native'

And I can't find any source using torch_directml_native

### Steps to reproduce the problem

Open webui.bat and run the code

### What should have happened?

The code should normally run the ui

### Commit where the problem happens

ae337fa

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
NO
```

### List of extensions

NO

### Console logs

```Shell
venv "D:\BACKUP11\App\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: ae337fa39b6d4598b377ff312c53b14c15142331
Installing requirements for Web UI
Launching Web UI with arguments:
Traceback (most recent call last):
  File "D:\BACKUP11\App\stable-diffusion-webui-directml\launch.py", line 353, in <module>
    start()
  File "D:\BACKUP11\App\stable-diffusion-webui-directml\launch.py", line 344, in start
    import webui
  File "D:\BACKUP11\App\stable-diffusion-webui-directml\webui.py", line 31, in <module>
    from modules import extra_networks, ui_extra_networks_checkpoints
  File "D:\BACKUP11\App\stable-diffusion-webui-directml\modules\ui_extra_networks_checkpoints.py", line 5, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "D:\BACKUP11\App\stable-diffusion-webui-directml\modules\shared.py", line 12, in <module>
    import modules.interrogate
  File "D:\BACKUP11\App\stable-diffusion-webui-directml\modules\interrogate.py", line 15, in <module>
    from modules import devices, paths, shared, lowvram, modelloader, errors
  File "D:\BACKUP11\App\stable-diffusion-webui-directml\modules\devices.py", line 4, in <module>
    import torch_directml
  File "D:\BACKUP11\App\stable-diffusion-webui-directml\venv\lib\site-packages\torch_directml\__init__.py", line 16, in <module>
    import torch_directml_native
ModuleNotFoundError: No module named 'torch_directml_native'
Press any key to continue . . .
```

**Comment by lshqqytiger** [comment]
Already known issue of DirectML. https://github.com/microsoft/DirectML/issues/432
It will be solved on next release of DirectML, and you can manually reinstall torchtext which is version 0.14.1.

**Comment by Henry715** [comment]
just to metion(because the instructions on microsoft's webpage is also a bit misleading...), to install pytorch manually:
1. download and install anaconda
2. run the following commands: 
    1) conda install numpy pandas tensorboard matplotlib tqdm pyyaml -y
    2) pip install opencv-python
    3) pip install wget
    4) pip install torch-directml
that should give you a correctly installed torch-directml
