### ISSUE TITLE
[Bug]: Error charging model

### ISSUE THREAD

**Issue by FrakerKill** [lshqqytiger/stable-diffusion-webui-directml#67]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

This is a new error.
Yesterday I was working with my SD without problems with a RX6600.
I updated my driver like another days but it gives always this error:

### Steps to reproduce the problem

Execute webui-user.bat

### What should have happened?

Starts without problems like other days

### Commit where the problem happens

In the console 

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--listen --api --medvram --disable-nan-check --opt-sub-quad-attention --precision full --no-half --autolaunch
```

### List of extensions

Openpose, controlnet...

### Console logs

```Shell
Already up to date.
venv "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: ae337fa39b6d4598b377ff312c53b14c15142331
Installing requirements for Web UI
Interrogations are fallen back to cpu. This doesn't affect on image generation. But if you want to use interrogate (CLIP or DeepBooru), check out this issue: https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/10
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled




Launching Web UI with arguments: --listen --api --medvram --disable-nan-check --opt-sub-quad-attention --precision full --no-half --autolaunch
Interrogations are fallen back to cpu. This doesn't affect on image generation. But if you want to use interrogate (CLIP or DeepBooru), check out this issue: https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/10
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
Loading weights [58a28bf595] from D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\models\Stable-diffusion\PeachTachyon2.safetensors
Creating model from config: D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
Failed to create model quickly; will retry using slow method.
LatentDiffusion: Running in eps-prediction mode
loading stable diffusion model: RuntimeError
Traceback (most recent call last):
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\webui.py", line 139, in initialize
    modules.sd_models.load_model()
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\modules\sd_models.py", line 438, in load_model
    sd_model = instantiate_from_config(sd_config.model)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 550, in __init__
    super().__init__(conditioning_key=conditioning_key, *args, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 92, in __init__
    self.model = DiffusionWrapper(unet_config, conditioning_key)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\models\diffusion\ddpm.py", line 1314, in __init__
    self.diffusion_model = instantiate_from_config(diff_model_config)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\util.py", line 79, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 669, in __init__
    ResBlock(
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\openaimodel.py", line 203, in __init__
    conv_nd(dims, channels, self.out_channels, 3, padding=1),
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\ldm\modules\diffusionmodules\util.py", line 229, in conv_nd
    return nn.Conv2d(*args, **kwargs)
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\conv.py", line 450, in __init__
    super(Conv2d, self).__init__(
  File "D:\Datos\Downloads\GitHub\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\conv.py", line 137, in __init__
    self.weight = Parameter(torch.empty(
RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 117964800 bytes.


Stable diffusion model failed to load, exiting
```

**Comment by lshqqytiger** [comment]
How much memory (RAM. not VRAM) do you have?
It seems to be not enough space to load that model.

**Comment by FrakerKill** [comment]
Yes, I saw that 16GB RAM becomes 4GB. Windows things. I need to check hardware, now.
