### ISSUE TITLE
[Bug]: atiadlxx.py issue

### ISSUE THREAD

**Issue by Shortcutz** [lshqqytiger/stable-diffusion-webui-directml#75]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

When I start the programm, since last update I receive this error message:

```
Launching Web UI with arguments: --skip-torch-cuda-test --precision full --no-half --deepdanbooru --autolaunch --opt-channelslast --api
Traceback (most recent call last):
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\launch.py", line 353, in <module>
    start()
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\launch.py", line 344, in start
    import webui
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\webui.py", line 31, in <module>
    from modules import extra_networks, ui_extra_networks_checkpoints
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\modules\ui_extra_networks_checkpoints.py", line 5, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\modules\shared.py", line 12, in <module>
    import modules.interrogate
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\modules\interrogate.py", line 15, in <module>
    from modules import devices, paths, shared, lowvram, modelloader, errors
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\modules\devices.py", line 7, in <module>
    from modules.atiadlxx import ATIADLxx
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\modules\atiadlxx.py", line 54
    match ATIADLxx.test():
          ^
SyntaxError: invalid syntax
```

### Steps to reproduce the problem

1. use .\webui-user.bat

### What should have happened?

program shouldve loaded

### Commit where the problem happens

dae3394497ea810a4601422e8c7f3c74debe4c7c

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
.\webui-user.bat
```

### List of extensions

No

### Console logs

```Shell
PS C:\Users\Yulia\Desktop\stable-diffusion-webui-directml> .\webui-user.bat
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

venv "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
==============================================================================================================
INCOMPATIBLE PYTHON VERSION

This program is tested with 3.10.6 Python, but you have 3.9.13.
If you encounter an error with "RuntimeError: Couldn't install torch." message,
or any other error regarding unsuccessful package (library) installation,
please downgrade (or upgrade) to the latest version of 3.10 Python
and delete current Python and "venv" folder in WebUI's directory.

You can download 3.10 Python from here: https://www.python.org/downloads/release/python-3109/

Alternatively, use a binary release of WebUI: https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases

Use --skip-python-version-check to suppress this warning.
==============================================================================================================
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Commit hash: 11de843884b55a3d39b8b302856d1e6145f62988
Installing requirements for Web UI
Launching Web UI with arguments: --skip-torch-cuda-test --precision full --no-half --deepdanbooru --autolaunch --opt-channelslast --api

Launching Web UI with arguments: --skip-torch-cuda-test --precision full --no-half --deepdanbooru --autolaunch --opt-channelslast --api
Traceback (most recent call last):
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\launch.py", line 353, in <module>
    start()
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\launch.py", line 344, in start
    import webui
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\webui.py", line 31, in <module>
    from modules import extra_networks, ui_extra_networks_checkpoints
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\modules\ui_extra_networks_checkpoints.py", line 5, in <module>
    from modules import shared, ui_extra_networks, sd_models
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\modules\shared.py", line 12, in <module>
    import modules.interrogate
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\modules\interrogate.py", line 15, in <module>
    from modules import devices, paths, shared, lowvram, modelloader, errors
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\modules\devices.py", line 7, in <module>
    from modules.atiadlxx import ATIADLxx
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\modules\atiadlxx.py", line 54
    match ATIADLxx.test():
          ^
SyntaxError: invalid syntax
```

**Comment by Tanuki33** [comment]
> This program is tested with 3.10.6 Python, but you have 3.9.13.

you have python 3.9.13 , try update your python to 3.10.6
also this

> PS C:\Users\Yulia\Desktop\stable-diffusion-webui-directml> .\webui-user.bat
> You are not currently on a branch.
> Please specify which branch you want to merge with.
> See git-pull(1) for details.
> 
>     git pull <remote> <branch>

you need type `git pull origin master` i think

**Comment by Shortcutz** [comment]
Thank you very much, I'm now on the correct branch, but the issue unfortunately persists.

I'm not sure how to update python version. I get this:

```
PS C:\Users\Yulia\Desktop\stable-diffusion-webui-directml> python -V
Python 3.10.9
PS C:\Users\Yulia\Desktop\stable-diffusion-webui-directml> pip --version
pip 23.1 from C:\Users\Yulia\AppData\Local\Programs\Python\Python310\lib\site-packages\pip (python 3.10)
```

So it seems like I have installed the correct python version, but when I use webui-user.bat I get the same alert as above.
I also added the install path for python310\python.exe to the webui-user.bat file after PYTHON=, but warning that I use python version 9 still persists. 
In requirements_versions.txt I have: GitPython==3.1.30

Do you know how I can change Python to the correct version in stable diffusion?

**Comment by lshqqytiger** [comment]
`match` keyword is introduced in python 3.10.
I replaced it with ifs.
Should be fixed in last commit.

**Comment by Shortcutz** [comment]
Thank you for your help! You're a godsend
