### ISSUE TITLE
[Bug]: RuntimeError: The parameter is incorrect.

### ISSUE THREAD

**Issue by ryuphobia** [lshqqytiger/stable-diffusion-webui-directml#78]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

No, go on a new commit.
Unable to generate due to the new update on -directml.
 

Nvidia is fine.

### Steps to reproduce the problem

1. Update
2. Go to webui
3. Press Generate
4. RuntimeError: The parameter is incorrect.

### What should have happened?

Generate as usual.

### Commit where the problem happens

b48ae2ba

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--medvram --opt-split-attention --no-half --precision full --opt-sub-quad-attention
```

### List of extensions

No

### Console logs

```Shell
Error completing request
Arguments: ('task(jyudfm7bhohj5d9)', 'a girl', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, <scripts.external_code.ControlNetUnit object at 0x0000023C7E997100>, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0, None, False, 50) {}
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\AI\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\AI\stable-diffusion-webui-directml\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "C:\AI\stable-diffusion-webui-directml\modules\processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "C:\AI\stable-diffusion-webui-directml\modules\processing.py", line 653, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "C:\AI\stable-diffusion-webui-directml\modules\processing.py", line 869, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "C:\AI\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 358, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\AI\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 234, in launch_sampling
    return func()
  File "C:\AI\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 358, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "C:\AI\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\AI\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\sampling.py", line 150, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\AI\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\AI\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 132, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict([cond_in[a:b]], image_cond_in[a:b]))
  File "C:\AI\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\AI\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "C:\AI\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 72, in sigma_to_t
    low_idx = dists.ge(0).cumsum(dim=0).argmax(dim=0).clamp(max=self.log_sigmas.shape[0] - 2)
RuntimeError: The parameter is incorrect.
```

**Comment by Lumpsack** [comment]
Thanks, I was coming here to report that issue too, the error log looks the same as mine as well.
I think only two files changed overnight, so presuming its one of those.

**Comment by Lumpsack** [comment]
I looked back as the history and pasted the content of \modules\devices.py back in and can generate images again, so the issue is in there.

**Comment by lshqqytiger** [comment]
Please run `pip show torch-directml` and copy output here.

**Comment by AraHaan** [comment]
I have the issue with this still even with the latest version of the code from this repository:
```
Name: torch-directml
Version: 0.2.0.dev230426
Summary: A DirectML backend for hardware acceleration in PyTorch.
Home-page: https://github.com/microsoft/directml
Author: Microsoft Corporation
Author-email: askdirectml@microsoft.com
License: MIT
Location: c:\stable-diffusion-webui\venv\lib\site-packages
Requires: torch, torchvision
Required-by:
```
