### ISSUE TITLE
[Bug]: RuntimeError: The parameter is incorrect.

### ISSUE THREAD

**Issue by Neoony** [lshqqytiger/stable-diffusion-webui-directml#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

After pulling latest commits

Getting error 
RuntimeError: The parameter is incorrect.

### Steps to reproduce the problem

1. Go to generate any txt2img

### What should have happened?

Generate image

### Commit where the problem happens

https://github.com/lshqqytiger/stable-diffusion-webui-directml/commit/ba7b23c2ae3916103dc6b7ecf73179f37f4d57bb

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--precision full --no-half --no-half-vae --opt-split-attention-v1 --opt-sub-quad-attention --disable-nan-check
```

### List of extensions

disabled them

### Console logs

```Shell
venv "H:\Programs\StableDiffusion\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: ba7b23c2ae3916103dc6b7ecf73179f37f4d57bb
Installing requirements for Web UI
Launching Web UI with arguments: --precision full --no-half --no-half-vae --opt-split-attention-v1 --opt-sub-quad-attention --disable-nan-check
Interrogations are fallen back to cpu. This doesn't affect on image generation. But if you want to use interrogate (CLIP or DeepBooru), check out this issue: https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/10
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
*** "Disable all extensions" option was set, will not load any extensions ***
Loading weights [dcd690123c] from H:\Programs\StableDiffusion\stable-diffusion-webui-directml\models\Stable-diffusion\v2-1_768-ema-pruned.safetensors
Creating model from config: H:\Programs\StableDiffusion\stable-diffusion-webui-directml\repositories\stable-diffusion-stability-ai\configs\stable-diffusion\v2-inference-v.yaml
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Loading VAE weights specified in settings: H:\Programs\StableDiffusion\stable-diffusion-webui-directml\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying sub-quadratic cross attention optimization.
Textual inversion embeddings loaded(3): nartfixer, nfixer, nrealfixer
Textual inversion embeddings skipped(9): bad-hands-5, bad-image-v2-39000, bad_prompt_version2, EasyNegative, ng_deepnegative_v1_16t, ng_deepnegative_v1_32t, ng_deepnegative_v1_4t, ng_deepnegative_v1_64t, ng_deepnegative_v1_75t
Model loaded in 5.2s (load weights from disk: 0.2s, find config: 1.0s, create model: 0.2s, apply weights to model: 0.7s, load VAE: 0.1s, move model to device: 3.0s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 14.3s (import torch: 1.7s, import gradio: 1.3s, import ldm: 0.4s, other imports: 1.2s, load SD checkpoint: 5.4s, create ui: 4.1s).
H:\Programs\StableDiffusion\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py:63: UserWarning: The operator 'aten::linspace.out' is not currently supported on the DML backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at D:\a\_work\1\s\pytorch-directml-plugin\torch_directml\csrc\dml\dml_cpu_fallback.cpp:17.)
  t = torch.linspace(t_max, 0, n, device=self.sigmas.device)
  0%|                                                                            | 0/20 [00:00<?, ?it/s]
Error completing request
Arguments: ('task(j5cvwelangep955)', 'image', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, 0, 0, 0, 0, 4, 512, 512, True, 'None', 'None', 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "H:\Programs\StableDiffusion\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "H:\Programs\StableDiffusion\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "H:\Programs\StableDiffusion\stable-diffusion-webui-directml\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "H:\Programs\StableDiffusion\stable-diffusion-webui-directml\modules\processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "H:\Programs\StableDiffusion\stable-diffusion-webui-directml\modules\processing.py", line 653, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "H:\Programs\StableDiffusion\stable-diffusion-webui-directml\modules\processing.py", line 869, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "H:\Programs\StableDiffusion\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 358, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "H:\Programs\StableDiffusion\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 234, in launch_sampling
    return func()
  File "H:\Programs\StableDiffusion\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 358, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "H:\Programs\StableDiffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "H:\Programs\StableDiffusion\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\sampling.py", line 150, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "H:\Programs\StableDiffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Programs\StableDiffusion\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 126, in forward
    x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict([cond_in], image_cond_in))
  File "H:\Programs\StableDiffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "H:\Programs\StableDiffusion\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 167, in forward
    return self.get_v(input * c_in, self.sigma_to_t(sigma), **kwargs) * c_out + input * c_skip
  File "H:\Programs\StableDiffusion\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 72, in sigma_to_t
    low_idx = dists.ge(0).cumsum(dim=0).argmax(dim=0).clamp(max=self.log_sigmas.shape[0] - 2)
RuntimeError: The parameter is incorrect.
```

### Additional information

Worked fine on commit https://github.com/lshqqytiger/stable-diffusion-webui-directml/commit/ae337fa39b6d4598b377ff312c53b14c15142331

**Comment by Neoony** [comment]
pip show torch-directml
Name: torch-directml
Version: 0.1.13.1.dev230301
Summary: A DirectML backend for hardware acceleration in PyTorch.
Home-page: https://github.com/microsoft/directml
Author: Microsoft Corporation
Author-email: askdirectml@microsoft.com
License: MIT
Location: c:\users\neoony\appdata\local\programs\python\python310\lib\site-packages
Requires: torch, torchvision
Required-by:

**Comment by thonsm06** [comment]
I just had the same problem, try deleting the venv folder and relaunch the webui.

**Comment by lshqqytiger** [comment]
#77

**Comment by Neoony** [comment]
Deleting venv helped, Thanks!
Also later did `pip install torch-directml --upgrade`

**Comment by SunGreen777** [comment]
Deleted the **venv** folder, restarted webui-user.bat, automatic1111 downloaded the remote folder, now it works

**Comment by Arnavv22** [comment]
Where is the venv folder?
