### ISSUE TITLE
[Bug]: Runtime error when running latest ControlNet 1.1 and Openpose

### ISSUE THREAD

**Issue by backtr4ck** [lshqqytiger/stable-diffusion-webui-directml#80]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

`RuntimeError: Input type (torch.FloatTensor) and weight type (PrivateUse1FloatType) should be the same or input should be a MKLDNN tensor and weight is a dense tensor`

Happens on any openpose setting.

### Steps to reproduce the problem

1. Go to ControlNet tab, set openpose as preprocessor and model
2. Press preview annotator
3. See error

### What should have happened?

generated the openpose preview

### Commit where the problem happens

ba7b23c

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--precision full --no-half --medvram --autolaunch
```

### List of extensions

ControlNet only 

### Console logs

```Shell
Traceback (most recent call last):
  File "E:\Programs\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\Programs\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "E:\Programs\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\Programs\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\Programs\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\Programs\stable-diffusion-webui-directml\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\Programs\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\controlnet.py", line 375, in run_annotator
    result, is_image = preprocessor(img, res=pres, thr_a=pthr_a, thr_b=pthr_b)
  File "E:\Programs\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\scripts\processor.py", line 174, in openpose_full
    result = model_openpose(img, include_hand=True, include_face=True)
  File "E:\Programs\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\openpose\__init__.py", line 84, in __call__
    candidate, subset = self.body_estimation(oriImg)
  File "E:\Programs\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\openpose\body.py", line 48, in __call__
    Mconv7_stage6_L1, Mconv7_stage6_L2 = self.model(data)
  File "E:\Programs\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Programs\stable-diffusion-webui-directml\extensions\sd-webui-controlnet\annotator\openpose\model.py", line 116, in forward
    out1 = self.model0(x)
  File "E:\Programs\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Programs\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "E:\Programs\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Programs\stable-diffusion-webui-directml\extensions-builtin\Lora\lora.py", line 319, in lora_Conv2d_forward
    return torch.nn.Conv2d_forward_before_lora(self, input)
  File "E:\Programs\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "E:\Programs\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.FloatTensor) and weight type (PrivateUse1FloatType) should be the same or input should be a MKLDNN tensor and weight is a dense tensor
```

**Comment by Miraihi** [comment]
ControlNet 1.1 is in pretty raw state right now, it's bleeding edge.

**Comment by jyomu** [comment]
It seems to have been fixed
https://github.com/Mikubill/sd-webui-controlnet/issues/901
