### ISSUE TITLE
[Bug]: Unknown error when launching SD webui

### ISSUE THREAD

**Issue by boiker** [lshqqytiger/stable-diffusion-webui-directml#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

ran webui--user.bat and the following error is being generated.

Traceback (most recent call last):
  File "E:\PythonEnv\stable-diffusion-webui-directml\modules\atiadlxx.py", line 74, in test
    tester = ATIADLxx()
  File "E:\PythonEnv\stable-diffusion-webui-directml\modules\atiadlxx.py", line 24, in __init__
    self.iHyperMemorySize = self.getMemoryInfo2(0).iHyperMemorySize
  File "E:\PythonEnv\stable-diffusion-webui-directml\modules\atiadlxx.py", line 30, in getMemoryInfo2
    raise RuntimeError("ADL2: Failed to get MemoryInfo2")
RuntimeError: ADL2: Failed to get MemoryInfo2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\PythonEnv\stable-diffusion-webui-directml\modules\atiadlxx.py", line 81, in test
    if "ADL2" in e:
TypeError: argument of type 'RuntimeError' is not iterable

### Steps to reproduce the problem

1. Go to ....  /stable-diffusion-webui-directml directory
2. run webui-user.bat
3. error pops up immediately in command window

### What should have happened?

Error should not have occured.

### Commit where the problem happens

?

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No.
```

### List of extensions

No.

### Console logs

```Shell
venv "E:\PythonEnv\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: ba7b23c2ae3916103dc6b7ecf73179f37f4d57bb
Installing requirements for Web UI
Installing requirements 1 for Infinite-Zoom

Installing sd-webui-controlnet requirement: opencv-contrib-python==4.7.0.68

Launching Web UI with arguments:

Unknown error occurred while testing whether experimental memory optimization can be applied!
Please copy full traceback below and create a new issue: https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/new/choose

↓↓↓↓↓
Traceback (most recent call last):
  File "E:\PythonEnv\stable-diffusion-webui-directml\modules\atiadlxx.py", line 74, in test
    tester = ATIADLxx()
  File "E:\PythonEnv\stable-diffusion-webui-directml\modules\atiadlxx.py", line 24, in __init__
    self.iHyperMemorySize = self.getMemoryInfo2(0).iHyperMemorySize
  File "E:\PythonEnv\stable-diffusion-webui-directml\modules\atiadlxx.py", line 30, in getMemoryInfo2
    raise RuntimeError("ADL2: Failed to get MemoryInfo2")
RuntimeError: ADL2: Failed to get MemoryInfo2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\PythonEnv\stable-diffusion-webui-directml\modules\atiadlxx.py", line 81, in test
    if "ADL2" in e:
TypeError: argument of type 'RuntimeError' is not iterable
↑↑↑↑↑
Warning: experimental graphic memory optimization for AMDGPU is disabled. Because there is an unknown error.
Interrogations are fallen back to cpu. This doesn't affect on image generation. But if you want to use interrogate (CLIP or DeepBooru), check out this issue: https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/10
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
Loading weights [fc2511737a] from E:\PythonEnv\stable-diffusion-webui-directml\models\Stable-diffusion\chilloutmix_NiPrunedFp32Fix.safetensors
Creating model from config: E:\PythonEnv\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (InvokeAI).
Textual inversion embeddings loaded(0):
Model loaded in 2.5s (load weights from disk: 0.1s, create model: 0.3s, apply weights to model: 0.6s, apply half(): 0.5s, move model to device: 0.9s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 8.2s (import torch: 1.4s, import gradio: 0.8s, import ldm: 0.4s, other imports: 0.8s, setup codeformer: 0.1s, load scripts: 1.1s, load SD checkpoint: 2.8s, create ui: 0.6s, gradio launch: 0.2s).
Traceback (most recent call last):
  File "E:\PythonEnv\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\PythonEnv\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 1073, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "E:\PythonEnv\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\blocks.py", line 962, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
IndexError: list index out of range
Closing server running on port: 7860
Restarting UI...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 0.8s (load scripts: 0.2s, create ui: 0.6s).
```

### Additional information

 I have an AMD RX 6700 XT so I'm following the install instructions for this version of AUTOMATIC11111.  

About a month ago I installed and had no issues and was able to generate images almost immediately.  I wanted to reinstall to a different drive and now I can't get it to work.

**Comment by jieran233** [comment]
I have the same problem

**Comment by jieran233** [comment]
I have the same problem

**Comment by lshqqytiger** [comment]
Should be fixed in the commit I pushed.
