### ISSUE TITLE
[Bug]: upscaler problem

### ISSUE THREAD

**Issue by Nathan-dm** [lshqqytiger/stable-diffusion-webui-directml#83]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

i have several issues with upscaler 
1#
i tried to upscale a image with SwinIR 4x upscaler but it got a black vertical rectangle on the left side
i tried change upscaling setting on setting tab it didn't work

Image sample:
Original image
![00000-4233856310](https://user-images.githubusercontent.com/65475192/232478821-0beb1b47-e7ef-4b71-a19b-a858f467a4eb.png)
Upscaled image
![00038](https://user-images.githubusercontent.com/65475192/232479240-9f0fa267-6f6c-47e5-9107-04c1b23d6b28.png)

2#
problem with ScuNET GAN and ScuNET PSNR
it got this error
```
Arguments: (0, <PIL.Image.Image image mode=RGB size=512x512 at 0x1D26BF5D6C0>, None, '', '', True, 0, 4, 512, 512, True, 'ScuNET GAN', 'None', 0, 0, 0, 0) {}
Traceback (most recent call last):
  File "C:\Stable diffusion\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Stable diffusion\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\modules\postprocessing.py", line 56, in run_postprocessing
    scripts.scripts_postproc.run(pp, args)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\modules\scripts_postprocessing.py", line 130, in run
    script.process(pp, **process_args)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\scripts\postprocessing_upscale.py", line 96, in process
    upscaled_image = self.upscale(pp.image, pp.info, upscaler1, upscale_mode, upscale_by, upscale_to_width, upscale_to_height, upscale_crop)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\scripts\postprocessing_upscale.py", line 66, in upscale
    image = upscaler.scaler.upscale(image, upscale_by, upscaler.data_path)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\modules\upscaler.py", line 63, in upscale
    img = self.do_upscale(img, selected_model)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\extensions-builtin\ScuNET\scripts\scunet_model.py", line 60, in do_upscale
    output = model(img)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\extensions-builtin\ScuNET\scunet_model_arch.py", line 245, in forward
    x2 = self.m_down1(x1)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\extensions-builtin\ScuNET\scunet_model_arch.py", line 159, in forward
    trans_x = self.trans_block(trans_x)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\extensions-builtin\ScuNET\scunet_model_arch.py", line 122, in forward
    x = x + self.drop_path(self.msa(self.ln1(x)))
  File "C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\extensions-builtin\ScuNET\scunet_model_arch.py", line 80, in forward
    sim = sim.masked_fill_(attn_mask, float("-inf"))
RuntimeError: m_device->CreateOperator(&opDesc, IID_PPV_ARGS(&op))

Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=512x512 at 0x1D26A63D630>, None, '', '', True, 0, 4, 512, 512, True, 'ScuNET PSNR', 'None', 0, 0, 0, 0) {}
Traceback (most recent call last):
  File "C:\Stable diffusion\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Stable diffusion\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\modules\postprocessing.py", line 56, in run_postprocessing
    scripts.scripts_postproc.run(pp, args)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\modules\scripts_postprocessing.py", line 130, in run
    script.process(pp, **process_args)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\scripts\postprocessing_upscale.py", line 96, in process
    upscaled_image = self.upscale(pp.image, pp.info, upscaler1, upscale_mode, upscale_by, upscale_to_width, upscale_to_height, upscale_crop)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\scripts\postprocessing_upscale.py", line 66, in upscale
    image = upscaler.scaler.upscale(image, upscale_by, upscaler.data_path)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\modules\upscaler.py", line 63, in upscale
    img = self.do_upscale(img, selected_model)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\extensions-builtin\ScuNET\scripts\scunet_model.py", line 60, in do_upscale
    output = model(img)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\extensions-builtin\ScuNET\scunet_model_arch.py", line 245, in forward
    x2 = self.m_down1(x1)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\extensions-builtin\ScuNET\scunet_model_arch.py", line 159, in forward
    trans_x = self.trans_block(trans_x)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\extensions-builtin\ScuNET\scunet_model_arch.py", line 122, in forward
    x = x + self.drop_path(self.msa(self.ln1(x)))
  File "C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\extensions-builtin\ScuNET\scunet_model_arch.py", line 80, in forward
    sim = sim.masked_fill_(attn_mask, float("-inf"))
RuntimeError: m_device->CreateOperator(&opDesc, IID_PPV_ARGS(&op))
``` 

### Steps to reproduce the problem

1. go to extras tab
2. input image
3. pick a SwinIR 4x or ScuNET
4. click Generate

### What should have happened?

1# the output should look fine without black rectangle 
2# it should run 

### Commit where the problem happens

7b5c7743c15bc73d348fb7e4cd7607c4fae7c392

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--lowvram --precision full --no-half --opt-sub-quad-attention --opt-split-attention-v1 --disable-nan-check
```

### List of extensions

1. sd-webui-controlnet
2. multidiffusion-upscaler-for-automatic1111

### Console logs

```Shell
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 9 (delta 4), reused 9 (delta 4), pack-reused 0
Unpacking objects: 100% (9/9), 16.68 KiB | 1.04 MiB/s, done.
From https://github.com/lshqqytiger/stable-diffusion-webui-directml
   ba7b23c2..7b5c7743  master     -> origin/master
Updating ba7b23c2..7b5c7743
Fast-forward
 modules/atiadlxx.py |  2 +-
 modules/shared.py   | 10 +++++-----
 2 files changed, 6 insertions(+), 6 deletions(-)
venv "C:\Stable diffusion\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Commit hash: 7b5c7743c15bc73d348fb7e4cd7607c4fae7c392
Installing requirements for Web UI

Launching Web UI with arguments: --lowvram --precision full --no-half --opt-sub-quad-attention --opt-split-attention-v1 --disable-nan-check
Warning: memory optimization for AMDGPU is disabled. Because couldn't find 'atiadlxx.dll'. Please install GPU driver downloaded from AMD.com.
Warning: experimental graphic memory optimization is disabled due to gpu vendor. Currently this optimization is only available for AMDGPUs.
Disabled experimental graphic memory optimizations.
Interrogations are fallen back to cpu. This doesn't affect on image generation. But if you want to use interrogate (CLIP or DeepBooru), check out this issue: https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/10
Warning: caught exception 'Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx', memory monitor disabled
No module 'xformers'. Proceeding without it.
Checkpoint dreamshaper_332BakedVaeClipFix.safetensors [13dfc9921f] not found; loading fallback Anything-V3.0-pruned-fp16.ckpt [812cd9f9d9]
Loading weights [812cd9f9d9] from C:\Stable diffusion\stable-diffusion-webui-directml\models\Stable-diffusion\Anything-V3.0-pruned-fp16.ckpt
Creating model from config: C:\Stable diffusion\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying sub-quadratic cross attention optimization.
Textual inversion embeddings loaded(4): EasyNegative, ng_deepnegative_v1_75t, pureerosface_v1, style-empire
Model loaded in 2.9s (load weights from disk: 1.8s, create model: 0.5s, apply weights to model: 0.5s).
C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\gradio\deprecation.py:43: UserWarning: You have unused kwarg parameters in Tab, please remove them: {'open': False}
  warnings.warn(
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 14.7s (import torch: 3.0s, import gradio: 2.2s, import ldm: 0.6s, other imports: 3.7s, setup codeformer: 0.1s, load scripts: 1.1s, load SD checkpoint: 3.0s, create ui: 0.5s, gradio launch: 0.1s).
C:\Stable diffusion\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py:63: UserWarning: The operator 'aten::linspace.out' is not currently supported on the DML backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at D:\a\_work\1\s\pytorch-directml-plugin\torch_directml\csrc\dml\dml_cpu_fallback.cpp:17.)
  t = torch.linspace(t_max, 0, n, device=self.sigmas.device)
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [03:49<00:00, 11.47s/it]
Downloading: "https://github.com/JingyunLiang/SwinIR/releases/download/v0.0/003_realSR_BSRGAN_DFOWMFC_s64w8_SwinIR-L_x4_GAN.pth " to C:\Stable diffusion\stable-diffusion-webui-directml\models\SwinIR\SwinIR_4x.pth

100%|███████████████████████████████████████████████████████████████████████████████| 136M/136M [01:32<00:00, 1.54MB/s]
C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3191.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
SwinIR tiles: 100%|██████████████████████████████████████████████████████████████████| 289/289 [09:12<00:00,  1.91s/it]
Downloading: "https://github.com/cszn/KAIR/releases/download/v1.0/scunet_color_real_gan.pth" to C:\Stable diffusion\stable-diffusion-webui-directml\models\ScuNET\ScuNET.pth

100%|██████████████████████████████████████████████████████████████████████████████| 68.6M/68.6M [03:17<00:00, 365kB/s]
Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=512x512 at 0x1D26BF5D6C0>, None, '', '', True, 0, 4, 512, 512, True, 'ScuNET GAN', 'None', 0, 0, 0, 0) {}
Traceback (most recent call last):
  File "C:\Stable diffusion\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Stable diffusion\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\modules\postprocessing.py", line 56, in run_postprocessing
    scripts.scripts_postproc.run(pp, args)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\modules\scripts_postprocessing.py", line 130, in run
    script.process(pp, **process_args)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\scripts\postprocessing_upscale.py", line 96, in process
    upscaled_image = self.upscale(pp.image, pp.info, upscaler1, upscale_mode, upscale_by, upscale_to_width, upscale_to_height, upscale_crop)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\scripts\postprocessing_upscale.py", line 66, in upscale
    image = upscaler.scaler.upscale(image, upscale_by, upscaler.data_path)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\modules\upscaler.py", line 63, in upscale
    img = self.do_upscale(img, selected_model)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\extensions-builtin\ScuNET\scripts\scunet_model.py", line 60, in do_upscale
    output = model(img)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\extensions-builtin\ScuNET\scunet_model_arch.py", line 245, in forward
    x2 = self.m_down1(x1)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\extensions-builtin\ScuNET\scunet_model_arch.py", line 159, in forward
    trans_x = self.trans_block(trans_x)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\extensions-builtin\ScuNET\scunet_model_arch.py", line 122, in forward
    x = x + self.drop_path(self.msa(self.ln1(x)))
  File "C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\extensions-builtin\ScuNET\scunet_model_arch.py", line 80, in forward
    sim = sim.masked_fill_(attn_mask, float("-inf"))
RuntimeError: m_device->CreateOperator(&opDesc, IID_PPV_ARGS(&op))

Error completing request
Arguments: (0, <PIL.Image.Image image mode=RGB size=512x512 at 0x1D26A63D630>, None, '', '', True, 0, 4, 512, 512, True, 'ScuNET PSNR', 'None', 0, 0, 0, 0) {}
Traceback (most recent call last):
  File "C:\Stable diffusion\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "C:\Stable diffusion\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\modules\postprocessing.py", line 56, in run_postprocessing
    scripts.scripts_postproc.run(pp, args)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\modules\scripts_postprocessing.py", line 130, in run
    script.process(pp, **process_args)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\scripts\postprocessing_upscale.py", line 96, in process
    upscaled_image = self.upscale(pp.image, pp.info, upscaler1, upscale_mode, upscale_by, upscale_to_width, upscale_to_height, upscale_crop)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\scripts\postprocessing_upscale.py", line 66, in upscale
    image = upscaler.scaler.upscale(image, upscale_by, upscaler.data_path)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\modules\upscaler.py", line 63, in upscale
    img = self.do_upscale(img, selected_model)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\extensions-builtin\ScuNET\scripts\scunet_model.py", line 60, in do_upscale
    output = model(img)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\extensions-builtin\ScuNET\scunet_model_arch.py", line 245, in forward
    x2 = self.m_down1(x1)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\container.py", line 204, in forward
    input = module(input)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\extensions-builtin\ScuNET\scunet_model_arch.py", line 159, in forward
    trans_x = self.trans_block(trans_x)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\extensions-builtin\ScuNET\scunet_model_arch.py", line 122, in forward
    x = x + self.drop_path(self.msa(self.ln1(x)))
  File "C:\Stable diffusion\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Stable diffusion\stable-diffusion-webui-directml\extensions-builtin\ScuNET\scunet_model_arch.py", line 80, in forward
    sim = sim.masked_fill_(attn_mask, float("-inf"))
RuntimeError: m_device->CreateOperator(&opDesc, IID_PPV_ARGS(&op))
```

### Additional information

i would say thank you for fixing previous problem, it was quick 👍

my system spec:
Acer Swift 3X
I5 1135G7
16 GB Ram
Intel xe graphic 80eu (shared memory)
intel xe max (4gb vram)

**Comment by lshqqytiger** [comment]
ScuNET works now. I added a fallback to cpu on specific part.

**Comment by lshqqytiger** [comment]
SwinIR works now. Similar solution.

**Comment by Nathan-dm** [comment]
great job bro, everything work fine now, but i still have some issues with some sampler having different time to finished(i give you the report ASAP), on task manager my gpu load seem spiking and unstable, is it normal?

**Comment by Miraihi** [comment]
Different samplers offer different algorhytms, so they have different speeds. That's normal.

**Comment by Nathan-dm** [comment]
ok i got it, but it didn't work with `--medvram` i got out of memory , i tried with 512x512, 20 steps, euler a sampler
and i removed `--opt-split-attention-v1 ` arguments and keep `--opt-sub-quad-attention`

> Different samplers offer different algorithms, so they have different speeds. That's normal. Also you probably should try `--medvram` instead of `--lowvram` and see how it works out. Also out of two `opt` arguments you should choose one. I think that `--opt-sub-quad-attention` is better.

**Comment by Miraihi** [comment]
I've made [a guide](https://github.com/lshqqytiger/stable-diffusion-webui-directml/discussions/84) for new users. Maybe going to be useful.

**Comment by Nathan-dm** [comment]
thank you for the guide, i will certainly read it
