### ISSUE TITLE
[Bug]: error loading torch_python.dll or one of its dependencies 

### ISSUE THREAD

**Issue by Shortcutz** [lshqqytiger/stable-diffusion-webui-directml#85]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

If I start the application, I receive this message:

```
PS C:\Users\Yulia\Desktop\stable-diffusion-webui-directml> .\webui-user.bat
venv "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: fd59537df9420bb14c1d6330ec59e30ce870a481
Installing requirements for Web UI
Launching Web UI with arguments: --skip-torch-cuda-test --precision full --no-half --deepdanbooru --autolaunch --opt-channelslast --api
Traceback (most recent call last):
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\launch.py", line 353, in <module>
    start()
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\launch.py", line 344, in start
    import webui
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\webui.py", line 16, in <module>
    from modules import paths, timer, import_hook, errors
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\modules\paths.py", line 5, in <module>
    import modules.safe
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\modules\safe.py", line 9, in <module>
    import torch
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\venv\lib\site-packages\torch\__init__.py", line 139, in <module>
    raise err
OSError: [WinError 126] Das angegebene Modul wurde nicht gefunden. Error loading "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\venv\lib\site-packages\torch\lib\torch_python.dll" or one of its dependencies.
```

### Steps to reproduce the problem

1. open powershell
2.  .\webui-user.bat
3. error

### What should have happened?

Programm should've started as usual

### Commit where the problem happens

fd59537df9420bb14c1d6330ec59e30ce870a481

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--skip-torch-cuda-test --precision full --no-half --deepdanbooru --autolaunch --opt-channelslast --api
```

### List of extensions

No

### Console logs

```Shell
PS C:\Users\Yulia\Desktop\stable-diffusion-webui-directml> .\webui-user.bat
venv "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: fd59537df9420bb14c1d6330ec59e30ce870a481
Installing requirements for Web UI
Launching Web UI with arguments: --skip-torch-cuda-test --precision full --no-half --deepdanbooru --autolaunch --opt-channelslast --api
Traceback (most recent call last):
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\launch.py", line 353, in <module>
    start()
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\launch.py", line 344, in start
    import webui
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\webui.py", line 16, in <module>
    from modules import paths, timer, import_hook, errors
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\modules\paths.py", line 5, in <module>
    import modules.safe
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\modules\safe.py", line 9, in <module>
    import torch
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\venv\lib\site-packages\torch\__init__.py", line 139, in <module>
    raise err
OSError: [WinError 126] Das angegebene Modul wurde nicht gefunden. Error loading "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\venv\lib\site-packages\torch\lib\torch_python.dll" or one of its dependencies.
```
```


### Additional information

_No response_

**Comment by lshqqytiger** [comment]
Reinstall `torch` and try again.
```
$ pip install torch --reinstall
```

**Comment by Shortcutz** [comment]
did not change unfortunately 👍 

```
PS C:\Users\Yulia\Desktop\stable-diffusion-webui-directml> pip install torch --force-reinstall --ignore-installed
Collecting torch
  Using cached torch-2.0.0-cp310-cp310-win_amd64.whl (172.3 MB)
Collecting filelock (from torch)
  Using cached filelock-3.11.0-py3-none-any.whl (10.0 kB)
Collecting typing-extensions (from torch)
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting sympy (from torch)
  Using cached sympy-1.11.1-py3-none-any.whl (6.5 MB)
Collecting networkx (from torch)
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting jinja2 (from torch)
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting MarkupSafe>=2.0 (from jinja2->torch)
  Using cached MarkupSafe-2.1.2-cp310-cp310-win_amd64.whl (16 kB)
Collecting mpmath>=0.19 (from sympy->torch)
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: mpmath, typing-extensions, sympy, networkx, MarkupSafe, filelock, jinja2, torch
Successfully installed MarkupSafe-2.1.2 filelock-3.11.0 jinja2-3.1.2 mpmath-1.3.0 networkx-3.1 sympy-1.11.1 torch-1.12.1+cu113 typing-extensions-4.5.0
PS C:\Users\Yulia\Desktop\stable-diffusion-webui-directml> .\webui-user.bat
venv "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: fd59537df9420bb14c1d6330ec59e30ce870a481
Installing requirements for Web UI
Launching Web UI with arguments: --skip-torch-cuda-test --precision full --no-half --deepdanbooru --autolaunch --opt-channelslast --api
Traceback (most recent call last):
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\launch.py", line 353, in <module>
    start()
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\launch.py", line 344, in start
    import webui
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\webui.py", line 16, in <module>
    from modules import paths, timer, import_hook, errors
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\modules\paths.py", line 5, in <module>
    import modules.safe
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\modules\safe.py", line 9, in <module>
    import torch
  File "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\venv\lib\site-packages\torch\__init__.py", line 139, in <module>
    raise err
OSError: [WinError 126] Das angegebene Modul wurde nicht gefunden. Error loading "C:\Users\Yulia\Desktop\stable-diffusion-webui-directml\venv\lib\site-packages\torch\lib\torch_python.dll" or one of its dependencies.
```

**Comment by Tanuki33** [comment]
first you need activate the virtual env
`venv\Scripts\activate`
then
`pip install torch --force-reinstall --ignore-installed`
or
`pip install --ignore-installed -r requirements.txt`

**Comment by Shortcutz** [comment]
Thank you!

I tried to quickly google about the virtual env and found that there should be an activate-file that I'm missing? I downloaded the missing files that I noticed:

activate
activate.bat
Activate.ps1
deactivate.bat
pip.exe
pip3.10.exe
pip3.exe

and added them to the Script-folder.

It looks good so far, do you know how I can limit my update to specific versions? I get this message here while installing torch via pip:

```ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
open-clip-torch 2.7.0 requires protobuf==3.20.0, but you have protobuf 3.20.3 which is incompatible.```

funny thing is, if I downscale to protobuf 3.20.0 I get:

```ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
onnx 1.13.1 requires protobuf<4,>=3.20.2, but you have protobuf 3.20.0 which is incompatible.```

Should I adjust something in requirements.txt?

**Comment by Shortcutz** [comment]
I realized I could just download everything again and now it works again! 

Thank you for your help!
