### ISSUE TITLE
[Bug]: Error Completing resquest

### ISSUE THREAD

**Issue by UnrealSimulation** [lshqqytiger/stable-diffusion-webui-directml#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Impossible to do any generation with text to image or image to image with this build

### Steps to reproduce the problem

1. Type anything in the prompt
2. Generate
3. Failed.

### What should have happened?

Generate an image.

### Commit where the problem happens

dd4dd2bd

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--medvram --no-half --precision full --no-half-vae --opt-sub-quad-attention --opt-split-attention-v1
```

### List of extensions

No

### Console logs

```Shell
Already up to date.
venv "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
Python 3.10.7 (tags/v3.10.7:6cc6b13, Sep  5 2022, 14:08:36) [MSC v.1933 64 bit (AMD64)]
Commit hash: dd4dd2bd0e07babc843308326c56efcabcb06e8c
Installing requirements for Web UI
Launching Web UI with arguments: --medvram --no-half --precision full --no-half-vae --opt-sub-quad-attention --opt-split-attention-v1
Interrogations are fallen back to cpu. This doesn't affect on image generation. But if you want to use interrogate (CLIP or DeepBooru), check out this issue: https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/10
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
Loading weights [8a02392904] from D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\models\Stable-diffusion\clarity_2.safetensors
Creating model from config: D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying sub-quadratic cross attention optimization.
Textual inversion embeddings loaded(0):
Textual inversion embeddings skipped(3): nartfixer, nfixer, nrealfixer
Model loaded in 1.8s (load weights from disk: 0.3s, load config: 0.1s, create model: 0.5s, apply weights to model: 0.8s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 9.3s (import torch: 2.2s, import gradio: 1.2s, import ldm: 0.4s, other imports: 1.7s, load scripts: 1.2s, load SD checkpoint: 1.9s, create ui: 0.5s, gradio launch: 0.1s).
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]
Error completing request
Arguments: ('task(l8k05jybhybcfny)', 'Deviant Art,', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\modules\processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\modules\processing.py", line 653, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\modules\processing.py", line 869, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 358, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 234, in launch_sampling
    return func()
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 358, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\sampling.py", line 150, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 132, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict([cond_in[a:b]], image_cond_in[a:b]))
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 72, in sigma_to_t
    low_idx = dists.ge(0).cumsum(dim=0).argmax(dim=0).clamp(max=self.log_sigmas.shape[0] - 2)
RuntimeError

  0%|                                                                                                                  | 0/16 [00:00<?, ?it/s]
Error completing request
Arguments: ('task(goctdizvsoq7xfw)', 0, 'deviant art', '', [], <PIL.Image.Image image mode=RGBA size=512x640 at 0x2C4FF8B9750>, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.75, -1.0, -1.0, 0, 0, 0, False, 512, 512, 0, 0, 32, 0, '', '', '', [], 0, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', 0, '', 0, '', True, False, False, False, 0, True, True, True, 0, 0.1, 1, 'None', False, 0, 2, 512, 512, False) {}
Traceback (most recent call last):
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\modules\img2img.py", line 172, in img2img
    processed = process_images(p)
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\modules\processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\modules\processing.py", line 653, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\modules\processing.py", line 1087, in sample
    samples = self.sampler.sample_img2img(self, self.init_latent, x, conditioning, unconditional_conditioning, image_conditioning=self.image_conditioning)
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 331, in sample_img2img
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 234, in launch_sampling
    return func()
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 331, in <lambda>
    samples = self.launch_sampling(t_enc + 1, lambda: self.func(self.model_wrap_cfg, xi, extra_args=extra_args, disable=False, callback=self.callback_state, **extra_params_kwargs))
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\sampling.py", line 150, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\modules\sd_samplers_kdiffusion.py", line 132, in forward
    x_out[a:b] = self.inner_model(x_in[a:b], sigma_in[a:b], cond=make_condition_dict([cond_in[a:b]], image_cond_in[a:b]))
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "D:\Super Stable Diffusion 2.0\stable-diffusion-webui-amd\stable-diffusion-webui-directml\repositories\k-diffusion\k_diffusion\external.py", line 72, in sigma_to_t
    low_idx = dists.ge(0).cumsum(dim=0).argmax(dim=0).clamp(max=self.log_sigmas.shape[0] - 2)
RuntimeError
```

### Additional information

Since the last update, Stable Diffusion is not working for me.

**Comment by scott-dft** [comment]
Second this issue. All attempts to generate fail at the same point as above.
Note that is with latest commit:
Commit hash: fd59537df9420bb14c1d6330ec59e30ce870a481

**Comment by lshqqytiger** [comment]
`cumsum` operator is now implemented for boolean tensors.
We no longer ought to convert them to int.
#77
