### ISSUE TITLE
[Bug]: don't gen images

### ISSUE THREAD

**Issue by Ryanclow112** [lshqqytiger/stable-diffusion-webui-directml#92]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

RuntimeError

### Steps to reproduce the problem

execute webui-user.bat and click to gen image

### What should have happened?

gen image

### Commit where the problem happens

fd59537

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --disable-nan-check --autolaunch --opt-split-attention
set GIT_SSL_NO_VERIFY=true

call webui.bat
```

### List of extensions

a1111-sd-webui-tagcomplete
posex
sd-webui-depth-lib
LDSR
Lora
ScuNET
SwinIR
prompt-bracket-checker

### Console logs

```Shell
venv "D:\Ai\stable-diffusion-webui-directml-master\venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: <none>
Installing requirements for Web UI
Launching Web UI with arguments: --disable-nan-check --autolaunch --opt-split-attention
Interrogations are fallen back to cpu. This doesn't affect on image generation. But if you want to use interrogate (CLIP or DeepBooru), check out this issue: https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/10
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
Loading weights [771c8fd970] from D:\Ai\stable-diffusion-webui-directml-master\models\Stable-diffusion\meinapastel_V4.safetensors
Creating model from config: D:\Ai\stable-diffusion-webui-directml-master\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(0):
Model loaded in 2.9s (load weights from disk: 0.2s, create model: 0.4s, apply weights to model: 0.5s, apply half(): 0.7s, move model to device: 1.0s).
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 11.6s (import torch: 1.8s, import gradio: 1.2s, import ldm: 0.5s, other imports: 2.2s, load scripts: 1.4s, load SD checkpoint: 3.0s, create ui: 1.0s, gradio launch: 0.4s).
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]
Error completing request
Arguments: ('task(9zqqasq3zvqot6b)', '1', '', [], 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, '', 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '', 0, '', 0, '', True, False, False, False, 0) {}
Traceback (most recent call last):
  File "D:\Ai\stable-diffusion-webui-directml-master\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "D:\Ai\stable-diffusion-webui-directml-master\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "D:\Ai\stable-diffusion-webui-directml-master\modules\txt2img.py", line 56, in txt2img
    processed = process_images(p)
  File "D:\Ai\stable-diffusion-webui-directml-master\modules\processing.py", line 503, in process_images
    res = process_images_inner(p)
  File "D:\Ai\stable-diffusion-webui-directml-master\modules\processing.py", line 653, in process_images_inner
    samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
  File "D:\Ai\stable-diffusion-webui-directml-master\modules\processing.py", line 869, in sample
    samples = self.sampler.sample(self, x, conditioning, unconditional_conditioning, image_conditioning=self.txt2img_image_conditioning(x))
  File "D:\Ai\stable-diffusion-webui-directml-master\modules\sd_samplers_kdiffusion.py", line 358, in sample
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "D:\Ai\stable-diffusion-webui-directml-master\modules\sd_samplers_kdiffusion.py", line 234, in launch_sampling
    return func()
  File "D:\Ai\stable-diffusion-webui-directml-master\modules\sd_samplers_kdiffusion.py", line 358, in <lambda>
    samples = self.launch_sampling(steps, lambda: self.func(self.model_wrap_cfg, x, extra_args={
  File "D:\Ai\stable-diffusion-webui-directml-master\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Ai\stable-diffusion-webui-directml-master\repositories\k-diffusion\k_diffusion\sampling.py", line 150, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\Ai\stable-diffusion-webui-directml-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Ai\stable-diffusion-webui-directml-master\modules\sd_samplers_kdiffusion.py", line 126, in forward
    x_out = self.inner_model(x_in, sigma_in, cond=make_condition_dict([cond_in], image_cond_in))
  File "D:\Ai\stable-diffusion-webui-directml-master\venv\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Ai\stable-diffusion-webui-directml-master\repositories\k-diffusion\k_diffusion\external.py", line 112, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "D:\Ai\stable-diffusion-webui-directml-master\repositories\k-diffusion\k_diffusion\external.py", line 72, in sigma_to_t
    low_idx = dists.ge(0).cumsum(dim=0).argmax(dim=0).clamp(max=self.log_sigmas.shape[0] - 2)
RuntimeError
```

**Comment by lshqqytiger** [comment]
#77

**Comment by Ryanclow112** [comment]
ok, after pip install torch-directml --upgrade it upgrades to last but still nothing. After del venv folder it works, thx
