### ISSUE TITLE
[Bug]: launch.py doesn't install the base Stable Diffusion files

### ISSUE THREAD

**Issue by TeutonJon78** [lshqqytiger/stable-diffusion-webui-directml#98]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

I was trying to test the new commits before updating my existing install. On a fresh clone of the repo, it no longer installs all the  needed files -- specifically the base Stable Diffusion files.

In launcher.py function "def prepare_environment():"

stable_diffusion_repo = os.environ.get('STABLE_DIFFUSION_REPO', "https://github.com/Stability-AI/stablediffusion.git")

was switched to 

sd_repo = os.environ.get('BLIP_REPO', 'https://github.com/lshqqytiger/stablediffusion-directml.git')

However this isn't pulling in the repo into the correct location.

My guess is K-deformers will have a similar problem:

k_diffusion_repo = os.environ.get('K_DIFFUSION_REPO', 'https://github.com/crowsonkb/k-diffusion.git')

switched to 

k_diffusion_repo = os.environ.get('BLIP_REPO', 'https://github.com/lshqqytiger/k-diffusion-directml.git')

My guess is the error is a copy and paste of BLIP_REPO rather than the correct repo defines.

### Steps to reproduce the problem

1. clone the repo fresh
2. run webui-user.bat

### What should have happened?

The prereqs should be installed and the server started.

### Commit where the problem happens

271edfa8d6b66e0d0b3f0b2964f35598df69d2a5

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
No
```

### List of extensions

No

### Console logs

```Shell
Creating venv in directory D:\Graphic Design\AI\webui-temp\venv using python "C:\Program Files\Python310\python.exe"
venv "D:\Graphic Design\AI\webui-temp\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Commit hash: 271edfa8d6b66e0d0b3f0b2964f35598df69d2a5
Installing torch and torchvision
Collecting torch==2.0.0
  Using cached torch-2.0.0-cp310-cp310-win_amd64.whl (172.3 MB)
Collecting torchvision==0.15.1
  Using cached torchvision-0.15.1-cp310-cp310-win_amd64.whl (1.2 MB)
Collecting torch-directml
  Using cached torch_directml-0.2.0.dev230426-cp310-cp310-win_amd64.whl (8.2 MB)
Collecting typing-extensions
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting filelock
  Using cached filelock-3.12.0-py3-none-any.whl (10 kB)
Collecting sympy
  Using cached sympy-1.11.1-py3-none-any.whl (6.5 MB)
Collecting jinja2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting networkx
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting requests
  Using cached requests-2.29.0-py3-none-any.whl (62 kB)
Collecting pillow!=8.3.*,>=5.3.0
  Using cached Pillow-9.5.0-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting numpy
  Using cached numpy-1.24.3-cp310-cp310-win_amd64.whl (14.8 MB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.2-cp310-cp310-win_amd64.whl (16 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.4-py3-none-any.whl (61 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.1.0-cp310-cp310-win_amd64.whl (97 kB)
Collecting mpmath>=0.19
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: mpmath, urllib3, typing-extensions, sympy, pillow, numpy, networkx, MarkupSafe, idna, filelock, charset-normalizer, certifi, requests, jinja2, torch, torchvision, torch-directml
Successfully installed MarkupSafe-2.1.2 certifi-2022.12.7 charset-normalizer-3.1.0 filelock-3.12.0 idna-3.4 jinja2-3.1.2 mpmath-1.3.0 networkx-3.1 numpy-1.24.3 pillow-9.5.0 requests-2.29.0 sympy-1.11.1 torch-2.0.0 torch-directml-0.2.0.dev230426 torchvision-0.15.1 typing-extensions-4.5.0 urllib3-1.26.15

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: D:\Graphic Design\AI\webui-temp\venv\Scripts\python.exe -m pip install --upgrade pip
Installing gfpgan
Installing clip
Installing open_clip
Installing requirements for CodeFormer
Installing requirements
Launching Web UI with arguments:
Traceback (most recent call last):
  File "D:\Graphic Design\AI\webui-temp\launch.py", line 348, in <module>
    start()
  File "D:\Graphic Design\AI\webui-temp\launch.py", line 339, in start
    import webui
  File "D:\Graphic Design\AI\webui-temp\webui.py", line 17, in <module>
    from modules import paths, timer, import_hook, errors
  File "D:\Graphic Design\AI\webui-temp\modules\paths.py", line 19, in <module>
    assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_sd_paths)
AssertionError: Couldn't find Stable Diffusion in any of: ['D:\\Graphic Design\\AI\\webui-temp\\repositories/stable-diffusion-stability-ai', '.', 'D:\\Graphic Design\\AI']
Press any key to continue . . .
```

**Comment by TeutonJon78** [comment]
Oops, it seems this is a dup of #46.
